### DISCUSSION TITLE
The generator is unable to generate Metrics

### DISCUSSION THREAD

**Discussion by HamzaChetoui** [prometheus/snmp_exporter#1018] [Q&A]
### **Host operating system: output of uname -a**

Linux xxxxxxxxx 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### **snmp_exporter version: output of snmp_exporter -version**

V0.22.0

### **What device/snmpwalk OID are you using?**

OID 1.3.6.1.2.1.33.2                upsTraps
OID 1.3.6.1.2.1.33.1.6.3           upsWellKnownAlarms
OID 1.3.6.1.4.1.534.1.11.4.1.0 XUPS-MIB
```
modules:
  MY-WALKS:
    walk:
    - 1.3.6.1.2.1.33.2 #upsTraps
    - 1.3.6.1.2.1.33.1.6.3 #upsWellKnownAlarms
    - 1.3.6.1.4.1.534.1.11.4.1.0 #XUPS-MIB
    version: 3
    max_repetitions: 25
    retries: 3
    timeout: 10s
    auth:
      username: 'readonly'
      security_level: authPriv
      password: 'xxxxxxxxxxx'
      auth_protocol: SHA256
      priv_protocol: AES
      priv_password: 'xxxxxxxxxxx'
```

### **What did you do that produced an error?**

`
./generator generate
`

### **What did you expect to see?**

snmp.yml is generated with metrics array is not empty

### **What did you see instead?**

snmp.yml is generated but there is **no metrics**

```
# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
MY-WALK:
  walk:
  - 1.3.6.1.2.1.33.1.6.3
  - 1.3.6.1.2.1.33.2
  - 1.3.6.1.4.1.534.1.11.4.1.0
  metrics: []
  version: 3
  max_repetitions: 25
  retries: 3
  timeout: 10s
  auth:
    security_level: authPriv
    username: readonly
    password: xxxxxxxxxxx
    auth_protocol: SHA256
    priv_protocol: AES
    priv_password: xxxxxxxxxxx
```

How can I monitore if i'm not receiving metrics ?

Thanks in advance!
