### DISCUSSION TITLE
The OID value queried is a string and I want to convert it into a numerical value.

### DISCUSSION THREAD

**Discussion by jycgxds** [prometheus/snmp_exporter#1023] [Q&A]
Contents of my snmp.yml file:
```
tttt:
   walk:
   - 1.3.6.1.4.1.15.8886.1067.1.0
   metrics:
   - name: ups
     oid: 1.3.6.1.4.1.15.8886.1067.1.0
     type: DisplayString
   version: 2
   auth:
     community: public

```

The result queried after running through snmp-exporter is
![image](https://github.com/prometheus/snmp_exporter/assets/44128073/c05e67cd-607e-4fe4-83f4-072e9d825f86)

**Comment by dl-romero** [comment]
@jycgxds. I did some digging, and this is what worked for me. Add "regex_extracts" bits to your snmp.yml.
```
modules:
  coolit:
    retries: 2
    timeout: 30s
    walk:
    - 1.3.6.1.4.1.30518
    get:
    - 1.3.6.1.4.1.30518
    metrics:
    - name: cdu_primary_supply_temp
      oid:  1.3.6.1.4.1.30518.16.2.1.3.1
      type: DisplayString
      help: Units = oF
      regex_extracts:
        Value:
          - regex: '(.*)'
            value: '$1'
```
I noticed the output now as an appended "Value" to the metric name and also the HELP has "(regex extracted)" appended to it.

![image](https://github.com/user-attachments/assets/97c9d5ca-5369-4a92-9ff9-1c385c26c745)
