### DISCUSSION TITLE
Consuming same OID by multiple metrics

### DISCUSSION THREAD

**Discussion by freeyssu** [prometheus/snmp_exporter#1058] [Q&A] [answered]
Hi team.

I am searching a way to create multiple metrics by consuming one OID.
Here is my example. I would like to create two metrics to store alert(0 or 1) and the other one stores actual enum values.
However, the exporter return pdu_system_status metric only. Probably it seems like the exporter doesn't support using same OID multiple times?

```
  metrics:
    - name: pdu_system_alert
      oid: 1.3.6.1.4.1.1718.4.1.2.3.1.1.1
      type: float
      regex_extracts:
        Status:
          - regex: '0'
            value: '0'
          - regex: '[^0][0-9]?'
            value: '1'
    - name: pdu_system_status
      oid: 1.3.6.1.4.1.1718.4.1.2.3.1.1.1
      type: gauge
      enum_values:
        0 : normal
        1 : disabled
        2 : purged
        5 : reading
```

**Comment by SuperQ** [comment]
You really should use the generator, rather than try and hand-craft these.

What you want is to is use `EnumAsInfo` or `EnumAsStateSet` mapping to convert the enum values to labels.

See this example: https://github.com/SuperQ/tools/tree/master/snmp_exporter/ServerTech

**Reply by freeyssu** [reply]
Yeah, Thanks. 
I just find a way myself :)
I am considering Enum set as well and will try it !

**Comment by freeyssu** [comment, marked as answer]
Ah, I think I can use regex multiple times :)
Use this as a reference somebody who want to create multiple metrics by one OID

```
  metrics:
    - name: pdu_system
      oid: 1.3.6.1.4.1.1718.4.1.2.3.1.1.1
      type: float
      regex_extracts:
        _alert:
          - regex: '0'
            value: '0'
          - regex: '[^0][0-9]?'
            value: '1'
        _status:
          - regex: (.*)
            value: $1
      enum_values:
        0 : normal
        1 : disabled
        2 : purged
        5 : reading
```
