### DISCUSSION TITLE
Dynamic OID

### DISCUSSION THREAD

**Discussion by northboys** [prometheus/snmp_exporter#1075] [General]
Hi guys,
how can I add a dynamic OID in the configuration file, I have a case when I want to take the IP of a device, the oid is mixed with the IP, how do I avoid having to add the oid one by one when there are many devices to be monitored?

for example:
using snmpwalk
```
iso.3.6.1.2.1.3.1.1.1.8.1.192.168.0.74 = INTEGER: 8
iso.3.6.1.2.1.3.1.1.2.8.1.192.168.0.74 = Hex-STRING: 00 01 02 03 04 CC
iso.3.6.1.2.1.3.1.1.3.8.1.192.168.0.74 = IpAddress: 192.168.0.74
```
is it possible to add OID like this

```
  metrics:
    - name: mClientIPaddr
      oid: "1.3.6.1.2.1.3.1.1.2.8.1.*"
      type: DisplayString
```

**Comment by SuperQ** [comment]
Those are different OIDs with different indexes. In fact, it looks like that is just part of `atTable` which comes from `RFC1213-MIB`.

The only difficulty here is that `RFC1213-MIB` has conflicts with the newer `SNMPv2-TC` MIB, so you need a separate set of MIBs to avoid those conflicts.

Here's what I get when I setup a generator.yml:
```yaml
modules:
  atTable:
    walk:
      - atTable
```

When I generate that with the `RFC1213-MIB` in my MIBDIRS I get this snmp.yml configuration:
```yaml
# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
modules:
  atTable:
    walk:
    - 1.3.6.1.2.1.3.1
    metrics:
    - name: atIfIndex
      oid: 1.3.6.1.2.1.3.1.1.1
      type: gauge
      help: The interface on which this entry's equivalence is effective - 1.3.6.1.2.1.3.1.1.1
      indexes:
      - labelname: atIfIndex
        type: gauge
      - labelname: atNetAddress
        type: InetAddressIPv4
    - name: atPhysAddress
      oid: 1.3.6.1.2.1.3.1.1.2
      type: PhysAddress48
      help: The media-dependent `physical' address - 1.3.6.1.2.1.3.1.1.2
      indexes:
      - labelname: atIfIndex
        type: gauge
      - labelname: atNetAddress
        type: InetAddressIPv4
    - name: atNetAddress
      oid: 1.3.6.1.2.1.3.1.1.3
      type: InetAddressIPv4
      help: The NetworkAddress (e.g., the IP address) corresponding to the media-dependent
        `physical' address. - 1.3.6.1.2.1.3.1.1.3
      indexes:
      - labelname: atIfIndex
        type: gauge
      - labelname: atNetAddress
        type: InetAddressIPv4
```

If you read the `atEntry` definition in the MIB you'll see how the INDEX is defined:

```
atEntry OBJECT-TYPE
    SYNTAX  AtEntry
    ACCESS  not-accessible
    STATUS  deprecated
    DESCRIPTION
            "Each entry contains one NetworkAddress to
            `physical' address equivalence."
    INDEX   { atIfIndex,
              atNetAddress }
    ::= { atTable 1 }
```

In this case, the index is actually two parts. The single octet `atIfIndex` and the 4 octet `atNetAddress`

You can see how things are broken up. The `iso.3.6.1.2.1.3.1.1.1` is the actual metric entry. The `.8.` is the index number, and the `.1.192.168.0.74` is an `atNetAddress`, which is defined as a `RFC1155-SMI` `NetworkAddress` which is defined as an `internet IpAddress`, which is `1` plus 4 octets of an IPv4 address.

Most of this MIB is marked deprecated, I think there are newer OIDs that should have the same data. But I don't remember off the top of my head what those are.
