### DISCUSSION TITLE
Override group of metrics

### DISCUSSION THREAD

**Discussion by llamafilm** [prometheus/snmp_exporter#1085] [Ideas]
Sometimes I need to apply the same override to several metrics, so it would be useful to write it just once in the config by specifying the parent OID.  As an example, here is a snippet of my config for Dataprobe iBoot PDU:
```yaml
  iboot_pdu:
    walk:
      - 1.3.6.1.4.1.1418.6.1.1 # firmware
      - 1.3.6.1.4.1.1418.6.6 # sensors
      - 1.3.6.1.4.1.1418.6.5 # outletTable
    lookups:
      - source_indexes: [outletIndex]
        # explicit OID needed until this PR is merged: https://github.com/prometheus/snmp_exporter/pull/828
        lookup: 1.3.6.1.4.1.1418.6.5.1.2
        drop_source_indexes: false
    overrides:
      voltageLC1:
        scale: 0.01
      currentLC1:
        scale: 0.01
      temperature1:
        scale: 0.01
      temperature2:
        scale: 0.01
```

Instead of specifying each metric with the same scaling factor, I'd like to do it like this:
```yaml
    overrides:
      1.3.6.1.4.1.1418.6.6:
        scale: 0.01
```

[iboot-pdu.mib.txt](https://github.com/prometheus/snmp_exporter/files/13822587/iboot-pdu.mib.txt)
