### DISCUSSION TITLE
index lookup not working

### DISCUSSION THREAD

**Discussion by llamafilm** [prometheus/snmp_exporter#1097] [Q&A]
I have 2 Barco cinema projectors of slightly different models, that both use the same MIB.  I'm trying to use `lookups` to apply the fanSpeedName as a label to each fanSpeed metric.  This works fine on one projector, but not on the other.

This is my config:
```yaml
  barco_projector:
    walk:
      - 1.3.6.1.4.1.12612.220.11.4.2.1.3.1.2 # fanSpeed
    lookups:
    - source_indexes: [fanSpeedIndex]
      lookup: fanSpeedName
      drop_source_indexes: false
```

The good one looks like this in the scrape:
```
fanSpeed{fanSpeedIndex="1",fanSpeedName="Blue formatter fan speed"} 5598
```

The bad one can't find the label:
```
fanSpeed{fanSpeedIndex="2",fanSpeedName=""} 4041
```

SnmpB shows that the good device is missing values for the index field:
![fan Tudum](https://github.com/prometheus/snmp_exporter/assets/3991046/38dcd234-05d2-4081-84bd-4ba9c0c81eec)

While the bad device does include numbers in that field:
![fan Home](https://github.com/prometheus/snmp_exporter/assets/3991046/0d1addff-28f3-470e-bb45-ba256a54d869)

This is the opposite of how I expected it to behave.  Why does this work when the index numbers are missing?

[MIB](https://github.com/prometheus/snmp_exporter/files/13972719/R33050003_00_MIBs.zip)
