### DISCUSSION TITLE
Only one SNMP target works at a time.

### DISCUSSION THREAD

**Discussion by ramarasty** [prometheus/snmp_exporter#1109] [Q&A]
Hello. I have been trying to add two SNMP targets, but only one of them works at a time. The first one to establish a connection is the one that works. I tested this by restarting snmp_exporter and reloading the one I wanted to work in the browser.
I can `snmpwalk` both at the same time without any issues. I also tested with PRTG and they both work fine.

This is my configuration:
```yaml
  - job_name: 'first'
    scrape_interval: 45s
    static_configs:
      - targets:
        - 192.168.0.190
    scheme: https
    metrics_path: /snmp
    params:
      auth: [first_auth]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: my-local-domain.com:9116

  - job_name: 'second'
    scrape_interval: 45s
    static_configs:
      - targets:
        - 192.168.0.191
    scheme: https
    metrics_path: /snmp
    params:
      auth: [second_auth]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: my-local-domain.com:9116
```

The error I get is:

```bash
An error has occurred while serving metrics:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: error getting target 192.168.0.190: request timeout (after 3 retries)
```

Here is what `tcpdump -i any -nn port snmp` shows for that IP:
```bash
15:44:28.166350 ens33 Out IP 192.168.0.233.44709 > 192.168.0.190.161:  F=r U="" E= C="" GetRequest(14)
15:44:28.167495 ens33 In  IP 192.168.0.190.161 > 192.168.0.233.44709:  F= U="" E=payload C="" Report(32)  .1.3.6.1.6.3.15.1.1.4.0=10946
15:44:28.189538 ens33 Out IP 192.168.0.233.44709 > 192.168.0.190.161:  F=apr U="my_snmp_user" [!scoped PDU]some_stuff
15:44:33.189984 ens33 Out IP 192.168.0.233.44709 > 192.168.0.190.161:  F=apr U="my_snmp_user" [!scoped PDU]some_stuff
15:44:38.194234 ens33 Out IP 192.168.0.233.44709 > 192.168.0.190.161:  F=apr U="my_snmp_user" [!scoped PDU]some_stuff
```

I get a response at first, but then nothing comes back.

I'm using v3. I tried to give them the same credentials and used v1 and v2c, but none worked. I also tried to combine them into one job, but that did not work either.

What could be the issue? Have I made a silly mistake in relabeling?
