### DISCUSSION TITLE
Enrich entSensorValue with ifAdminStatus using entAliasMappingTable

### DISCUSSION THREAD

**Discussion by KlettIT** [prometheus/snmp_exporter#1129] [Q&A]
Hi guys,

I currently have a functioning metric for entSensorValue. But now I would like to know for an alert rule whether the associated interface is administratively deactivated (aka ifAdminStatus ) for an optical sensor (voltage, dbm). For this I would need the IfIndex. After a bit of googling I stumbled across 'entAliasMappingTable' - I should be able to enrich the metric with this. However, it is not at all clear to me how I would formulate this in snmp.yaml as I would theoretically need a double lookup.

My snmp.yaml currently looks like this:

```
---

modules:

  cisco_bgp:
    retries: 3
    timeout: 10s
    max_repetitions: 10
    walk:
    - cbgpPeer2Table
    - cbgpPeer2AddrFamilyPrefixTable
    lookups:
    - source_indexes: [cbgpPeer2RemoteAddr]
      lookup: cbgpPeer2RemoteAs
    overrides:
      cbgpPeer2State:
        type: EnumAsStateSet
      cbgpPeer2AdminStatus:
        type: EnumAsStateSet
  
  cisco_fru:
    retries: 3
    timeout: 10s
    max_repetitions: 10
    walk:
    - cefcFRUPowerSupplyGroupTable
    - cefcFRUPowerStatusTable
    - cefcFanTrayStatusTable
    lookups:
    - source_indexes: [entPhysicalIndex]
      lookup: entPhysicalName

  cisco_env:
    retries: 3
    timeout: 10s
    max_repetitions: 10
    walk:
    - entPhysicalIndex
    - entPhysicalDescr
    - entPhysicalName
    - entSensorScale
    - entSensorType
    - entSensorPrecision
    - entSensorValue
    - entSensorThresholdTable
    - entAliasMappingTable
    lookups:
    - source_indexes: [entPhysicalIndex]
      lookup: entPhysicalDescr
    - source_indexes: [entPhysicalIndex]
      lookup: entPhysicalName
    - source_indexes: [entPhysicalIndex]
      lookup: entSensorType
    - source_indexes: [entPhysicalIndex]
      lookup: entSensorScale
    - source_indexes: [entPhysicalIndex]
      lookup: entSensorPrecision
    - source_indexes: [entPhysicalIndex, entSensorThresholdIndex]
      lookup: entSensorThresholdSeverity
    - source_indexes: [entPhysicalIndex, entSensorThresholdIndex]
      lookup: entSensorThresholdRelation
    - source_indexes: [entPhysicalIndex, entSensorThresholdIndex]
      lookup: entSensorThresholdEvaluation
    - source_indexes: [entPhysicalIndex, entAliasLogicalIndexOrZero]
      lookup:  entAliasMappingIdentifier ## here i would need probably another looker which uses entAliasMappingIdentifier to fetch ifIndex?
    overrides:
      entPhysicalIndex: {ignore: true}
      entPhysicalDescr: {ignore: true}
      entPhysicalName: {ignore: true}
      entSensorType: {ignore: true}
      entSensorThresholdIndex: {ignore: true}
      entSensorThresholdRelation: {ignore: true}
      entSensorThresholdSeverity: {ignore: true}
      entSensorThresholdEvaluation: {ignore: true}
      entSensorThresholdNotificationEnable: {ignore: true}
      entAliasLogicalIndexOrZero: {ignore: true}
      entAliasMappingIdentifier: {ignore: true}
```

Has anyone done this before or do you have an idea how it could be solved (possibly even better)?

Thanks in advance for any hints!
