### DISCUSSION TITLE
sysName showing as gauge and not display string

### DISCUSSION THREAD

**Discussion by G0nz0uk** [prometheus/snmp_exporter#1144] [General]
Hello,

I'm using SNMP Exporter (which is fab I must say!) to retrieve all out switches port info.  I just want to also add the SysName to the scrape but it's seems to show as a gauge like this:

```
snmp_scrape_walk_duration_seconds{module="if_mib"} 18.663328509
# HELP sysName An administratively-assigned name for this managed node - 1.3.6.1.2.1.1.5
# TYPE sysName gauge
sysName{sysName="Cisco-SW-5"} 1
```

Which seems to mean I can't show the name in Grafana as a string.

This is my generator.yml, can you see anything wrong?

```
---
  auths:
    cisco_v2:
      version: 2
      community: public
    aruba_v2:
      version: 2
      community: public
    extreme_v2:
      version: 2
      community: public

  modules:
    # Default IF-MIB interfaces table with ifIndex.
    if_mib:
      walk: [sysName, sysUpTime, interfaces, ifXTable]
      lookups:
        - source_indexes: [ifIndex]
          lookup: ifAlias
        - source_indexes: [ifIndex]
          # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
          lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
        - source_indexes: [ifIndex]
          # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
          lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
      overrides:
        ifAlias:
          ignore: true # Lookup metric
        ifDescr:
          ignore: true # Lookup metric
        ifName:
          ignore: true # Lookup metric
        ifType:
          type: EnumAsInfo
        sysName:
          type: DisplayString
```
