### DISCUSSION TITLE
generator bug?

### DISCUSSION THREAD

**Discussion by blissend** [prometheus/snmp_exporter#1149] [Q&A]
Trying to generate an snmp.yml file for my synology devices using the generator but get the below errors...

```
Starting generator ... done
Attaching to generator
generator    | ts=2024-03-31T21:44:24.592Z caller=net_snmp.go:175 level=info msg="Loading MIBs" from=/etc/mibs
generator    | ts=2024-03-31T21:44:24.600Z caller=main.go:124 level=warn msg="NetSNMP reported parse error(s)" errors=881
generator    | ts=2024-03-31T21:44:24.601Z caller=main.go:53 level=info msg="Generating config for module" module=synology
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=diskType
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=raidName
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=raidTotalSize
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=serviceName
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=diskModel
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=diskSMARTAttrStatus
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=diskSMARTInfoDevName
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=serialNumber
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=version
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=diskSMARTAttrName
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=modelName
generator    | ts=2024-03-31T21:44:24.601Z caller=tree.go:287 level=warn msg="Could not find node to override type" node=raidFreeSize
generator    | ts=2024-03-31T21:44:24.601Z caller=main.go:134 level=error msg="Error generating config netsnmp" err="cannot find oid '1.3.6.1.4.1.6574.1' to walk"
generator exited with code 1
```

I'm using the mibs from https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_MIB_File.zip and doing this via docker compose file...

```
---
version: "2.2"
services:
  generator:
    image: prom/snmp-generator:latest
    container_name: generator
    environment:
      - PUID=1024
      - PGID=100
    volumes:
      - /path/to/yaml:/etc/generator
      - /path/to/mibs:/etc/mibs
    command:
      - generate
      - '-m/etc/mibs'
      - '-g/etc/generator/generator.yml'
      - '-o/etc/generator/snmp.yml'
      - '--log.level=debug'
```

When I run the snmpwalk command `snmpwalk -v3 -l authPriv -u snmp-poller -a MD5 -A "REDACTED" -x DES -X "REDACTED" -u "REDACTED" REDACTED 1.3.6.1.4.1.6574.1` it works just fine.

What am I doing wrong? How do I get this to work? Is there a bug?
