### DISCUSSION TITLE
Help needed creatinging custom generator.yml

### DISCUSSION THREAD

**Discussion by andonovski** [prometheus/snmp_exporter#1151] [Q&A]
I need to monitor Fortinet devices using SNMP, and I have a problem how to generate generator.yml file from Fortinet MIBs.
Is there any automation process behind this, or generator.yml must be edited manually?

To me it's not clear at all what should I put in generator.yml, I guess I can't just put all the OIDS I find for the Fortinet devices.

**Comment by bastischubert** [comment]
totally depends on what you'd like to see from your fortinet devices.

i'm using a config for example that is scraping all metrics i'm interested in - you could also scrape interface metrics for example in one module and fortigate specific in another.

i manually went through the WHOLE mib file and created the generator config with the OIDs i needed - this is cumbersome but gave *ME* the best results as i know what i'm searching for - YMMV

my current config - just for ref:
```
modules:
  fortinet_fortigate:
    walk:
      - 1.3.6.1.4.1.12356.101.13.2.1.1.3 # fgHaStatsCpuUsage
      - 1.3.6.1.4.1.12356.101.3.2.1.1.5 # fgVdEntCpuUsage
      - 1.3.6.1.4.1.12356.101.4.1.3 # fgSysCpuUsage
      - 1.3.6.1.4.1.12356.101.13.2.1.1.4 # fgHaStatsMemUsage
      - 1.3.6.1.4.1.12356.101.13.2.1.1.2 # fgHaStatsSerial
      - 1.3.6.1.4.1.12356.101.13.2.1.1.6 # fgHaStatsSesCount
      - 1.3.6.1.4.1.12356.101.13.2.1.1.9 # fgHaStatsIdsCount
      - 1.3.6.1.4.1.12356.101.13.2.1.1.10 # fgHaStatsAvCount
      - 1.3.6.1.4.1.12356.101.13.2.1.1.11 # fgHaStatsHostname
      - 1.3.6.1.4.1.12356.101.13.1.1 # fgHaSystemMode
      - 1.3.6.1.4.1.12356.101.13.1.2 # fgHaGroupId
      - 1.3.6.1.4.1.12356.101.13.1.7 # fgHaGroupName
      - 1.3.6.1.2.1.1.1 # sysDescr
      - 1.3.6.1.2.1.1.3 # sysUpTime
      - 1.3.6.1.2.1.1.6 # sysLocation
      - 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - 1.3.6.1.2.1.2.2.1.3 # ifType
      - 1.3.6.1.2.1.2.2.1.7 # ifAdminStatus
      - 1.3.6.1.2.1.2.2.1.8 # ifOperStatus
      - 1.3.6.1.2.1.2.2.1.13 # ifInDiscards
      - 1.3.6.1.2.1.2.2.1.14 # ifInErrors
      - 1.3.6.1.2.1.2.2.1.19 # ifOutDiscards
      - 1.3.6.1.2.1.2.2.1.20 # ifOutErrors
      - 1.3.6.1.2.1.15.3.1.2 # bgpPeerState
      - 1.3.6.1.2.1.15.3.1.3 # bgpPeerAdminStatus
      - 1.3.6.1.2.1.15.3.1.16 # bgpPeerFsmEstablishedTime
      - 1.3.6.1.2.1.15.6.1.3 # bgp4PathAttrIpAddrPrefix
      - 1.3.6.1.2.1.31.1.1.1.1 # ifName
      - 1.3.6.1.2.1.31.1.1.1.6 # ifHCInOctets
      - 1.3.6.1.2.1.31.1.1.1.7 # ifHCInUcastPkts
      - 1.3.6.1.2.1.31.1.1.1.8 # ifHCInMulticastPkts
      - 1.3.6.1.2.1.31.1.1.1.9 # ifHCInBroadcastPkts
      - 1.3.6.1.2.1.31.1.1.1.10 # ifHCOutOctets
      - 1.3.6.1.2.1.31.1.1.1.11 # ifHCOutUcastPkts
      - 1.3.6.1.2.1.31.1.1.1.12 # ifHCOutMulticastPkts
      - 1.3.6.1.2.1.31.1.1.1.13 # ifHCOutBroadcastPkts
      - 1.3.6.1.2.1.31.1.1.1.15 # ifHighSpeed
      - 1.3.6.1.2.1.31.1.1.1.18 # ifAlias
      - 1.3.6.1.4.1.12356.101.3.2.1.1.2 # fgVdEntName
      - 1.3.6.1.4.1.12356.101.3.2.1.1.6 # fgVdEntMemUsage
      - 1.3.6.1.4.1.12356.101.3.2.1.1.7 # fgVdEntSesCount
      - 1.3.6.1.4.1.12356.101.4.1.1 # fgSysVersion
      - 1.3.6.1.4.1.12356.101.4.1.4 # fgSysMemUsage
      - 1.3.6.1.4.1.12356.101.4.1.6 # fgSysDiskUsage
      - 1.3.6.1.4.1.12356.101.4.1.8 # fgSysSesCount
      - 1.3.6.1.4.1.12356.101.4.1.15 # fgSysSes6Count
      - 1.3.6.1.4.1.12356.101.4.1.20 # fgSysUpTime
      - 1.3.6.1.4.1.12356.101.4.3.2.1.2 # fgHwSensorEntName
      - 1.3.6.1.4.1.12356.101.4.3.2.1.3 # fgHwSensorEntValue
      - 1.3.6.1.4.1.12356.101.4.3.2.1.4 # fgHwSensorEntAlarmStatus
      - 1.3.6.1.4.1.12356.101.12.1.1 # fgVpnTunnelUpCount
      - 1.3.6.1.4.1.12356.101.7.2.1.1.1 # fgIntfEntVdom
      - 1.3.6.1.4.1.12356.101.11.2.2.1.1 # fgIpSessNumber
      - 1.3.6.1.4.1.12356.101.11.2.3.1.1 # fgIp6SessNumber
      - 1.3.6.1.4.1.12356.101.12.2.2.1.2 # fgVpnTunEntPhase1Name
      - 1.3.6.1.4.1.12356.101.12.2.2.1.3 # fgVpnTunEntPhase2Name
      - 1.3.6.1.4.1.12356.101.12.2.2.1.18 # fgVpnTunEntInOctets
      - 1.3.6.1.4.1.12356.101.12.2.2.1.19 # fgVpnTunEntOutOctets
      - 1.3.6.1.4.1.12356.101.12.2.2.1.20 # fgVpnTunEntStatus
      - 1.3.6.1.4.1.12356.101.12.2.2.1.21 # fgVpnTunEntVdom
      - 1.3.6.1.4.1.12356.101.12.2.3.1.2 # fgVpnSslStatsLoginUsers
      - 1.3.6.1.4.1.12356.101.12.2.3.1.4 # fgVpnSslStatsActiveWebSessions
      - 1.3.6.1.4.1.12356.101.12.2.3.1.6 # fgVpnSslStatsActiveTunnels
      - 1.3.6.1.4.1.12356.101.12.2.4.1.2 # fgVpnSslTunnelVdom
      - 1.3.6.1.4.1.12356.101.12.2.4.1.3 # fgVpnSslTunnelUserName
      - 1.3.6.1.4.1.12356.101.12.2.4.1.4 # fgVpnSslTunnelSrcIp
      - 1.3.6.1.4.1.12356.101.12.2.4.1.7 # fgVpnSslTunnelBytesIn
      - 1.3.6.1.4.1.12356.101.12.2.4.1.8 # fgVpnSslTunnelBytesOut
      - 1.3.6.1.4.1.12356.101.14.2.3 # fgWcInfoWtpCapacity
      - 1.3.6.1.4.1.12356.101.14.2.5 # fgWcInfoWtpSessions
      - 1.3.6.1.4.1.12356.101.14.2.7 # fgWcInfoStationCount
      - 1.3.6.1.4.1.12356.101.14.4.3.1.3 # fgWcWtpConfigWtpName
      - 1.3.6.1.4.1.12356.101.14.4.4.1.3 # fgWcWtpSessionWtpIpAddress
      - 1.3.6.1.4.1.12356.101.14.4.4.1.6 # fgWcWtpSessionWtpBaseMacAddress
      - 1.3.6.1.4.1.12356.101.14.4.4.1.7 # fgWcWtpSessionConnectionState
      - 1.3.6.1.4.1.12356.101.14.4.4.1.8 # fgWcWtpSessionWtpUpTime
      - 1.3.6.1.4.1.12356.101.14.4.4.1.9 # fgWcWtpSessionWtpDaemonUpTime
      - 1.3.6.1.4.1.12356.101.14.4.4.1.10 # fgWcWtpSessionWtpSessionUpTime
      - 1.3.6.1.4.1.12356.101.14.4.4.1.12 # fgWcWtpSessionWtpModelNumber
      - 1.3.6.1.4.1.12356.101.14.4.4.1.14 # fgWcWtpSessionWtpSwVersion
      - 1.3.6.1.4.1.12356.101.14.4.4.1.17 # fgWcWtpSessionWtpStationCount
      - 1.3.6.1.4.1.12356.101.14.4.4.1.18 # fgWcWtpSessionWtpByteRxCount
      - 1.3.6.1.4.1.12356.101.14.4.4.1.19 # fgWcWtpSessionWtpByteTxCount
      - 1.3.6.1.4.1.12356.101.14.4.4.1.20 # fgWcWtpSessionWtpCpuUsage
      - 1.3.6.1.4.1.12356.101.14.4.4.1.21 # fgWcWtpSessionWtpMemoryUsage
      - 1.3.6.1.4.1.12356.101.14.4.5.1.7 # fgWcWtpSessionRadioOperatingChannel
      - 1.3.6.1.4.1.12356.101.14.4.5.1.8 # fgWcWtpSessionRadioOperatingPower
      - 1.3.6.1.4.1.12356.101.14.4.5.1.9 # fgWcWtpSessionRadioStationCount
      - 1.3.6.1.4.1.12356.101.14.4.6.1.3 # fgWcWtpSessionVapSsid
      - 1.3.6.1.4.1.12356.101.14.4.6.1.4 # fgWcWtpSessionVapStationCount
      - 1.3.6.1.4.1.12356.101.14.5.1.2 # fgWcStaWlan
      - 1.3.6.1.4.1.12356.101.14.5.1.3 # fgWcStaWtpId
      - 1.3.6.1.4.1.12356.101.14.5.1.7	# fgWcStaIpAddress
      - 1.3.6.1.4.1.12356.101.14.5.1.12 # fgWcStaSignal
      - 1.3.6.1.4.1.12356.101.14.5.1.13 # fgWcStaNoise
      - 1.3.6.1.4.1.12356.101.14.5.1.15 # fgWcStaBandwidthTx
      - 1.3.6.1.4.1.12356.101.14.5.1.16 # fgWcStaBandwidthRx
      - 1.3.6.1.4.1.12356.101.14.5.1.17 # fgWcStaChannel
      - 1.3.6.1.6.3.10.2.1.3 # snmpEngineTime
    overrides:
      fgHwSensorEntValue:
        regex_extracts:
          '':
          - regex: '(.*)'
            value: '$1'
      ifAdminStatus:
        type: DisplayString
      ifOperStatus:
        type: DisplayString
      fgWcWtpSessionVapSsid:
        type: DisplayString
```
