### DISCUSSION TITLE
No specific metrics are generated

### DISCUSSION THREAD

**Discussion by tksskt** [prometheus/snmp_exporter#1176] [Q&A]
### Host operating system: output of `uname -a`
```5.15.0-92-generic # 102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux  ```
### snmp_exporter version: output of `snmp_exporter -version`

```0.25.0```
### What device/snmpwalk OID are you using?
```
device: yamaha rtx810
OID: 1.3.6.1.4.1.1182.2.3.2.1.2
```
This is the mib file used
http://www.rtpro.yamaha.co.jp/RT/docs/mib/index.php

### What did you do that produced an error?
I generated snmp.yml with the generator, but certain metrics are not generated and data cannot be obtained.

generator.yml
```yml
auths:
  rtx810_v1_auth:
    version: 1
    community: public
modules:
  rtx810_v1:
    walk:
      - yrIfIndex # 1.3.6.1.4.1.1182.2.3.2.1.1
      - yrIfDescr # 1.3.6.1.4.1.1182.2.3.2.1.2
    max_repetitions: 25
    retries: 3
    timeout: 10s
```
```
generator$ echo $MIBDIRS
mibs
generator$ ./generator generate
ts=2024-02-09T17:17:38.548Z caller=net_snmp.go:175 level=info msg="Loading MIBs" from=mibs
ts=2024-02-09T17:17:38.723Z caller=main.go:53 level=info msg="Generating config for module" module=rtx810_v1
ts=2024-02-09T17:17:38.744Z caller=main.go:68 level=info msg="Generated metrics" module=rtx810_v1 metrics=2
ts=2024-02-09T17:17:38.744Z caller=main.go:93 level=info msg="Config written" file=/home/xxxxx/snmp_exporter/generator/snmp.yml
```
snmp.yml
```yml
# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
auths:
  rtx810_v1_auth:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 1
modules:
  rtx810_v1:
    walk:
    - 1.3.6.1.4.1.1182.2.3.2.1.1
    - 1.3.6.1.4.1.1182.2.3.2.1.2
    metrics:
    - name: yrIfIndex
      oid: 1.3.6.1.4.1.1182.2.3.2.1.1
      type: gauge
      help: A unique value for each interface - 1.3.6.1.4.1.1182.2.3.2.1.1
      indexes:
      - labelname: yrIfIndex
        type: gauge
    max_repetitions: 25
    retries: 3
    timeout: 10s

```
### What did you expect to see?
```yml
# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
auths:
  rtx810_v1_auth:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 1
modules:
  rtx810_v1:
    walk:
    - 1.3.6.1.4.1.1182.2.3.2.1.1
    - 1.3.6.1.4.1.1182.2.3.2.1.2
    metrics:
    - name: yrIfIndex
      oid: 1.3.6.1.4.1.1182.2.3.2.1.1
      type: gauge
      help: A unique value for each interface - 1.3.6.1.4.1.1182.2.3.2.1.1
      indexes:
      - labelname: yrIfIndex
        type: gauge
    - name: yrIfDescr
      oid: 1.3.6.1.4.1.25461.2.1.2.3.11.1.2
      type: DisplayString
      help: A textual string containing information about the interface - 1.3.6.1.4.1.1182.2.3.2.1.2
      indexes:
      - labelname: yrIfIndex
        type: gauge
    max_repetitions: 25
    retries: 3
    timeout: 10s
```

Metrics whose type is DisplayString are not output
