### DISCUSSION TITLE
Lookups returning empty strings when use the index lookup cdpCacheDeviceId

### DISCUSSION THREAD

**Discussion by OnionTop** [prometheus/snmp_exporter#1189] [Q&A] [answered]
### Host operating system: output of `uname -a`
`Linux zk-net01-wifi214 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### snmp_exporter version: output of `snmp_exporter -version`

```
snmp_exporter, version 0.25.0 (branch: HEAD, revision: 9c42d6c874d479314e612bca69558c81f8e26287)
  build user:       root@880115266f70
  build date:       20231210-10:05:18
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo
```

### What device/snmpwalk OID are you using?
OID:1.3.6.1.4.1.9.9.23.1.2.1
objectName:cdpCacheTable
![图片](https://github.com/prometheus/snmp_exporter/assets/83639885/da2fd28a-5a65-42eb-94a5-6939a2e87c0a)

### If this is a new device, please link to the MIB(s).
MIB file address:[cisco-mibs](https://github.com/cisco/cisco-mibs/blob/main/v2/CISCO-CDP-MIB.my)
### What did you do that produced an error?
My generator.yml content
```
auths:
  cisco_snmp:
    version: 2
    community: public
modules:
  if_mib:
    walk:
      - cdpCacheTable #1.3.6.1.4.1.9.9.23.1.2.1
    lookups:
      - source_indexes: [cdpCacheDeviceIndex]
        lookup: 1.3.6.1.4.1.9.9.23.1.2.1.1.6
```

### What did you expect to see?
I hope insert cdpCacheDeviceId in tag use cdpCacheDeviceIndex, but it's empty

```
# HELP cdpCacheDeviceId The Device-ID string as reported in the most recent CDP message - 1.3.6.1.4.1.9.9.23.1.2.1.1.6
# TYPE cdpCacheDeviceId gauge
cdpCacheDeviceId{cdpCacheDeviceId="2960-G01-1F-A-S-172.19.216.7.dpbg.lh.com",cdpCacheDeviceIndex="2",cdpCacheIfIndex="31"} 1
cdpCacheDeviceId{cdpCacheDeviceId="2960-G01-1F-A-S-172.19.218.5.dpbg.lh.com",cdpCacheDeviceIndex="1",cdpCacheIfIndex="29"} 1
cdpCacheDeviceId{cdpCacheDeviceId="3850-G01-1F-B-S-172.18.255.44.dpbg.lh.com",cdpCacheDeviceIndex="5",cdpCacheIfIndex="58"} 1
cdpCacheDeviceId{cdpCacheDeviceId="N9K-L12-2F-A-S-172.18.255.1.dpbg.lh.com(FGE2530QR15)",cdpCacheDeviceIndex="7",cdpCacheIfIndex="57"} 1
cdpCacheDeviceId{cdpCacheDeviceId="admin-N7K-K12-2F-A-S-172.18.255.252.dpbg.lh.com(JPG210300AK)",cdpCacheDeviceIndex="3",cdpCacheIfIndex="56"} 1
```

### What did you see instead?
the "cdpCacheDeviceId" is empty
```
# HELP cdpCacheDeviceId The Device-ID string as reported in the most recent CDP message - 1.3.6.1.4.1.9.9.23.1.2.1.1.6
# TYPE cdpCacheDeviceId gauge
cdpCacheDeviceId{cdpCacheDeviceId="",cdpCacheDeviceIndex="1",cdpCacheIfIndex="29"} 1
cdpCacheDeviceId{cdpCacheDeviceId="",cdpCacheDeviceIndex="2",cdpCacheIfIndex="31"} 1
cdpCacheDeviceId{cdpCacheDeviceId="",cdpCacheDeviceIndex="3",cdpCacheIfIndex="56"} 1
cdpCacheDeviceId{cdpCacheDeviceId="",cdpCacheDeviceIndex="5",cdpCacheIfIndex="58"} 1
cdpCacheDeviceId{cdpCacheDeviceId="",cdpCacheDeviceIndex="7",cdpCacheIfIndex="57"} 1
```

**Comment by SuperQ** [comment, marked as answer]
As you can see by the MIB definition:
```
cdpCacheEntry OBJECT-TYPE
    SYNTAX     CdpCacheEntry
    MAX-ACCESS not-accessible
    STATUS     current
    DESCRIPTION
            "An entry (conceptual row) in the cdpCacheTable,
            containing the information received via CDP on one
            interface from one device.  Entries appear when
            a CDP advertisement is received from a neighbor
            device.  Entries disappear when CDP is disabled
            on the interface, or globally."
    INDEX      { cdpCacheIfIndex, cdpCacheDeviceIndex }
    ::= { cdpCacheTable 1 }
```

The index is two OIDs. So the lookup must be two OIDs.

```yaml
modules:
  cdp_cache:
    walk:
      - cdpCacheTable #1.3.6.1.4.1.9.9.23.1.2.1
    lookups:
      - source_indexes: [cdpCacheIfIndex, cdpCacheDeviceIndex]
        lookup: cdpCacheDeviceId
```
