### DISCUSSION TITLE
Can't manually pull tags from OID

### DISCUSSION THREAD

**Discussion by cwesterfield** [prometheus/snmp_exporter#1196] [Q&A] [answered]
### Host operating system: output of `uname -a`
Linux
### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter, version 0.26.0 (branch: HEAD, revision: 44f8732988e726bad3f13d5779f1da7705178642)
  build user:       root@90ba0aabb239
  build date:       20240511-11:16:35
  go version:       go1.22.3
  platform:         linux/amd64
  tags:             unknown

### What device/snmpwalk OID are you using?
Room alert 3E

- 1.3.6.1.4.1.20916.1.9.1.1.1.2.0 # Metric
- 1.3.6.1.4.1.20916.1.9.1.1.1.3.0 # Device Name
- 1.3.6.1.2.1.1.5.0 # Device Type

### If this is a new device, please link to the MIB(s).
Added
[RA3E-MIB.zip](https://github.com/prometheus/snmp_exporter/files/15377097/RA3E-MIB.zip)

### What did you do that produced an error?
Attempting to manually create a config to pull a measurements with a couple of tags.

```
auths:
  public_v1:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 1
modules:
  roomalert_snmp:
    max_repetitions: 25
    retries: 3
    timeout: 10s
    get:
    - 1.3.6.1.4.1.20916.1.9.1.1.1.2.0 # Metric
    - 1.3.6.1.4.1.20916.1.9.1.1.1.3.0 # Device Name
    - 1.3.6.1.2.1.1.5.0 # Device Type
    metrics:
    - name: internal_sensor
      oid: 1.3.6.1.4.1.20916.1.9.1.1.1.2.0
      type: gauge
      help: The temperature reading in Fahrenheit of the Internal Sensor
      lookups:
      - labels:
        - name
        labelname: name
        oid: 1.3.6.1.4.1.20916.1.9.1.1.1.3.0
        type: DisplayString
      - labels:
        - type
        labelname: type
        oid: 1.3.6.1.2.1.1.5.0
        type: DisplayString
```

### What did you expect to see?
```sh
TRUNCATED FOR APPLICABLE VALUES
$ snmpwalk -v 1 -c public 172.16.0.21 1.3.6 
iso.3.6.1.2.1.1.5.0 = STRING: "hq-server-temp"
iso.3.6.1.4.1.20916.1.9.1.1.1.2.0 = INTEGER: 7766
iso.3.6.1.4.1.20916.1.9.1.1.1.3.0 = STRING: "Rack Sensor"
```

```
# HELP internal_sensor The temperature reading in Fahrenheit of the Internal Sensor
# TYPE internal_sensor gauge
internal_sensor{name="Rack Sensor",type="hq-server-temp"} 7766
```

### What did you see instead?
```
# HELP internal_sensor The temperature reading in Fahrenheit of the Internal Sensor
# TYPE internal_sensor gauge
internal_sensor{name="",type=""} 7766
```

The tags do not come across, so I feel like I'm doing it wrong, but I'm not able to find a good example of single OID pulls.
Is this not possible, or am I just doing it wrong?

**Comment by SuperQ** [comment]
You are specifying an index in your lookup labels. It's trying to find that label index on the metric. Since your metric has no index there's nothing to match.

I haven't tried this, but maybe it would work with no lookup index?

```
modules:
  roomalert_snmp:
    get:
    - 1.3.6.1.4.1.20916.1.9.1.1.1.2.0 # Metric
    - 1.3.6.1.4.1.20916.1.9.1.1.1.3.0 # Device Name
    - 1.3.6.1.2.1.1.5.0 # Device Type
    metrics:
    - name: internal_sensor
      oid: 1.3.6.1.4.1.20916.1.9.1.1.1.2.0
      type: gauge
      help: The temperature reading in Fahrenheit of the Internal Sensor
      lookups:
      - labels: []
        labelname: name
        oid: 1.3.6.1.4.1.20916.1.9.1.1.1.3.0
        type: DisplayString
      - labels: []
        labelname: type
        oid: 1.3.6.1.2.1.1.5.0
        type: DisplayString
```

**Comment by cwesterfield** [comment]
Thanks for the guidance. I just need to figure out the exact syntax to make them tags. I took your example and got no tags, so I tried to specify a tag for one of them (even though it has nothing to replace). Still no dice.

```yaml
auths:
  public_v1:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 1
modules:
  if_mib:
    max_repetitions: 25
    retries: 3
    timeout: 10s
    get:
    - 1.3.6.1.4.1.20916.1.9.1.1.1.2.0 # Metric
    - 1.3.6.1.4.1.20916.1.9.1.1.1.3.0 # Sensor Name
    - 1.3.6.1.2.1.1.5.0 # Device Name
    metrics:
    - name: internal_sensor
      oid: 1.3.6.1.4.1.20916.1.9.1.1.1.2.0
      type: gauge
      help: The temperature reading in Fahrenheit of the Internal Sensor
      lookups:
      - labels: [type]
        labelname: type
        oid: 1.3.6.1.4.1.20916.1.9.1.1.1.3.0
        type: DisplayString
      - labels: []
        labelname: device_name
        oid: 1.3.6.1.2.1.1.5.0
        type: DisplayString
```

You can see the top one actually has the label, but no value. The bottom one doesn't even show up.

```
# HELP internal_sensor The temperature reading in Fahrenheit of the Internal Sensor
# TYPE internal_sensor gauge
internal_sensor{type=""} 7811
```
