### DISCUSSION TITLE
Connecting snmp-exporter prometheus to cisco switches

### DISCUSSION THREAD

**Discussion by alemsas** [prometheus/snmp_exporter#1204] [Q&A]
I have a question about snmp exporter Prometheus, my problem is with this configuration

```
version: '3'

networks:
  monitoring:
    external: true

volumes:
  prometheus-data:

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:9091'

    restart: unless-stopped
    network_mode: host

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    command:
     - '--config.expand-environment-variables'
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
    restart: unless-stopped
    network_mode: host
```
here is my prometheus.yml
```
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.31.0.148:9091"]

  - job_name: snmp
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 172.31.0.40:161
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116

  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['localhost:9116']
```
I get this error
server returned HTTP status 400 Bad Request
I added this item in snmp.yml
```
head snmp.yml
# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
auths:
  public_v2:
    community: sasan
    version: 2
modules:
  apcups:
    walk:
    - 1.3.6.1.4.1.318.1.1.1.12
    - 1.3.6.1.4.1.318.1.1.1.2
...
```

The destination is a Cisco switch, and the snmpwalk machine is OK, and also snmp for Zabex is working at the same time, from this machine to the destination I said.
source: 172.31.0.148
destination: 172.31.0.40
I don't have any network or firewall problems.
