### DISCUSSION TITLE
inetAddress and Juniper (qfx) jnxBgpM2 tree

### DISCUSSION THREAD

**Discussion by plarivee** [prometheus/snmp_exporter#1210] [Q&A] [answered]
Hello,

I want to make sure I understand correctly the implementation of inetAddress that has been done in 
https://github.com/prometheus/snmp_exporter/pull/330

```
/snmp_exporter --version
snmp_exporter, version 0.26.0 (branch: HEAD, revision: 44f8732988e726bad3f13d5779f1da7705178642)
  build user:       root@90ba0aabb239
  build date:       20240511-11:16:35
  go version:       go1.22.3
  platform:         linux/amd64
  tags:             unknown
```

```
Using the generator from the main branch
```

I want to use the `https://apps.juniper.net/mib-explorer/getMibFile/Junos-OS/23.1R1/mib-jnx-bgpmib2.txt`  to get more detailed bgp peering information that is not in the bgp4 oid.

** I'd like to preface that this mib is marked experimental and that could be the reason for all the issues. Hence why I am just looking for a second look by people that know more about the core of snmp_exporter and the implemented inetAddress

The `snmp.yml``config generated and the generator config used: ( reduce for clarity, only walking 1 oid, but issue still the same for the full walk of mib )

```
modules:
  juniperbgp:
    walk:
    - 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.14
    metrics:
    - name: jnxBgpM2PeerIndex
      oid: 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.14
      type: gauge
      help: This value is a unique index for the remote peer entry in the jnxBgpM2PeerTable
        - 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.14
      indexes:
      - labelname: jnxBgpM2PeerRoutingInstance
        type: gauge
      - labelname: jnxBgpM2PeerLocalAddr
        type: InetAddress
      - labelname: jnxBgpM2PeerRemoteAddr
        type: InetAddress
```

```
---
auths:
 pubstw:
    community:  [redacted]
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 2
modules:
  juniperbgp:
    walk: [jnxBgpM2PeerIndex]

```

Juniper uses these indexes

Indexes:
jnxBgpM2PeerRoutingInstance
jnxBgpM2PeerLocalAddrType
jnxBgpM2PeerLocalAddr
jnxBgpM2PeerRemoteAddrType
jnxBgpM2PeerRemoteAddr

And from what I understood of https://github.com/prometheus/snmp_exporter/pull/330  is that the snmp_exporter is taking care of the AddrType , hence why it did not add it to the indexes in generated file.

Here  is my result that I am trying to get a second look on:

Exemple of a PeerIndex info walk  (ip values changed )

```
jnxBgpM2PeerIndex.0.1.10.10.10.122.1.10.10.10.121 = 23
[...]
```

The returned metrics from the exporter have shifted the values for the LocalAddr, the RemoteAddr is correct ( it's a hex value padded with lots of 0, that's something else to see if that can be returned another way) 

Example for  `jnxBgpM2PeerIndex.0.1.10.10.10.122.1.10.10.10.121 = 23` , the metrics returned
```
jnxBgpM2PeerIndex{jnxBgpM2PeerLocalAddr="10.10.122.1",jnxBgpM2PeerRemoteAddr="0x0A0A0A79000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",jnxBgpM2PeerRoutingInstance="0"} 23
```

In the indexes oid

jnxBgpM2PeerLocalAddr.0.1.10.10.10.122.1.10.10.10.121 = 0A 0A 0A 7A
jnxBgpM2PeerRemoteAddr.0.1.10.10.10.122.1.10.10.10.121 = 0A 0A 0A 79

So `10.10.10.122` (jnxBgpM2PeerLocalAddr)  was shifted to `10.10.122.1`  , taking the `1` from the addrType of the `PeerRemoteAddr` value. So did it ignore the first addrType after the routinginstance value (`0`)

Also changing `remoteAddr` to be in hex? ( I know it's return as an Hex value, but so is LocalAddr and it's in "decimal" form )

I have tried adding the addrType manually in the indexes but was even worse results.

Thank you in advance for any insights .

**Comment by dkaias** [comment, marked as answer]
I have run into the same issue, it is due to the device breaking RFC specs and not sending a size along with the address (which i found from [this issue](https://github.com/prometheus/snmp_exporter/issues/586)). To fix you need to override the address types to  `InetAddressMissingSize` like this:

```
modules:
  juniperbgp:
    walk: [jnxBgpM2PeerIndex]
    overrides:
      jnxBgpM2PeerLocalAddr:
        type: InetAddressMissingSize
      jnxBgpM2PeerRemoteAddr:
        type: InetAddressMissingSize
```
