### DISCUSSION TITLE
How do i do a lookups matching a value, not an index

### DISCUSSION THREAD

**Discussion by dkaias** [prometheus/snmp_exporter#1226] [Q&A]
I am trying to gather counts of BGP prefixes sent to each peer from a Juniper router, There is a SNMP metric for this: `jnxBgpM2PrefixOutPrefixes`, however this indexes on this do not have the local and remote peer addresses, it instead has a index number called `jnxBgpM2PeerIndex`. `jnxBgpM2PeerIndex` confusingly is not an index for other helpful metrics like `jnxBgpM2PeerRemoteAddr`, so i don't think i can get that value using lookups.

Basically i have this in `genreator.yml`:
```
modules:
  juniper_bgp_prefixes:
      walk:
        - jnxBgpM2PrefixOutPrefixes
        - jnxBgpM2PeerIndex
      overrides:
        jnxBgpM2PeerLocalAddr:
          type: InetAddressMissingSize
        jnxBgpM2PeerRemoteAddr:
          type: InetAddressMissingSize
```

That gives me something like this when i scrape:
```
# HELP jnxBgpM2PeerIndex This value is a unique index for the remote peer entry in the jnxBgpM2PeerTable - 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.14
# TYPE jnxBgpM2PeerIndex gauge
jnxBgpM2PeerIndex{jnxBgpM2PeerLocalAddr="39.82.154.245",jnxBgpM2PeerRemoteAddr="39.82.154.244",jnxBgpM2PeerRoutingInstance="0"} 1
jnxBgpM2PeerIndex{jnxBgpM2PeerLocalAddr="2001:1234:0000:5000:0000:0000:0000:A5DF",jnxBgpM2PeerRemoteAddr="2001:1234:0000:5000:0000:0000:0000:A5DE",jnxBgpM2PeerRoutingInstance="0"} 3
jnxBgpM2PeerIndex{jnxBgpM2PeerLocalAddr="17.37.63.87",jnxBgpM2PeerRemoteAddr="17.37.63.86",jnxBgpM2PeerRoutingInstance="0"} 0
# HELP jnxBgpM2PrefixOutPrefixes The number of prefixes for a peer that are installed in that peers Adj-Ribs-Out. - 1.3.6.1.4.1.2636.5.1.1.2.6.2.1.10
# TYPE jnxBgpM2PrefixOutPrefixes gauge
jnxBgpM2PrefixOutPrefixes{jnxBgpM2PeerIndex="0",jnxBgpM2PrefixCountersAfi="1",jnxBgpM2PrefixCountersSafi="1"} 7
jnxBgpM2PrefixOutPrefixes{jnxBgpM2PeerIndex="1",jnxBgpM2PrefixCountersAfi="1",jnxBgpM2PrefixCountersSafi="1"} 7
jnxBgpM2PrefixOutPrefixes{jnxBgpM2PeerIndex="3",jnxBgpM2PrefixCountersAfi="2",jnxBgpM2PrefixCountersSafi="1"} 4
```
How do i join these so i can have the remote address as a label on the jnxBgpM2PrefixOutPrefixes metric? `lookups` doesn't seem to work, because I need it to match the value of `jnxBgpM2PeerIndex` not an index.

**Comment by SuperQ** [comment]
I think I've run into this before. Here's what [I have in my notes](https://github.com/SuperQ/tools/tree/master/snmp_exporter/junos_bgp)

```yaml
modules:
  junos_bgp:
    walk:
      # - jnxBgpM2PeerTable
      - 1.3.6.1.4.1.2636.5.1.1.2.6.2.1.7 #jnxBgpM2PrefixInPrefixes
      - 1.3.6.1.4.1.2636.5.1.1.2.6.2.1.10 #jnxBgpM2PrefixOutPrefixes
    overrides:
      jnxBgpM2PeerLocalAddr:
        type: InetAddressMissingSize
      jnxBgpM2PeerRemoteAddr:
        type: InetAddressMissingSize
    lookups:
      - source_indexes: [ jnxBgpM2PeerIndex ]
        lookup: jnxBgpM2PeerRemoteAddr
      - source_indexes: [jnxBgpM2PeerIndex ]
        lookup: jnxBgpM2PeerRemoteAs
```

**Reply by SuperQ** [reply]
Maybe this doesn't actually work. :(

**Reply by dkaias** [reply]
Sadly not, i just tried your exact config, and got results like this:
```
jnxBgpM2PrefixOutPrefixes{jnxBgpM2PeerIndex="111",jnxBgpM2PeerRemoteAddr="",jnxBgpM2PeerRemoteAs="",jnxBgpM2PrefixCountersAfi="1",jnxBgpM2PrefixCountersSafi="1"} 34
jnxBgpM2PrefixOutPrefixes{jnxBgpM2PeerIndex="112",jnxBgpM2PeerRemoteAddr="",jnxBgpM2PeerRemoteAs="",jnxBgpM2PrefixCountersAfi="1",jnxBgpM2PrefixCountersSafi="1"} 19
jnxBgpM2PrefixOutPrefixes{jnxBgpM2PeerIndex="113",jnxBgpM2PeerRemoteAddr="",jnxBgpM2PeerRemoteAs="",jnxBgpM2PrefixCountersAfi="1",jnxBgpM2PrefixCountersSafi="1"} 34
jnxBgpM2PrefixOutPrefixes{jnxBgpM2PeerIndex="114",jnxBgpM2PeerRemoteAddr="",jnxBgpM2PeerRemoteAs="",jnxBgpM2PrefixCountersAfi="1",jnxBgpM2PrefixCountersSafi="1"} 34
```
Because `jnxBgpM2PeerRemoteAddr`/`jnxBgpM2PeerRemoteAs` don't have `jnxBgpM2PeerIndex` as an index

**Comment by dkaias** [comment]
I found a super hacky way to do this by overriding `jnxBgpM2PeerIndex` as a `DisplayString`. This causes the value to be added as a label. Unfortunately it also messes up all indexes in the prefix count metrics, (because its trying to interpret the `jnxBgpM2PeerIndex` index as a string). I got around this by just having two separate modules:

```
modules:
  juniper_bgp_prefixes:
    walk:
      - jnxBgpM2PrefixInPrefixes
      - jnxBgpM2PrefixOutPrefixes
  
  juniper_bgp_peers:
    walk:
       - jnxBgpM2PeerIndex
    overrides:
      jnxBgpM2PeerLocalAddr:
        type: InetAddressMissingSize
      jnxBgpM2PeerRemoteAddr:
        type: InetAddressMissingSize
      jnxBgpM2PeerIndex:
        type: DisplayString
```
This way all the metrics have `jnxBgpM2PeerIndex` as a label and i can join them together in prometheus using a recording rule. Would like to know if there is a cleaner way to do this though.
