### DISCUSSION TITLE
error walking target / HTTP 500

### DISCUSSION THREAD

**Discussion by canadabri** [prometheus/snmp_exporter#1280] [Q&A]
My offline environment has Prometheus v3.0.0 and snmp_exporter 0.26.0 running.

I have an Isilon NAS that I would like to monitor.  The Isilon admin interface lets me download the MIB file directly from the NAS.  I have copied that MIB file to my staging computer (has internet), and have generated a new snmp.yml file.  Specifically, I followed an example [found here](https://blog.devgenius.io/isilon-metrics-through-snmp-4be309e82cbc)

In my generator.yml file at the top, I added an auth that has the community name that is configured on the Isilon.  I use the same syntax as the public_v2, but I call it isilon_v2 and specify the community name.

And at the very bottom, I added this:
```
isilon:
    walk:
      - 1.3.6.1.4.1.12124.1 # cluster
      - 1.3.6.1.4.1.12124.1.2 # clusterPerformance
      - 1.3.6.1.4.1.12124.1.3 # ifsFilesystem
      - 1.3.6.1.4.1.12124.1.5 # licenses
      - 1.3.6.1.4.1.12124.2 # node
```

The isilon mib file is copied to the mibs folder.  Then I generated the new snmp.yml file, and from what I can see, it all looks good.

If I use the SNMP exporter web page (port 9116 of my Prometheus server), and I use the FQDN of my Isilon, auth is isilon_v2, and stick with the default if_mib, I get the standard generic outputs.

If I do the same, but use the module `isilon`, it thinks for a bit and comes back with:
```
An error has occurred while serving metrics:

error collecting metric Desc(fqName: "snmp_error", help: "Error scraping target", constLabels: {module="isilon"}, variableLabels: {}}: error walking target <IP ADDRESS>: request timeout (after 3 retries)
```

From the shell of the Prometheus server, I can do snmpwalk, snmpbulkwalk, snmpbulkget without errors, and it returns a lot of data.

I have also added a job to my Prometheus server to try to grab the metrics.  This job returns a 500 error on the Prometheus web page (Target Health).
``` Error scraping target: server returned HTTP status 500 Internal Server Error ```

```
  - job_name: "isilon_snmp"
    scrape_interval: 1000s
    scrape_timeout: 900s
    static_configs:
      - targets: 
        - my-isilon-ip-address # I have tried both IP and fqdn
    metrics_path: /snmp
    params:
      auth: [isilon_v2]
      module: [isilon]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116


  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['localhost:9116']
```

Because the if_mib seems to return some info, but the isilon module fails, I am thinking there may be something that did not generate properly when generating the snmp.yml.  I just don't know enough about MIBs to say what that might be, but the syntax compared to other modules does look correct.
