### DISCUSSION TITLE
resolve nested index and enrich the metrics from another module/mib

### DISCUSSION THREAD

**Discussion by CheapVibe** [prometheus/snmp_exporter#1294] [Q&A]
Hi, I'm looking for a way to perform a resolve of index of specific MIB from another MIB.
pretty sure I'm missing something basics here and would appreciate your help

the example here is [aristaQueueMIB ](https://mibs.observium.org/mib/ARISTA-SW-IP-FORWARDING-MIB/)has nested index of [ifIndex](https://mibs.observium.org/mib/IF-MIB/).
here's generator.yml configuration:

```
  arista_sw:
    walk:
      - 1.3.6.1.4.1.30065.3.6   # aristaQueueMIB new walk for this example
```
MIBs loaded successfully
example metric once polling the arista switch with arista_sw module:
```
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="0"} 2914
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="1"} 7.243897114474e+12
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="2"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="3"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="4"} 1.21428322508e+11
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="5"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="6"} 1.33255203e+08
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="7"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="33",aristaEgressPacketType="0",aristaEgressQueueIndex="8"} 384644
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="0"} 10963
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="1"} 6.860550655369e+12
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="2"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="3"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="4"} 2.05923579e+08
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="5"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="6"} 2.46362671e+08
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="7"} 0
aristaEgressQueuePkts{aristaEgressIfIndex="34",aristaEgressPacketType="0",aristaEgressQueueIndex="8"} 384644
```

the aristaEgressIfIndex value represented by the well known if_mib module, here's output:
```
ifAdminStatus{ifAlias="to_net1",ifDescr="Ethernet33",ifIndex="33",ifName="Ethernet33"} 1
ifAdminStatus{ifAlias="to_net2",ifDescr="Ethernet34",ifIndex="34",ifName="Ethernet34"} 1
```

what i'm looking for is to resolve the ifAlias into the entire aristaQueueMIB metrics to loo like this as an truncated example:
```
aristaEgressQueuePkts{aristaEgressIfIndex="Ethernet33",aristaEgressPacketType="0",aristaEgressQueueIndex="0"} 2914
aristaEgressQueuePkts{aristaEgressIfIndex="Ethernet34",aristaEgressPacketType="0",aristaEgressQueueIndex="0"} 10963
```
or further more to enrich more labels to metrics with ifAlias:
```
aristaEgressQueuePkts{aristaEgressIfIndex="Ethernet33",ifAlias="to_net1",aristaEgressPacketType="0",aristaEgressQueueIndex="0"} 2914
aristaEgressQueuePkts{aristaEgressIfIndex="Ethernet34",ifAlias="to_net2",aristaEgressPacketType="0",aristaEgressQueueIndex="0"} 10963
```

i looked at the [generator file format](https://github.com/prometheus/snmp_exporter/tree/main/generator#file-format) for ideas, but without of success.
tried few conventions and kinds of this generator config:
```
  arista_sw:
    walk:
      - 1.3.6.1.4.1.30065.3.6   # aristaQueueMIB

    lookups:
      - source_indexes: [ifIndex, aristaEgressIfIndex]
        lookup: ifAlias
```

thank you

**Comment by CheapVibe** [comment]
managed to solve this.

generator.yml config example gives the desired output with additional enrichment labels
```
  arista_sw:
    walk:
#      - 1.3.6.1.4.1.30065.3.1.1 # aristaSwFwdIp
      - 1.3.6.1.4.1.30065.3.6   # aristaQueueMIB
    lookups:
      - source_indexes: [aristaEgressIfIndex]  # From aristaQueueMIB
        lookup: ifAlias                        # Map `ifAlias` from IF-MIB
      - source_indexes: [aristaEgressIfIndex]
        lookup: ifName                         # Map `ifName` from IF-MIB
```

truncated output example:
