### DISCUSSION TITLE
Question on data from snmp-explorer/indexes

### DISCUSSION THREAD

**Discussion by felixm0311** [prometheus/snmp_exporter#1316] [Q&A]
Had a question on how to work/change the data we get from snmp-explorer.
The information I get from a specific index, the result is a digit when it should be a string. Is there a way to change this?
This is what I get from snmp-explorer.

```
# HELP arubaWiredFanName Identification of the fan for the system. - 1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4
# TYPE arubaWiredFanName gauge
arubaWiredFanName{arubaWiredFanGroupIndex="1",arubaWiredFanName="PSU-1/1/1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="101"} 1
arubaWiredFanName{arubaWiredFanGroupIndex="1",arubaWiredFanName="PSU-1/2/1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="102"} 1
arubaWiredFanName{arubaWiredFanGroupIndex="1",arubaWiredFanName="Tray-1/1/1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="1"} 1
arubaWiredFanName{arubaWiredFanGroupIndex="1",arubaWiredFanName="Tray-1/1/2",arubaWiredFanSlotIndex="2",arubaWiredFanTrayIndex="1"} 1
arubaWiredFanName{arubaWiredFanGroupIndex="1",arubaWiredFanName="Tray-1/2/1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="2"} 1
arubaWiredFanName{arubaWiredFanGroupIndex="1",arubaWiredFanName="Tray-1/2/2",arubaWiredFanSlotIndex="2",arubaWiredFanTrayIndex="2"} 1
```

When I run an snmpwalk on the OID this is what I get;

```
OID 1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4
iso.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.1.1 = STRING: "Tray-1/1/1"
iso.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.1.2 = STRING: "Tray-1/1/2"
iso.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.2.1 = STRING: "Tray-1/2/1"
iso.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.2.2 = STRING: "Tray-1/2/2"
iso.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.101.1 = STRING: "PSU-1/1/1"
iso.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.4.1.102.1 = STRING: "PSU-1/2/1"

```

Is there a way that I can get the string as a result “Tray-1/1/1” in snmp-explorer ?

Is there a way that we can add that value to a different index like `arubaWiredFanRPM` ? Would like to add `arubaWiredFanName` into `arubaWiredFanRPM` .

```
# HELP arubaWiredFanRPM Current RPM read for the fan - 1.3.6.1.4.1.47196.4.1.1.3.11.5.1.1.8
# TYPE arubaWiredFanRPM gauge
arubaWiredFanRPM{arubaWiredFanGroupIndex="1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="1"} 4121
arubaWiredFanRPM{arubaWiredFanGroupIndex="1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="101"} 4155
arubaWiredFanRPM{arubaWiredFanGroupIndex="1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="102"} 4140
arubaWiredFanRPM{arubaWiredFanGroupIndex="1",arubaWiredFanSlotIndex="1",arubaWiredFanTrayIndex="2"} 4104
arubaWiredFanRPM{arubaWiredFanGroupIndex="1",arubaWiredFanSlotIndex="2",arubaWiredFanTrayIndex="1"} 4117
arubaWiredFanRPM{arubaWiredFanGroupIndex="1",arubaWiredFanSlotIndex="2",arubaWiredFanTrayIndex="2"} 4128
```

Is there a way to add a specific index/info to a different index?
Not sure if I am using the proper terminology.

Here is my snmp-explorer config for this device. (Not sure on how to work with "lookups and overrides" this was from a sample config that was used.)

```
  aruba_mib:
    walk:
    - 1.3.6.1.2.1.31.1.1.1                # IF-MIB::ifXEntry
    - 1.3.6.1.2.1.2.2.1                   # IF-MIB::ifEntry
    - 1.3.6.1.2.1.1.3.0                   # DISMAN-EVENT-MIB::sysUpTimeInstance
    - 1.3.6.1.2.1.16.3.1                  # RMON-MIB::alarmTable
    - 1.3.6.1.2.1.16.9.1                  # RMON-MIB::eventTable
    - 1.3.6.1.2.1.16.9.2                  # RMON-MIB::logTable
    - 1.3.6.1.2.1.25                      # HOST-RESOURCES-MIB
    - 1.3.6.1.2.1.131                     # SNMPv2-SMI::mib-2.131
    - 1.3.6.1.2.1.47                      # SNMPv2-SMI::
    - 1.3.6.1.2.1.99                      # SNMPv2-SMI::mib-2.99
    - 1.3.6.1.4.1.47196.4.1.1.3.11.2.1    # ARUBAWIRED-POWERSUPPLY-MIB
    - 1.3.6.1.4.1.47196.4.1.1.3.11.4.1    # ARUBAWIRED-FANTRAY-MIB
    - 1.3.6.1.4.1.47196.4.1.1.3.11.5.1    # ARUBAWIRED-FAN-MIB
    - 1.3.6.1.4.1.47196.4.1.1.3.11.3.1    # ARUBAWIRED-TEMPSENSOR-MIB
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: ifDescr #1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: ifName #1.3.6.1.2.1.31.1.1.1.1 # ifName

    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo
```
