### DISCUSSION TITLE
Error in unmarshalResponse: error decoding value: got ipaddress len 8, expected 4 or 16

### DISCUSSION THREAD

**Discussion by v0lumehi** [prometheus/snmp_exporter#1357] [Q&A]
Hi! I have set up the snmp exporter for scraping watchguard firewalls and used the generator to generate an snmp.yml. I used the Watchguard MIBs for this. When I run the snmp exporter with this config I get the following error:
```
An error has occurred while serving metrics:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {module="watchguard"}, variableLabels: {}}: error walking target 127.0.0.1: error in unmarshalResponse: error decoding value: got ipaddress len 8, expected 4 or 16
```

I can't upload my SNMP yml because it is too large

**Comment by v0lumehi** [comment]
An snmpwalk works without problems

**Comment by SuperQ** [comment]
Please include a link to the MIBs and your generator configuration.

**Comment by v0lumehi** [comment]
This is my generator.yml:
```
auths:
  auth_v2:
    version: 2
    community: public
modules:
  # Default IF-MIB interfaces table with ifIndex.
  if_mib_if_name:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo
  watchguard:
    walk: 
      - 1.3.6.1.4.1.3097
```
Here are the watchguard MIBs: https://techsearch.watchguard.com/KB?type=Article&SFDCID=kA16S000000bzGoSAI&lang=en_US
I have stored the MIBs in a folder called "mib" as described in the doc, the generator also runs through. The error occurs when you call the scraper with the corresponding parameters
EDIT: The if_mib_if_name module works fine

**Comment by v0lumehi** [comment]
I have created a working config by process of elimination. Unfortunately, a few MIBs that I would like to have are missing. This is the working generator config:
```
auths:
  auth_v2:
    version: 2
    community: public
modules:
  # Default IF-MIB interfaces table with ifIndex.
  if_mib_if_name:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo
  watchguard:
    walk: 
      - 1.3.6.1.4.1.3097.2
      - 1.3.6.1.4.1.3097.3
      - 1.3.6.1.4.1.3097.4
      #- 1.3.6.1.4.1.3097.5.1 # broken
      #- 1.3.6.1.4.1.3097.6.1 # broken
      #- 1.3.6.1.4.1.3097.6.2 # broken
      - 1.3.6.1.4.1.3097.6.3
      # 1.3.6.1.4.1.3097.6.4 does not exist
      - 1.3.6.1.4.1.3097.6.5
      - 1.3.6.1.4.1.3097.6.6
```
What is interesting about the OID 1.3.6.1.4.1.3097.6.1, for example, is that there are no metrics that have anything to do with IP addresses, but I still get the same error when I activate this OID. Here are the metrics for this OID, generated by the generator:
```
...
    - name: wgInfoSystemCurrentTime
      oid: 1.3.6.1.4.1.3097.6.1.1
      type: DateAndTime
      help: The host's notion of the local date and time of day. - 1.3.6.1.4.1.3097.6.1.1
    - name: wgInfoGavService
      oid: 1.3.6.1.4.1.3097.6.1.3
      type: OctetString
      help: Version and update time of Gateway Antivirus Service - 1.3.6.1.4.1.3097.6.1.3
    - name: wgInfoIpsService
      oid: 1.3.6.1.4.1.3097.6.1.4
      type: OctetString
      help: Version and update time of Intrusion Prevention Service - 1.3.6.1.4.1.3097.6.1.4
    - name: wgFeaureKeyExpirationInfo
      oid: 1.3.6.1.4.1.3097.6.1.5
      type: DateAndTime
      help: The feature keys expiration day. - 1.3.6.1.4.1.3097.6.1.5
...
```
Here is also what was generated for the OID 1.3.6.1.4.1.3097.5.1, here is an IPAdress type:
```
...
    - name: wgIpsecEndpointPairNum
      oid: 1.3.6.1.4.1.3097.5.1.1.1
      type: gauge
      help: The total number of entries in the wgIpsecEndpointPairTable. - 1.3.6.1.4.1.3097.5.1.1.1
    - name: wgIpsecEndpointPairIndex
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.1
      type: gauge
      help: The running index of this IPSec endpoint pair. - 1.3.6.1.4.1.3097.5.1.1.2.1.1
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairLocalAddr
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.2
      type: InetAddressIPv4
      help: The local IP address of the current IPSec ednpoint pair. - 1.3.6.1.4.1.3097.5.1.1.2.1.2
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairPeerAddr
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.3
      type: InetAddressIPv4
      help: The remote IP address of the current IPSec endpoint pair. - 1.3.6.1.4.1.3097.5.1.1.2.1.3
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairInSAs
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.4
      type: gauge
      help: The number of inbound IPSEC SA's within this IPSec endpoint pair.If IKE
        rekeys and no data stream to activate new SA, the SA statistics may be include
        the old SA, then the total number is the double of the active SA - 1.3.6.1.4.1.3097.5.1.1.2.1.4
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOutSAs
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.5
      type: gauge
      help: The number of outbound IPSEC SA's within this IPSec endpoint pair.If IKE
        rekeys and no data stream to activate new SA, the SA statistics may be include
        the old SA, then the total number is the double of the active SA - 1.3.6.1.4.1.3097.5.1.1.2.1.5
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairInAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.6
      type: counter
      help: Total inbound traffic in Kbytes since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.6
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOutAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.7
      type: counter
      help: Total outound traffic in Kbytes since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.7
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairInPackets
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.8
      type: counter
      help: Total number of inbound packets since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.8
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOutPackets
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.9
      type: counter
      help: Total number of outound packets since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.9
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairDecryptErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.10
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.10
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairAuthErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.11
      type: counter
      help: Total number of packets discarded due to authentication error since the
        establish of this connection. - 1.3.6.1.4.1.3097.5.1.1.2.1.11
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairReplayErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.12
      type: counter
      help: Total number of packets discarded due to replay error since the establish
        of this connection. - 1.3.6.1.4.1.3097.5.1.1.2.1.12
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairPolicyErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.13
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.13
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairPadErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.14
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.14
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOtherReceiveErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.15
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.15
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairSendErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.16
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.16
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairTotalInSAs
      oid: 1.3.6.1.4.1.3097.5.1.2.1
      type: gauge
      help: The total number of active inbound SA's in the entity. - 1.3.6.1.4.1.3097.5.1.2.1
    - name: wgIpsecEndpointPairTotalOutSAs
      oid: 1.3.6.1.4.1.3097.5.1.2.2
      type: gauge
      help: The total number of active outbound SA's in the entity. - 1.3.6.1.4.1.3097.5.1.2.2
    - name: wgIpsecEndpointPairTotalInAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.2.3
      type: counter
      help: The total inbound IPsec traffic of this entity. - 1.3.6.1.4.1.3097.5.1.2.3
    - name: wgIpsecEndpointPairTotalOutAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.2.4
      type: counter
      help: The total outbound IPsec traffic of this entity. - 1.3.6.1.4.1.3097.5.1.2.4
    - name: wgIpsecEndpointPairTotalInPackets
      oid: 1.3.6.1.4.1.3097.5.1.2.5
      type: counter
      help: The total inbound IPsec packets of this entity. - 1.3.6.1.4.1.3097.5.1.2.5
    - name: wgIpsecEndpointPairTotalOutPackets
      oid: 1.3.6.1.4.1.3097.5.1.2.6
      type: counter
      help: The total outbound IPsec packets of this entity. - 1.3.6.1.4.1.3097.5.1.2.6
    - name: wgIpsecEndpointPairTotalDecryptErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.7
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.7
    - name: wgIpsecEndpointPairTotalAuthErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.8
      type: counter
      help: Total number of packets on this entity discarded due to authentication
        errors. - 1.3.6.1.4.1.3097.5.1.2.8
    - name: wgIpsecEndpointPairTotalReplayErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.9
      type: counter
      help: Total number of packets discarded due to replay errors on this entity.
        - 1.3.6.1.4.1.3097.5.1.2.9
    - name: wgIpsecEndpointPairTotalPolicyErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.10
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.10
    - name: wgIpsecEndpointPairTotalPadErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.11
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.11
    - name: wgIpsecEndpointPairTotalOtherReceiveErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.12
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.12
    - name: wgIpsecEndpointPairTotalSendErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.13
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.13
    - name: wgIpsecEndpointPairPeerIPToTunnelNum
      oid: 1.3.6.1.4.1.3097.5.1.3.1
      type: gauge
      help: The total number of tunnels in the peeriptotunnel table. - 1.3.6.1.4.1.3097.5.1.3.1
    - name: wgIpsecEndpointPairPeerIPToTunnelPeerIP
      oid: 1.3.6.1.4.1.3097.5.1.3.2.1.1
      type: InetAddressIPv4
      help: The peer ip of the peeriptotunnel table. - 1.3.6.1.4.1.3097.5.1.3.2.1.1
      indexes:
      - labelname: wgIpsecEndpointPairPeerIPToTunnelPeerIP
        type: InetAddressIPv4
      - labelname: wgIpsecEndpointPairPeerIPToTunnelTunnelID
        type: gauge
    - name: wgIpsecEndpointPairPeerIPToTunnelTunnelID
      oid: 1.3.6.1.4.1.3097.5.1.3.2.1.2
      type: gauge
      help: The tunnel id of the peeriptotunnel table. - 1.3.6.1.4.1.3097.5.1.3.2.1.2
      indexes:
      - labelname: wgIpsecEndpointPairPeerIPToTunnelPeerIP
        type: InetAddressIPv4
      - labelname: wgIpsecEndpointPairPeerIPToTunnelTunnelID
        type: gauge
 ...
```
Especially the IPSec metrics would be important for me

**Comment by v0lumehi** [comment]
By the way, I think this is an issue in the code, maybe it would be more of an issue instead of a discussion here in GitHub?

**Reply by SuperQ** [reply]
Without some packet captures and example results, it's hard to say. But so far the evidence suggests that this is a device bug. Generally when we see these issues, the data returned by the device is inconsistent with the spec of the MIB.

**Reply by v0lumehi** [reply]
Would an snmpwalk result be helpful here? And how can I do a package capture? If that would work, that would be great, I'm happy to provide test data, but I have to be careful not to send any personal data.

**Reply by SuperQ** [reply]
```
./snmp_exporter --log.level=debug --snmp.debug-packets
```

Try doing this with a single OID metric that fails to work, rather than try doing everything.

**Reply by v0lumehi** [reply]
I just ran the command for the OID "1.3.6.1.4.1.3097.5.1". What's strange is that OIDs are being walked that aren't even in the config. Why does that happen? Output:
```
time=2025-02-06T17:46:10.131Z level=DEBUG source=logger_debug.go:18 msg="parseRawField: OID" auth=auth_v3 target=<redacted> source_address="" worker=0
time=2025-02-06T17:46:10.131Z level=DEBUG source=logger_debug.go:18 msg="OID: .1.3.6.1.4.1.3097.6.2.1.2.0" auth=auth_v3 target=<redacted> source_address="" worker=0
time=2025-02-06T17:46:10.131Z level=DEBUG source=logger_debug.go:12 msg="decodeValue: type is IPAddress" auth=auth_v3 target=<redacted> source_address="" worker=0
time=2025-02-06T17:46:10.131Z level=DEBUG source=logger_debug.go:18 msg="ERROR on UnmarshalPayload on v3: error in unmarshalResponse: error decoding value: got ipaddress len 8, expected 4 or 16" auth=auth_v3 target=<redacted> source_address="" worker=0
time=2025-02-06T17:46:10.131Z level=DEBUG source=logger_debug.go:18 msg="Retry number 4. Last error was: error in unmarshalResponse: error decoding value: got ipaddress len 8, expected 4 or 16" auth=auth_v3 target=<redacted> source_address="" worker=0
time=2025-02-06T17:46:10.131Z level=DEBUG source=logger_debug.go:18 msg="SEND Error on the first Request Error: error in unmarshalResponse: error decoding value: got ipaddress len 8, expected 4 or 16" auth=auth_v3 target=<redacted> source_address="" worker=0
time=2025-02-06T17:46:10.131Z level=INFO source=collector.go:367 msg="Error scraping target" auth=auth_v3 target=<redacted> source_address="" worker=0 module=watchguard err="error walking target <redacted>: error in unmarshalResponse: error decoding value: got ipaddress len 8, expected 4 or 16"
time=2025-02-06T17:46:10.131Z level=DEBUG source=collector.go:469 msg="Finished scrape" auth=auth_v3 target=<redacted> source_address="" worker=0 module=watchguard duration_seconds=0.534330084
```
snmp.yml:
  ```
watchguard:
    walk:
    - 1.3.6.1.4.1.3097.5.1
    metrics:
    - name: wgIpsecEndpointPairNum
      oid: 1.3.6.1.4.1.3097.5.1.1.1
      type: gauge
      help: The total number of entries in the wgIpsecEndpointPairTable. - 1.3.6.1.4.1.3097.5.1.1.1
    - name: wgIpsecEndpointPairIndex
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.1
      type: gauge
      help: The running index of this IPSec endpoint pair. - 1.3.6.1.4.1.3097.5.1.1.2.1.1
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairLocalAddr
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.2
      type: InetAddressIPv4
      help: The local IP address of the current IPSec ednpoint pair. - 1.3.6.1.4.1.3097.5.1.1.2.1.2
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairPeerAddr
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.3
      type: InetAddressIPv4
      help: The remote IP address of the current IPSec endpoint pair. - 1.3.6.1.4.1.3097.5.1.1.2.1.3
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairInSAs
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.4
      type: gauge
      help: The number of inbound IPSEC SA's within this IPSec endpoint pair.If IKE
        rekeys and no data stream to activate new SA, the SA statistics may be include
        the old SA, then the total number is the double of the active SA - 1.3.6.1.4.1.3097.5.1.1.2.1.4
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOutSAs
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.5
      type: gauge
      help: The number of outbound IPSEC SA's within this IPSec endpoint pair.If IKE
        rekeys and no data stream to activate new SA, the SA statistics may be include
        the old SA, then the total number is the double of the active SA - 1.3.6.1.4.1.3097.5.1.1.2.1.5
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairInAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.6
      type: counter
      help: Total inbound traffic in Kbytes since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.6
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOutAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.7
      type: counter
      help: Total outound traffic in Kbytes since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.7
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairInPackets
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.8
      type: counter
      help: Total number of inbound packets since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.8
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOutPackets
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.9
      type: counter
      help: Total number of outound packets since the establish of this connection.
        - 1.3.6.1.4.1.3097.5.1.1.2.1.9
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairDecryptErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.10
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.10
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairAuthErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.11
      type: counter
      help: Total number of packets discarded due to authentication error since the
        establish of this connection. - 1.3.6.1.4.1.3097.5.1.1.2.1.11
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairReplayErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.12
      type: counter
      help: Total number of packets discarded due to replay error since the establish
        of this connection. - 1.3.6.1.4.1.3097.5.1.1.2.1.12
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairPolicyErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.13
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.13
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairPadErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.14
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.14
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairOtherReceiveErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.15
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.15
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairSendErrors
      oid: 1.3.6.1.4.1.3097.5.1.1.2.1.16
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.1.2.1.16
      indexes:
      - labelname: wgIpsecEndpointPairIndex
        type: gauge
    - name: wgIpsecEndpointPairTotalInSAs
      oid: 1.3.6.1.4.1.3097.5.1.2.1
      type: gauge
      help: The total number of active inbound SA's in the entity. - 1.3.6.1.4.1.3097.5.1.2.1
    - name: wgIpsecEndpointPairTotalOutSAs
      oid: 1.3.6.1.4.1.3097.5.1.2.2
      type: gauge
      help: The total number of active outbound SA's in the entity. - 1.3.6.1.4.1.3097.5.1.2.2
    - name: wgIpsecEndpointPairTotalInAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.2.3
      type: counter
      help: The total inbound IPsec traffic of this entity. - 1.3.6.1.4.1.3097.5.1.2.3
    - name: wgIpsecEndpointPairTotalOutAccKbytes
      oid: 1.3.6.1.4.1.3097.5.1.2.4
      type: counter
      help: The total outbound IPsec traffic of this entity. - 1.3.6.1.4.1.3097.5.1.2.4
    - name: wgIpsecEndpointPairTotalInPackets
      oid: 1.3.6.1.4.1.3097.5.1.2.5
      type: counter
      help: The total inbound IPsec packets of this entity. - 1.3.6.1.4.1.3097.5.1.2.5
    - name: wgIpsecEndpointPairTotalOutPackets
      oid: 1.3.6.1.4.1.3097.5.1.2.6
      type: counter
      help: The total outbound IPsec packets of this entity. - 1.3.6.1.4.1.3097.5.1.2.6
    - name: wgIpsecEndpointPairTotalDecryptErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.7
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.7
    - name: wgIpsecEndpointPairTotalAuthErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.8
      type: counter
      help: Total number of packets on this entity discarded due to authentication
        errors. - 1.3.6.1.4.1.3097.5.1.2.8
    - name: wgIpsecEndpointPairTotalReplayErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.9
      type: counter
      help: Total number of packets discarded due to replay errors on this entity.
        - 1.3.6.1.4.1.3097.5.1.2.9
    - name: wgIpsecEndpointPairTotalPolicyErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.10
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.10
    - name: wgIpsecEndpointPairTotalPadErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.11
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.11
    - name: wgIpsecEndpointPairTotalOtherReceiveErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.12
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.12
    - name: wgIpsecEndpointPairTotalSendErrors
      oid: 1.3.6.1.4.1.3097.5.1.2.13
      type: counter
      help: Deprecated, currently unused. - 1.3.6.1.4.1.3097.5.1.2.13
    - name: wgIpsecEndpointPairPeerIPToTunnelNum
      oid: 1.3.6.1.4.1.3097.5.1.3.1
      type: gauge
      help: The total number of tunnels in the peeriptotunnel table. - 1.3.6.1.4.1.3097.5.1.3.1
    - name: wgIpsecEndpointPairPeerIPToTunnelPeerIP
      oid: 1.3.6.1.4.1.3097.5.1.3.2.1.1
      type: InetAddressIPv4
      help: The peer ip of the peeriptotunnel table. - 1.3.6.1.4.1.3097.5.1.3.2.1.1
      indexes:
      - labelname: wgIpsecEndpointPairPeerIPToTunnelPeerIP
        type: InetAddressIPv4
      - labelname: wgIpsecEndpointPairPeerIPToTunnelTunnelID
        type: gauge
    - name: wgIpsecEndpointPairPeerIPToTunnelTunnelID
      oid: 1.3.6.1.4.1.3097.5.1.3.2.1.2
      type: gauge
      help: The tunnel id of the peeriptotunnel table. - 1.3.6.1.4.1.3097.5.1.3.2.1.2
      indexes:
      - labelname: wgIpsecEndpointPairPeerIPToTunnelPeerIP
        type: InetAddressIPv4
      - labelname: wgIpsecEndpointPairPeerIPToTunnelTunnelID
        type: gauge
```
