### DISCUSSION TITLE
replace 2 sources for one lookup label

### DISCUSSION THREAD

**Discussion by gouvy-hub** [prometheus/snmp_exporter#1378] [Q&A]
Hello,

First I'd like to congratulate you for this tool which is brilliant.
I have a device returns 2 label for each OID (card + port) and I want to replace this by the interface description.
How could I do that?

SNMP walk:

```
# HELP ethIfPurpose A string representing the purpose of the interface - 1.3.6.1.4.1.2928.2.2.1.3.2.1.6
# TYPE ethIfPurpose gauge
ethIfPurpose{ethDevIndex="2",ethIfIndex="1",ethIfPurpose="Description_2/1"} 1
ethIfPurpose{ethDevIndex="3",ethIfIndex="1",ethIfPurpose="Description_3/1"} 1
```

ethDevIndex is the card and ethIfIndex is the port, Purpose being the description.
My goal is to add to all metric containing ethDevIndex="2",ethIfIndex="1", the ethIfPurpose.

My generator.yml looks like this but not working:

```
    lookups:
      - source_indexes: [dtmIfIndex]
        lookup: dtmIfPurpose
      - source_indexes: [ethIfIndex, ethDevIndex ]
        lookup: ethIfPurpose
      - source_indexes: [dtmIfIndex]
        lookup: dtmIfName
      - source_indexes: [ethIfIndex, ethDevIndex ]
        lookup: ethIfName
      - source_indexes: [pmTifIndex]
        lookup: pmTifDataSourceName
    overrides:
      dtmIfIndex:
        ignore: true # Lookup metric
      ethIfIndex:
        ignore: true # Lookup metric
      ethDevIndex:
        ignore: true # Lookup metric
#      ethIfName:
#        ignore: true # Lookup metric
```
Is there anyway to make this works?

Thanks,

Steph
