### DISCUSSION TITLE
Exporting snmp.yml using multiple community

### DISCUSSION THREAD

**Discussion by lmas-chwy** [prometheus/snmp_exporter#1431] [Q&A] [answered]
In my case my snmp_exporter scan devices that have different community. With the new format how can i do that?

This is how my generator configs look now

```
  bgp_status:
    walk: 
      - bgpPeerState
      - cbgpPeerAcceptedPrefixes
    version: 2
    max_repetitions: 25
    retries: 3
    timeout: 30s
    auth:
      community: example-a

  redboxcalls:
    walk: 
      - redBoxCallsBeingRecorded
    version: 2
    max_repetitions: 25
    retries: 3
    timeout: 30s
    auth:
      community: example-b

```

**Comment by lmas-chwy** [comment, marked as answer]
found the awnser. WIth the new version of snmp_exporter once you move the auth like they mention on this page https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md. You now need to tell prometheus which auth to use by passing a parameter.

```
  - job_name: 'example job'
    scrape_interval: 60s
    scrape_timeout: 55s
    file_sd_configs:
      - files:
        - routers.json
    metrics_path: /snmp
    params:
      auth: [public_v2]    <---------------
      module: [vvb_server_stats]

```
