### DISCUSSION TITLE
generator overrides do not effect

### DISCUSSION THREAD

**Discussion by NASA1nk** [prometheus/snmp_exporter#1443] [Q&A]
generator.yml
```
oss:
    walk:
      - 1.3.6.1.4.1.2014.1.1 # ism
      
    overrides:
      cpuUtilization:
        type: DisplayString
        regex_extracts:
          '':
          - regex: '(.*)'
            value: '$1'

      cpuMaxUtilization:
        type: DisplayString
        regex_extracts:
          Temp:
          - regex: '([0-9.]+)'
            value: '$1'

      cpuTempName:
        type: DisplayString
      memCapacity:
        type: DisplayString
```
I override above metric because default type is OctetString，but some of them do not effect，eg：diskCapacity，is still OctetString，
```
# HELP cpuMaxUtilization The max utilization of CPUs in the cloud. - 1.3.6.1.4.1.2014.1.1.2.2
# TYPE cpuMaxUtilization gauge
cpuMaxUtilization{cpuMaxUtilization="1.3%"} 1
# HELP cpuUtilization The average utilization of CPUs in the cloud. - 1.3.6.1.4.1.2014.1.1.2.1
# TYPE cpuUtilization gauge
cpuUtilization{cpuUtilization="1.2%"} 1
# HELP diskCapacity The total disk capacity of the cloud. - 1.3.6.1.4.1.2014.1.1.14.1
# TYPE diskCapacity gauge
diskCapacity{diskCapacity="0x332E3335205042"} 1
# HELP diskIdle The idle disk capacity of the cloud. - 1.3.6.1.4.1.2014.1.1.14.2
# TYPE diskIdle gauge
diskIdle{diskIdle="3.35 PB"} 1
# HELP diskIp The node IP in the cloud. - 1.3.6.1.4.1.2014.1.1.14.3.1.1
```
another problem is regex_extracts（regex），eg：cpu value is 1.2% diskIdle is 3.35 PB ,I want 1.2 and 3.35，so I write regex: '([0-9.]+)' and generate snmp.yml ，then I found the regex was changed，and I can not get the metric，I thought regex is wrong and exporter do not collect this metric
```
  oss:
    walk:
    - 1.3.6.1.4.1.2014.1.1
    metrics:
    - name: cpuUtilization
      oid: 1.3.6.1.4.1.2014.1.1.2.1
      type: DisplayString
      help: The average utilization of CPUs in the cloud. - 1.3.6.1.4.1.2014.1.1.2.1
      regex_extracts:
        "":
        - value: $1
          regex: ^(?:(.*))$
    - name: cpuMaxUtilization
      oid: 1.3.6.1.4.1.2014.1.1.2.2
      type: DisplayString
      help: The max utilization of CPUs in the cloud. - 1.3.6.1.4.1.2014.1.1.2.2
      regex_extracts:
        Temp:
        - value: $1
          regex: ^(?:([0-9.]+))$
```
