### DISCUSSION TITLE
generator: change metric type

### DISCUSSION THREAD

**Discussion by MVKozlov** [prometheus/snmp_exporter#892] [Q&A]
I have MIB and try to make my own table with generator

_snmpbulkwalk_ return `iso.3.6.1.4.1.12345.1.1.7.1.26.5 = STRING: "351"`
and I want to get INTEGER

I try to change metric type to gauge
```
overrides:
  metric:
     type: gauge
```
but it just set metric to **0**

Now I have wortkaround
```
overrides:
  metric:
    regex_extracts:
       '':
         - regex: '(.*)'
           value: '$1'
```
Why `type: gauge` doesn't work ? maybe I misunderstood its usage?
