### DISCUSSION TITLE
URL structure different from webinterface and prometheus link

### DISCUSSION THREAD

**Discussion by LudwigDevOps** [prometheus/snmp_exporter#913] [Q&A]
Hello Guys,

i have a simmular problem with this.
i have prometheus and snmp_exporter on the same machine (no docker, just debian OS)
prometheus runs on 9090 and snmp_exporter on 9116

in the prometheus config file i have declated my targets:

```
  - job_name: snmp
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 192.168.130.246 #HP ProCurve 4204
        - 192.168.130.252 #HP 2530
        - 192.168.130.249 #Aruba 6100
        - 192.168.130.250 #Dell PowerEdge 2824
        - 192.166.130.1   #Firewall 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: myserver.domain.com:9116 # URL as shown on the UI
```
the other switches are running and everything is fine.
i collect the data and display my traffic with grafana.

but the firewall one is a little bit bitchy.
the snmp config on the firewall should be fine snmp v2c and public as the com.string.

on the webinterface from the snmp_exporter the firewall(called devices) gives back his information instant.
webinterface runs with this URL:

http://myserver.domain.com:9116/snmp?target=192.168.130.1&module=if_mib

fine.. i got my ifOutOctets

on the prometheus webinterface on targets.. i got the error 500 and if i click on the link i get
error getting target 192.166.130.1: request timeout (after 3 retries)

i look in the URL and its this one:

http://myserver.domain.com:9116/snmp?module=if_mib&target=192.166.130.1

so just the structure of the URL is changed.. and then error 500 on prometheus and timeout????

can you guys say me something about this. why the URL stucture changes and why it workes with just this constellation..
it makes no sense to me.

br

Ludwig

btw: i use this version

```
 snmp_exporter --version
snmp_exporter, version 0.22.0 (branch: HEAD, revision: 7b0657fd99862a47f2f9f780f08a794ca7040ae7)
  build user:       root@cfac3556bd96
  build date:       20230615-13:29:47
  go version:       go1.20.5
  platform:         linux/amd64
  tags:             netgo
```
