### DISCUSSION TITLE
Regex to remove whitespace at the end of DisplayString metrics

### DISCUSSION THREAD

**Discussion by jp-moller** [prometheus/snmp_exporter#933] [Q&A]
I have a vendor that has a variable amount of whitespace at the end of all metrics that are of type DisplayString:

```
solarChargersCurrentDescription{solarChargersCurrentDescription="Solar current   "} 1
batteryTimeLeftDescription{batteryTimeLeftDescription="BatteryTimeLeft "} 1
batteryTemperaturesDescription{batteryTemperaturesDescription="BatteryTemp     "} 1
```

Is there a way for me to rewrite these to remove any trailing whitespace? I don't think the `regex_extracts` method works, as that converts the extracted group to a float64, which doesn't work for strings that are meant to stay as strings.

Any ideas?

**Comment by SuperQ** [comment]
I had an idea to provide an equivalent to `metric_relabel_configs` directly in the exporter. But for now you would need to do this in Prometheus.

Something like this:

```yaml
metric_relabel_configs:
- source_labels:
  - solarChargersCurrentDescription
  regex: "(.+[a-z])\\s*"
  target_label: solarChargersCurrentDescription
```
