### DISCUSSION TITLE
Docker updated

### DISCUSSION THREAD

**Discussion by sahara101** [prometheus/snmp_exporter#948] [Q&A]
Hello, my docker got updated and snmp is no longer working. Unfortunately I do not understand what I have to change for the new version. 

### Host operating system: output of `uname -a`

Linux nas 4.4.302+ #64570 SMP Thu Jul 20 00:06:39 CST 2023 x86_64 GNU/Linux synology_v1000_rs1221+

### snmp_exporter version: output of `snmp_exporter -version`
0.23.0 docker

### What did you do that produced an error?

docker automatically updated to newest version

### What did you expect to see?

working connection to prometheus

### What did you see instead?

`porter" version="(version=0.23.0, branch=HEAD, revision=20657d2f486a1ac237238827beed97fa67eb8611)"
ts=2023-08-16T11:47:38.980Z caller=main.go:181 level=info build_context="(go=go1.20.7, platform=linux/amd64, user=root@f2310b8dd92c, date=20230816-09:56:45, tags=netgo)"
ts=2023-08-16T11:47:38.984Z caller=main.go:188 level=error msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 1: field synology not found in type config.Config"
ts=2023-08-16T11:47:38.984Z caller=main.go:189 level=error msg="Possible old config file, see https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md"`

Here is the config:

https://pastebin.com/1DzCbz8d

**Comment by logopk** [comment]
Same issue with qnap mibs and exporter.yml

**Comment by servak** [comment]
You need to change the format of your config file.
For example like this
```
auths:
  public_v3:
    version: 3
    security_level: authPriv
    auth_protocol: MD5
    username: snmp-exporter
    password: password
    priv_protocol: DES
    priv_password: password

modules:
  synology:
    walk:
    - 1.3.6.1.2.1.2             # network
    - 1.3.6.1.2.1.31.1.1        # The total number received/transmitted of the interface
    - 1.3.6.1.4.1.6574.1        # displays all system statuses
    - 1.3.6.1.4.1.6574.2        # information regarding hard drives e.g Temperature
    - 1.3.6.1.4.1.6574.3        # monitoring RAID status
    - 1.3.6.1.4.1.6574.6        # the number of users logging in
    metrics:
    - name: ifNumber
      oid: 1.3.6.1.2.1.2.1
      type: gauge
```

> BREAKING CHANGES:
> This version of the exporter introduces a new configuration file format. This new format separates the walk and metric mappings from the connection and authentication settings. This allows for easier configuration of different auth params without having to duplicate the full walk and metric mapping.
