### DISCUSSION TITLE
error parsing snmp.yml config - yaml: unmarshal errors:\n line3 field public_v2 not found in type config.plain

### DISCUSSION THREAD

**Discussion by BradTran** [prometheus/snmp_exporter#964] [Q&A] [answered]
Hello! I am trying to set up snmp_exporter for the first time and I used the generator and this was the snmp.yml that was created but I am getting the following error when trying to start the snmp_exporter.service and have not been able to find a solution - can someone help!? Many Thanks!

This is the error I am getting when running the systemctl status snmp_exporter.service
` snmp_exporter[20044]: ts=2023-08-22T18:50:33.516Z caller=main.go:166 level=error msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 3: field public_v2 not found in type config.plain\n  line 11: field public_v3 not found in type config.plain\n  line 20: field if-mib not found in type config.plain"`

I've attached a copy of the yaml file in case someone can take a look to see what I am missing or have incorrectly configured? 
[snmp.yml.txt](https://github.com/prometheus/snmp_exporter/files/12412158/snmp.yml.txt)

**Comment by SuperQ** [comment, marked as answer]
That config file requires the snmp_exporter version v0.23.0 or newer. You probably have an old version installed.

**Comment by seal61** [comment]
For anyone coming along here upgrading their exporters and just want to change the snmp.yml config file without running the generator again, you can do the following:

1. Check `/var/log/syslog` for a more detailed output of that is wrong
2. Check if your `snmp.yml` config file contains any version information like `version: 1`, if yes, remove (or at least uncomment them for now) them.
3. Move the whole content of the file 2 spaces to the right (do so e.g. in sublime-text editor or vim - as you prefer) to not break the yml format in the next step
4. Add the version / auth part + the modules line to this file like
```
auths:
  public_v2:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 2
modules:
```
if it fits you, depending on your setup it could be that you still need to adapt this, possible also to add version 1:
```
auths:
  public_v1:
    version: 1
  public_v2:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 2
modules: 
```
We went with the second option as we had some `version: 1` in our generator.yml file. 

5. Also you want to add the auth version like `auth: [public_v1]` to your prometheus.yaml where you include the snmp exporter target(s).

```
    params:
      module: [YOURMODULENAME]
      auth: [public_v1]
```

Otherwise you might see errors like `Unknown auth 'public_v2'` while testing your exporter output. Testing can be done like `http://SERVERIP-WHERE-EXPORTER-RUNS:9116/snmp?target=SNMP-TARGET-IP&module=YOURMODULENAME&auth=public_v1` - if you are still getting the same error, also specify the auth version in the query like  `http://SERVERIP-WHERE-EXPORTER-RUNS:9116/snmp?target=SNMP-TARGET-IP&module=YOURMODULENAME&auth=public_v1`.

Maybe this helps someone out there - if yes, feel free to leave a comment or upvote :)

**Reply by kalid-kto** [reply]
Hello,
I read your response and I have some doubts that may be related to this...
with version 0.22.0 of the snmp-exporter, my snmp.yml had a configuration that I used for two devices, the prometheus.yaml was configured as follows:
```
- job_name: snmp-exporter
  static_configs:
    - targets:
      - ip.ip.ip.001  # UPS EATON
      - ip.ip.ip.002  # UPS POWER-ALL
  metrics_path: /snmp
  params:
    module: [ups]    
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter:9116
```
with the update of the snmp-exporter, if we do what you suggest, both use public_v1

>     params:
>       module: [YOURMODULENAME]
>       auth: [public_v1]
> 

 how do I define that the Eaton UPS uses public_v1 and the Power-all public_v2? Will I have to create two jobs, one for each device, with the same `module: [YOURMODULENAME]` ?
