### DISCUSSION TITLE
New generator.yml breaks auth when multiple communities are used (i.e Meraki Dashboard)

### DISCUSSION THREAD

**Discussion by R2NetD2** [prometheus/snmp_exporter#966] [Q&A] [answered]
v0.23.0 - Auth Split Migration is non-compatible with platforms such as Meraki that auto-generate a community for scraping their config. 

Since rollout of v0.23.0 there's no choice to create a sub-auth option for a specific module (Meraki Dashboard in my case).

### What device/snmpwalk OID are you using?
MERAKI-CLOUD-CONTROLLER-MIB

### If this is a new device, please link to the MIB(s).
Only accesible to Meraki customers

### What did you do that produced an error?
Have a split Auth for the module MERAKI-CLOUD-CONTROLLER-MIB

### What did you expect to see?
A successfully generated config

### What did you see instead?
```
ts=2023-08-23T10:15:06.175Z caller=main.go:132 level=error msg="Error generating config netsnmp" err="error parsing yml config: yaml: unmarshal errors:\n  line 3: cannot unmarshal !!str ###### into config.plain\n  line 4: cannot unmarshal !!int ##### into config.plain\n  line 36: field auth not found in type main.plain"
``` 

PS: I appreciate the `unmarshal` errors are not related to this issue.

**Comment by SuperQ** [comment]
There never was a "sub-auth option", this statement doesn't make sense. Previously there were only modules.

It would be helpful if you shared your existing `generator.yml`, otherwise we're all left guessing what you're talking about.

**Reply by R2NetD2** [reply]
Hey @SuperQ, thanks for your quick reply. I meant that there was an auth section per module... After removing that possibility, I can't have different auth parameters for different modules. Here is an example of a `generator.yml`:


```
auths:
  generic_auth:
    community: COMMUNITY_STRING
    version: 2

modules:
  FORTINET_FORTIGATE_MIB:
    walk:
      - fgSysUpTime
      - fgSysVersion
      - fgSysCpuUsage
      - fgSysMemUsage
      - fgSysDiskUsage
      - fgSysSesCount
      - fgHwSensors
      - fgHaStatsSerial
      - fgHaStatsSyncStatus
      - fgProcessorUsage

    max_repetitions: 25
    retries: 3

  MERAKI-CLOUD-CONTROLLER-MIB:
    walk:
      - networkTable
      - devClientCount
      - devMac
      - devName
      - devNetworkName
      - devStatus

    max_repetitions: 25
    retries: 3
    version: 2
    auth:
      community: "AUTOMATICALLY_GENERATED_BY_MERAKI"

``` 

Thx!
