### DISCUSSION TITLE
Decrease metric or label value with generator config?

### DISCUSSION THREAD

**Discussion by bull-daniel-paprocki** [prometheus/snmp_exporter#995] [Q&A]
I'm scraping Brocade switches and I've encountered an issue with port numbering. Metric containing all ports - swFCPortIndex - returns higher value than on switch side - as port_index + 1, e.g. switch's port 0 is scraped as port 1. In MIB I saw below explanation:

```
swFCPortIndex - "This object identifies the switch port index.
		Note that the value of a port index is 1 higher than the
		port number labeled on the front panel.
		E.g. port index 1 correspond to port number 0."
```

It is very problematic as metric swFCPortIndex value is used as label on all other metrics that are related with any port metrics. Below example describes metrics of physical port 0:

```
brocade_swFCPortIndex{data_center="x", instance="y", swFCPortIndex="1"} = 1

brocade_swFCPortRxLCs{data_center="x", instance="y", swFCPortIndex="1"}
```

I've already tried relabeling on Prometheus level however I failed as each label is kept as string, so no arithmetical operation are possible. I also tried to record new metric with correct port value, however I couldn't use it to create new label. 

Is there a way to fix port indexing on snmp_exporter level, for instance via generator config?

**Comment by SuperQ** [comment]
Does `swFCPortName` or `swFCPortSpecifier` map to the names you want? You want to setup a lookup, similar to how `ifDescr` and `ifName` are handled in `IF-MIB`.

```yaml
modules:
  brocade_sw_mib:
    walk:
      - swFCPortTable
    lookups:
      - source_indexes: [swFCPortIndex]
        lookup: swFCPortName
      - source_indexes: [swFCPortIndex]
        lookup: swFCPortSpecifier
```

**Reply by bull-daniel-paprocki** [reply]
I've tried this approach with small modification:

```
modules
  brocade_sw_mib:
    walk:
      - swFCPortTable
    lookups:
      - source_indexes: [swFCPortEntry]
        lookup: swFCPortName # 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.36
      - source_indexes: [swFCPortEntry]
        lookup: swFCPortSpecifier # 1.3.6.1.4.1.1588.2.1.1.1.6.2.1.37
```

As swFCPortEntry is a parent object for above, and swFCPortIndex generator was failing. With that kind of config generator created configuration successfully however all timeseries corresponding to any port data were gone, metrics were completely empty.
