### ISSUE TITLE
Generator max_repetitions is only unit8

### ISSUE THREAD

**Issue by p-krupl** [prometheus/snmp_exporter#1004]
Im running on 
FreeBSD 13.2-RELEASE-p3 FreeBSD 13.2-RELEASE-p3 GENERIC amd64
Snmp_exporter version 2.43.0.

The given generator.yml
```
modules:
  cmts_harmonic_ofdma_cm:
    version: 2
    retries: 2
    max_repetitions: 256
    auth:
      community: public
    walk:
      - hrmCmtsCmOfdmaMerCurrent
    lookups:
      - source_indexes: [ ifIndex ]
        lookup: ifName
        drop_source_indexes: true
```
Gives the following error message when running "snmp_exporter_generator generate":
```
level=error ts=2023-09-19T17:21:48.973Z caller=main.go:130 msg="Error generating config netsnmp" err="error parsing yml config: yaml: unmarshal errors:\n  line 5: cannot unmarshal !!int `256` into uint8"
```
In snmp max_repetitions can be more than 255, in the getBulkRequest the max-repetitions seems to be variable length encoded so i'm not sure what the upper limit for max_repetitions is for snmp.

Snmp is sadly still the king of the Cable world. :(
The vendor even had a prometheus metrics endpoint directly integrated in the product, but sadly removed in later releases.
