### ISSUE TITLE
Indices filters does not support names, only oids

### ISSUE THREAD

**Issue by JDA88** [prometheus/snmp_exporter#1005]
### Host operating system: output of `uname -a`
Windows 2019

### snmp_exporter version: output of `snmp_exporter -version`
0.24.1

### What did you do that produced an error?
The filter bellow des not work:
```
    filters:
      dynamic: 
        - oid: 1.3.6.1.2.1.31.1.1.1.1
          targets:
            - ifAdminStatus
            - ifOperStatus
          values: ["^wan.*"]
```
but this one does:
```
    filters:
      dynamic: 
        - oid: 1.3.6.1.2.1.31.1.1.1.1
          targets:
            - 1.3.6.1.2.1.2.2.1.7
            - 1.3.6.1.2.1.2.2.1.8
          values: ["^wan.*"]
```

### What did you expect to see?
Been able to use names like in the `walk` section. Would be easier to read / maintain

### What did you see instead?
The probe fail
