### ISSUE TITLE
HP  blade cannot send data

### ISSUE THREAD

**Issue by ugatu20** [prometheus/snmp_exporter#1019]
### What did you expect to see?
Disk bay number and state
### What did you see instead?
Nothing!

Hello! 
I'm trying to get info about drivers and bays for HP blade-server with snmp-exporter 1.5.1
In console do i snmpwalk and get result
snmpwalk -v 3 -a SHA -A MySHAKey -l authPriv -u MyUser -x AES -X MyAESKey serverIP 1.3.6.1.4.1.232.3.2.5.1.1.6.0
And have response like:
iso.3.6.1.4.1.232.3.2.5.1.1.6.0.0 = INTEGER: 2
iso.3.6.1.4.1.232.3.2.5.1.1.6.0.1 = INTEGER: 2

In exporter manifest i have auth-section
```
config: |
  auths:
    my_v3sha1:
      version: 3
      security_level: authPriv
      auth_protocol: SHA
      username: MyUser
      password: MySHAKey
      priv_protocol: AES
      priv_password: MyAESKey
```

And i include this auth in host-params section
```
params:
    - name: serverName
      target: "serverIP"
      auth: my_v3sha1
      module:
        - if_mib
      labels: {}
      interval: 30s
      scrapeTimeout: 30s
      relabelings: []
      additionalMetricsRelabels: {}
```
But there is no data. How can I fix this?
