### ISSUE TITLE
The OID value queried is a string and I want to convert it into a numerical value.

### ISSUE THREAD

**Issue by jycgxds** [prometheus/snmp_exporter#1021]
Contents of my snmp.yml file:
```
tttt:
   walk:
   - 1.3.6.1.4.1.15.8886.1067.1.0
   metrics:
   - name: ups
     oid: 1.3.6.1.4.1.15.8886.1067.1.0
     type: DisplayString
   version: 2
   auth:
     community: public

```

The result queried after running through snmp-exporter is
![image](https://github.com/prometheus/snmp_exporter/assets/44128073/c05e67cd-607e-4fe4-83f4-072e9d825f86)
