### ISSUE TITLE
Issues with label replacement after latest missing label PR

### ISSUE THREAD

**Issue by zerosignal0** [prometheus/snmp_exporter#103]
Hello,

I have been experimenting with using snmp_exporter for walking networking devices (primarily Arista) and have been using label substitutions.  I have found that after updating snmp_exporter to the latest PR https://github.com/prometheus/snmp_exporter/pull/100 that a majority of labels are now being returned as blank causing errors to be reported back from snmp_exporter on completion.

Can we please work to validate what has caused the regression?  I will work to experiment a bit with the diff between commits, but this is a pretty breaking change (at least to me) at the moment.

Cheers,

**example pre-PR100 working snmp.yml**
```yaml
---
arista:
  auth:
    community: <REMOVED>
  walk:
    - 1.3.6.1.2.1.1.3
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
    - 1.3.6.1.2.1.14
    - 1.3.6.1.2.1.15.3.1
    - 1.3.6.1.2.1.2.2.1.2
    - 1.3.6.1.4.1.30065.3.1.1.1.1
    - 1.3.6.1.4.1.30065.3.15.1.1.1
    - 1.3.6.1.4.1.30065.3.6.1.1
    - 1.3.6.1.4.1.30065.3.6.1.2
    - 1.3.6.1.2.1.99.1.1.1
    - 1.3.6.1.2.1.47.1.1.1.1.2
    - 1.3.6.1.2.1.47.1.1.1.1.4
    - 1.3.6.1.2.1.25
    - 1.3.6.1.4.1.30065.4.1.1
  metrics:
    - name: sysUpTime
      oid: 1.3.6.1.2.1.1.3
    - name: ifNumber
      oid: 1.3.6.1.2.1.2.1
    - name: ifMtu
      oid: 1.3.6.1.2.1.2.2.1.4
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifSpeed
      oid: 1.3.6.1.2.1.2.2.1.5
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifAdminStatus
      oid: 1.3.6.1.2.1.2.2.1.7
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOperStatus
      oid: 1.3.6.1.2.1.2.2.1.8
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInOctets
      oid: 1.3.6.1.2.1.2.2.1.10
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInUcastPkts
      oid: 1.3.6.1.2.1.2.2.1.11
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInNUcastPkts
      oid: 1.3.6.1.2.1.2.2.1.12
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInDiscards
      oid: 1.3.6.1.2.1.2.2.1.13
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInErrors
      oid: 1.3.6.1.2.1.2.2.1.14
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInUnknownProtos
      oid: 1.3.6.1.2.1.2.2.1.15
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutOctets
      oid: 1.3.6.1.2.1.2.2.1.16
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutUcastPkts
      oid: 1.3.6.1.2.1.2.2.1.17
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutNUcastPkts
      oid: 1.3.6.1.2.1.2.2.1.18
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutDiscards
      oid: 1.3.6.1.2.1.2.2.1.19
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutErrors
      oid: 1.3.6.1.2.1.2.2.1.20
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutQLen
      oid: 1.3.6.1.2.1.2.2.1.21
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInMulticastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.2
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifInBroadcastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.3
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutMulticastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.4
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifOutBroadcastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.5
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCInOctets
      oid: 1.3.6.1.2.1.31.1.1.1.6
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCInUcastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.7
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCInMulticastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.8
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCInBroadcastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.9
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCOutOctets
      oid: 1.3.6.1.2.1.31.1.1.1.10
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCOutUcastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.11
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCOutMulticastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.12
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHCOutBroadcastPkts
      oid: 1.3.6.1.2.1.31.1.1.1.13
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifLinkUpDownTrapEnable
      oid: 1.3.6.1.2.1.31.1.1.1.14
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifHighSpeed
      oid: 1.3.6.1.2.1.31.1.1.1.15
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifPromiscuousMode
      oid: 1.3.6.1.2.1.31.1.1.1.16
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: ifConnectorPresent
      oid: 1.3.6.1.2.1.31.1.1.1.17
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
    - name: ospfNbrState
      oid: 1.3.6.1.2.1.14.10.1.6
      indexes:
        - labelname: routerId
          type: IpAddress
      lookups:
        - labels: [routerId]
          labelname: routerId
          oid: 1.3.6.1.2.1.14.10.1.3
    - name: ospfSpfRuns
      oid: 1.3.6.1.2.1.14.2.1.4
      indexes:
        - labelname: Area
          type: IpAddress
      lookups:
        - labels: [Area]
          labelname: Area
          oid: 1.3.6.1.2.1.14.2.1.1
    - name: ospfAreaLsaCount
      oid: 1.3.6.1.2.1.14.2.1.7
      indexes:
        - labelname: Area
          type: IpAddress
      lookups:
        - labels: [Area]
          labelname: Area
          oid: 1.3.6.1.2.1.14.2.1.1
    - name: bgpPeerAdminStatus
      oid: 1.3.6.1.2.1.15.3.1.4
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: bgpPeerFsmEstablishedTransitions
      oid: 1.3.6.1.2.1.15.3.1.15
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: bgpPeerInTotalMessages
      oid: 1.3.6.1.2.1.15.3.1.12
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: bgpPeerInUpdates
      oid: 1.3.6.1.2.1.15.3.1.10
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: bgpPeerOutTotalMessages
      oid: 1.3.6.1.2.1.15.3.1.13
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: bgpPeerOutUpdates
      oid: 1.3.6.1.2.1.15.3.1.11
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: bgpPeerState
      oid: 1.3.6.1.2.1.15.3.1.2
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: aristaIfInPktRate
      oid: 1.3.6.1.4.1.30065.3.15.1.1.1.3
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: aristaIfOutPktRate
      oid: 1.3.6.1.4.1.30065.3.15.1.1.1.4
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: aristaIfInOctetRate
      oid: 1.3.6.1.4.1.30065.3.15.1.1.1.5
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: aristaIfOutOctetRate
      oid: 1.3.6.1.4.1.30065.3.15.1.1.1.6
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [Interface]
          labelname: Description
          oid: 1.3.6.1.2.1.31.1.1.1.18
    - name: aristaIngressQueuePktsDropped
      oid: 1.3.6.1.4.1.30065.3.6.1.1.1.3 
      indexes:
        - labelname: Interface
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
    - name: aristaEgressQueuePktsDropped
      oid: 1.3.6.1.4.1.30065.3.6.1.2.1.6
      indexes:
        - labelname: Interface
          type: Integer32
        - labelname: Queue
          type: Integer32
        - labelname: PacketType
          type: Integer32
      lookups:
        - labels: [Interface]
          labelname: Interface
          oid: 1.3.6.1.2.1.2.2.1.2
    - name: entPhySensorValue
      oid: 1.3.6.1.2.1.99.1.1.1.4
      indexes:
        - labelname: Index
          type: Integer32
      lookups:
        - labels: [Index]
          labelname: SensorName
          oid: 1.3.6.1.2.1.47.1.1.1.1.2
        - labels: [Index]
          labelname: Unit
          oid: 1.3.6.1.2.1.99.1.1.1.6
        - labels: [Index]
          labelname: Scale
          oid: 1.3.6.1.2.1.99.1.1.1.2
        - labels: [Index]
          labelname: Precision
          oid: 1.3.6.1.2.1.99.1.1.1.3
    - name: StorageUsed
      oid: 1.3.6.1.2.1.25.2.3.1.6
      indexes:
        - labelname: Index
          type: Integer32
      lookups:
        - labels: [Index]
          labelname: Description
          oid: 1.3.6.1.2.1.25.2.3.1.3
        - labels: [Index]
          labelname: TotalSize
          oid: 1.3.6.1.2.1.25.2.3.1.5
    - name: aristaBgp4V2PrefixInPrefixes
      oid: 1.3.6.1.4.1.30065.4.1.1.8.1.3.1.1.4
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: aristaBgp4V2PrefixInPrefixesAccepted
      oid: 1.3.6.1.4.1.30065.4.1.1.8.1.4.1.1.4
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
    - name: aristaBgp4V2PrefixOutPrefixes
      oid: 1.3.6.1.4.1.30065.4.1.1.8.1.5.1.1.4
      indexes:
        - labelname: neighbor
          type: IpAddress
      lookups:
        - labels: [neighbor]
          labelname: neighbor
          oid: 1.3.6.1.2.1.14.10.1.3
        - labels: [neighbor]
          labelname: Description
          oid: 1.3.6.1.4.1.30065.4.1.1.2.1.14.1.1.4
```
