### ISSUE TITLE
Lookups returning empty strings on Checkpoint MIB

### ISSUE THREAD

**Issue by JDA88** [prometheus/snmp_exporter#1073]
### Host operating system: output of `uname -a`
`Windows 2019`

### snmp_exporter version: output of `snmp_exporter -version`
```
snmp_exporter, version 0.25.0 (branch: HEAD, revision: 9c42d6c874d479314e612bca69558c81f8e26287)
  build user:       root@085768eb2e29
  build date:       20231210-10:04:40
  go version:       go1.21.5
  platform:         windows/amd64
  tags:             netgo
```

### What device/snmpwalk OID are you using?
Checkpoint 6200 `chkpnt.mib` [R81.20](https://support.checkpoint.com/results/sk/sk166715)

### If this is a new device, please link to the MIB(s).
MIB available [here](https://support.checkpoint.com/results/sk/sk90470) 

### What did you do that produced an error?
Two modules in `generator.yml`:
```yml
  checkpoint_nolookups_test:
    max_repetitions: 25
    retries: 3
    timeout: 5s
    walk:
      - fanSpeedSensorName   #1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      - fanSpeedSensorStatus #1.3.6.1.4.1.2620.1.6.7.8.2.1.6


  checkpoint_lookups_test:
    max_repetitions: 25
    retries: 3
    timeout: 5s
    walk:
      - fanSpeedSensorName   #1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      - fanSpeedSensorStatus #1.3.6.1.4.1.2620.1.6.7.8.2.1.6
    lookups:
      - source_indexes: [fanSpeedSensorIndex]
        lookup: fanSpeedSensorName
        drop_source_indexes: false
```

output in `snmp.yml`:
```yml
  checkpoint_nolookups_test:
    walk:
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
    metrics:
    - name: fanSpeedSensorName
      oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      type: DisplayString
      help: Sensor name - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      indexes:
      - labelname: fanSpeedSensorIndex
        type: gauge
    - name: fanSpeedSensorStatus
      oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
      type: gauge
      help: Sensor is out of range TRUE(1), FALSE(0), READING ERROR(2) - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
      indexes:
      - labelname: fanSpeedSensorIndex
        type: gauge
    max_repetitions: 25
    retries: 3
    timeout: 5s


  checkpoint_lookups_test:
    walk:
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
    metrics:
    - name: fanSpeedSensorName
      oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      type: DisplayString
      help: Sensor name - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      indexes:
      - labelname: fanSpeedSensorIndex
        type: gauge
      lookups:
      - labels:
        - fanSpeedSensorIndex
        labelname: fanSpeedSensorName
        oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
        type: DisplayString
    - name: fanSpeedSensorStatus
      oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
      type: gauge
      help: Sensor is out of range TRUE(1), FALSE(0), READING ERROR(2) - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
      indexes:
      - labelname: fanSpeedSensorIndex
        type: gauge
      lookups:
      - labels:
        - fanSpeedSensorIndex
        labelname: fanSpeedSensorName
        oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
        type: DisplayString
    max_repetitions: 25
    retries: 3
    timeout: 5s

```

### What did you expect to see?
```
# HELP fanSpeedSensorStatus Sensor is out of range TRUE(1), FALSE(0), READING ERROR(2) - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
# TYPE fanSpeedSensorStatus gauge
fanSpeedSensorStatus{fanSpeedSensorIndex="1",fanSpeedSensorName="System Fan 1"} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="2",fanSpeedSensorName="System Fan 2"} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="3",fanSpeedSensorName="System Fan 3"} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="4",fanSpeedSensorName="System Fan 4"} 0
```

### What did you see instead?
`checkpoint_nolookups_test` return:
```
# HELP fanSpeedSensorName Sensor name - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
# TYPE fanSpeedSensorName gauge
fanSpeedSensorName{fanSpeedSensorIndex="1",fanSpeedSensorName="System Fan 1"} 1
fanSpeedSensorName{fanSpeedSensorIndex="2",fanSpeedSensorName="System Fan 2"} 1
fanSpeedSensorName{fanSpeedSensorIndex="3",fanSpeedSensorName="System Fan 3"} 1
fanSpeedSensorName{fanSpeedSensorIndex="4",fanSpeedSensorName="System Fan 4"} 1
# HELP fanSpeedSensorStatus Sensor is out of range TRUE(1), FALSE(0), READING ERROR(2) - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
# TYPE fanSpeedSensorStatus gauge
fanSpeedSensorStatus{fanSpeedSensorIndex="1"} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="2"} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="3"} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="4"} 0
```

`checkpoint_lookups_test` return:
```
# HELP fanSpeedSensorName Sensor name - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
# TYPE fanSpeedSensorName gauge
fanSpeedSensorName{fanSpeedSensorIndex="1",fanSpeedSensorName=""} 1
fanSpeedSensorName{fanSpeedSensorIndex="2",fanSpeedSensorName=""} 1
fanSpeedSensorName{fanSpeedSensorIndex="3",fanSpeedSensorName=""} 1
fanSpeedSensorName{fanSpeedSensorIndex="4",fanSpeedSensorName=""} 1
# HELP fanSpeedSensorStatus Sensor is out of range TRUE(1), FALSE(0), READING ERROR(2) - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
# TYPE fanSpeedSensorStatus gauge
fanSpeedSensorStatus{fanSpeedSensorIndex="1",fanSpeedSensorName=""} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="2",fanSpeedSensorName=""} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="3",fanSpeedSensorName=""} 0
fanSpeedSensorStatus{fanSpeedSensorIndex="4",fanSpeedSensorName=""} 0
```

No matter what I tested I cannot find a way to match `fanSpeedSensorName` on `tempertureSensorIndex` and the `fanSpeedSensorName` end up empty. I never faced this on any mibs.
Other lookups like `ifIndex` > `ifName` works just fine, but every lookup under 1.3.6.1.4.1.2620.* fail.
Debug log show no issues on walking and the `nolookups` version cant get the value just fine.

**Comment by SuperQ** [comment]
Can you share the snmp.yml output as well?

**Comment by JDA88** [comment]
> Can you share the snmp.yml output as well?

Orriginal post updated with the `snmp.yml` output.

**Comment by SuperQ** [comment]
That is extremely strange. Would you mind testing with v0.24.1? I wonder if this is related to https://github.com/prometheus/snmp_exporter/pull/782.

**Comment by JDA88** [comment]
I was developing with v0.24.1 and tested with v0.25 just to be sure. Same behavior.
It is indeed very strange, never saw this, I tested with multiples targets, same results.
Same with `tempertureSensorName` / `tempertureSensorStatus` / `tempertureSensorIndex`

**Comment by SuperQ** [comment]
Yea, I have never seen lookup strings fail like that. Maybe try all the way back to 0.23.0 and 0.22.0? There have been a few misc changes to the lookups over the last few versions.

**Comment by JDA88** [comment]
I don't have the generator for version <0.24  format anymore.. I'll try to find a way to test this.

**Comment by JDA88** [comment]
v0.22 with the old format, Same behavior! oO

**Comment by JDA88** [comment]
Ok, sorry if I’m saying something completely stupid but browsing the SNMP on this device with “FrameFlow SNMP Browser”  I noticed this:
![image](https://github.com/prometheus/snmp_exporter/assets/67072186/d0327522-7116-451f-af53-7607ebb136b6)
VS
![image](https://github.com/prometheus/snmp_exporter/assets/67072186/204ba58d-e884-496c-b55c-6d32188e92ae)


for the `fanSpeedSensorName` it looks like the OID for the first value is `1.3.6.1.4.1.2620.1.6.7.8.2.1.2.1.0` and not `1.3.6.1.4.1.2620.1.6.7.8.2.1.2.1` with an additional zero after the index. I don't if it's expected?

This
```yml
  checkpoint_nolookups_test:
    walk:
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2.1.0
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2.2
```
return:
```
# HELP fanSpeedSensorName Sensor name - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2.1.0
# TYPE fanSpeedSensorName gauge
fanSpeedSensorName{fanSpeedSensorIndex="1",fanSpeedSensorName="System Fan 1"} 1
fanSpeedSensorName{fanSpeedSensorIndex="2",fanSpeedSensorName="System Fan 2"} 1
```

So both works, but maybe it mess up the lookups?

**Comment by SuperQ** [comment]
That does appear to be either a device bug (an additional octet) or a MIB bug (missing 2-dimension index).

Right now, the listed single value index does not match what the snmpwalk returns. That's why the lookup result is empty.

**Comment by SuperQ** [comment]
As a workaround, you could try manually modifying the index in the snmp.yml.

```yaml
  checkpoint_lookups_test:
    walk:
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
    - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
    metrics:
    - name: fanSpeedSensorName
      oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      type: DisplayString
      help: Sensor name - 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
      indexes:
      - labelname: fanSpeedSensorIndex
        type: gauge
      - labelname: fanSpeedSensorCheckpointLol
        type: gauge
      lookups:
      - labels:
        - fanSpeedSensorIndex
        labelname: fanSpeedSensorName
        oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
        type: DisplayString
    - name: fanSpeedSensorStatus
      oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
      type: gauge
      help: Sensor is out of range TRUE(1), FALSE(0), READING ERROR(2) - 1.3.6.1.4.1.2620.1.6.7.8.2.1.6
      indexes:
      - labelname: fanSpeedSensorIndex
        type: gauge
      - labelname: fanSpeedSensorCheckpointLol
        type: gauge
      lookups:
      - labels:
        - fanSpeedSensorIndex
        - fanSpeedSensorCheckpointLol
        labelname: fanSpeedSensorName
        oid: 1.3.6.1.4.1.2620.1.6.7.8.2.1.2
        type: DisplayString
    max_repetitions: 25
    retries: 3
    timeout: 5s
```
