### ISSUE TITLE
Dynamically load targets and modules

### ISSUE THREAD

**Issue by mohanprasaths** [prometheus/snmp_exporter#108]
To add targets dynamically Iam using file_sd_config . But I have to load modules respective to targets .
ie: 

**_# prometheus.yml_**

```
scrape_configs:
  - job_name: 'snmp'
    scrape_interval: 200s
    scrape_timeout: 200s
    file_sd_configs:
        - files :
          - targets.yml
    metrics_path: /snmp
    params:
      module: [cisco_wlc] #which OID's we will be querying in
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmpexporter:9116
```

# **_targets.yml_**

```
- targets:
   -x.x.x.Cisco
   -x.x.x.Brocade
   -x.x.x.Cisco
  labels:
    job: snmp
```

Consider I have 4 different modules configured in snmp.yml [Brocade ,Cisco ,CiscoIPSLA, BrocadeIPSLA]

I have to load modules for polling based on router .

So far my solution is  : I will write in prometheus.yml dynamically multiple scrap_configs and 
do post to "http://prometheus:9090/-/reload" to reload configuration .

Please let me know if  there is any better way ?

PS: Prometheus should never be restarted .
