### ISSUE TITLE
Sonicwall Firewall / snmp exporter / prometheus

### ISSUE THREAD

**Issue by R4ZZB3RRY** [prometheus/snmp_exporter#1120]
Hi.  I'm having trouble getting snmp data from Prometheus.  I think I've configured the prometheus.yml file correctly, and have started looking at the generator.yml file.  I can successfully snmpwalk my firewall so I know snmp is working.  Can someone spot where I went wrong.  Here is the code in my prometheus.yml and generator.yml

Generator.yml

```
---
auths:
  public_v1:
    version: 1
  public_v2:
    version: 2

modules:
  # Default IF-MIB interfaces table with ifIndex.
  if_mib:
    walk: 
      - 1.3.6.1.2.1.31.1.1
      - 1.3.6.1.2.1.2.2
      - sysUpTime
      - interfaces
      - ifXTable
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo
  synology:
    walk:
      - laNames
      - laLoadInt
      - ssCpuUser
      - ssCpuSystem
      - ssCpuIdle
      - memory
      - interfaces
      - sysUpTime
      - ifXTable
      - 1.3.6.1.4.1.6574.1       # synoSystem
      - 1.3.6.1.4.1.6574.2       # synoDisk
      - 1.3.6.1.4.1.6574.3       # synoRaid
      - 1.3.6.1.4.1.6574.4       # synoUPS
      - 1.3.6.1.4.1.6574.5       # synologyDiskSMART
      - 1.3.6.1.4.1.6574.6       # synologyService
      - 1.3.6.1.4.1.6574.101     # storageIO
      - 1.3.6.1.4.1.6574.102     # spaceIO
      - 1.3.6.1.4.1.6574.104     # synologyiSCSILUN
      - 1.3.6.1.2.1.2.2
      - 1.3.6.1.2.1.31.1.1
      - 1.3.6.1.2.1.2.2.1.6      #ifPhysAddress
      - 1.3.6.1.2.1.31.1.1
      - 1.3.6.1.2.1.2.2

    lookups:
      - source_indexes: [spaceIOIndex]
        lookup: spaceIODevice
        drop_source_indexes: true
      - source_indexes: [storageIOIndex]
        lookup: storageIODevice
        drop_source_indexes: true
      - source_indexes: [serviceInfoIndex]
        lookup: serviceName
        drop_source_indexes: true
      - source_indexes: [diskIndex]
        lookup: diskID
        drop_source_indexes: true
      - source_indexes: [raidIndex]
        lookup: raidName
        drop_source_indexes: true
      - source_indexes: [laIndex]
        lookup: laNames
        drop_source_indexes: true
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo
      diskModel:
        type: DisplayString
      diskSMARTAttrName:
        type: DisplayString
      diskSMARTAttrStatus:
        type: DisplayString
      diskSMARTInfoDevName:
        type: DisplayString
      diskType:
        type: DisplayString
      modelName:
        type: DisplayString
      raidFreeSize:
        type: gauge
      raidName:
        type: DisplayString
      raidTotalSize:
        type: gauge
      serialNumber:
        type: DisplayString
      serviceName:
        type: DisplayString
      version:
        type: DisplayString
  sonicwall:
    walk:
      - 1.3.6.1.2.1.31.1.1
      - 1.3.6.1.2.1.2.2
      - sysUpTime
      - interfaces
      - ifXTable
      - sonicCurrentRAMUtil
      - sonicCurrentCPUUtil
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo
```

Prometheus.yml

```
# my global config
global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "linux"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "Windows"
    static_configs:
      - targets: ['xxx.xxx.xxx.xxx:9182', 'xxx.xxx.xxx.xxx:9182']
  - job_name: 'snmp'
    static_configs:
      - targets:
        - xxx.xxx.xxx.xxx
        - xxx.xxx.xxx.xxx
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter
  - job_name: 'synologynas'
    static_configs:
      - targets:
        - xxx.xxx.xxx.xxx
    metrics_path: /snmp
    params:
      module: [synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['localhost:9116']
  - job_name: 'Sonicwall'
    static_configs:
      - targets:
        - xxx.xxx.xxx.xxx
    metrics_path: /snmp
    params:
      module: [sonicwall]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
```

### Host operating system: output of `uname -a`
5.15.0-94-generic #104~20.04.1-Ubuntu SMP Tue Jan 16 13:34:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux VM

### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter, version 0.25.0 (branch: HEAD, revision: 9c42d6c874d479314e612bca69558c81f8e26287)
  build user:       root@880115266f70
  build date:       20231210-10:05:18
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo

### What device/snmpwalk OID are you using?
Sonicwall Firewall using OID .1.3.6.1.4.1.8741.1.3.1.4
