### ISSUE TITLE
Generator - get without .0 + unwanted walk

### ISSUE THREAD

**Issue by pszafarczyk** [prometheus/snmp_exporter#1130]
### Host operating system: output of `uname -a`
Linux ... 6.1.55-75.123.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 26 20:06:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

0.25.0

### What device/snmpwalk OID are you using?
1.3.6.1.2.1.4.24 (IP-MIB)

### What did you do that produced an error?
I am using the following generator.yml file:
```
[...]
modules:
  x:
    walk:
      - "1.3.6.1.2.1.4.24"
    filters:
      static:
        - targets:
          - "1.3.6.1.2.1.4.24"
          indices: ["6"]

```
### What did you expect to see?
snmp.yml:
```
modules:
  x:
    get:
    - 1.3.6.1.2.1.4.24.6.0

```
### What did you see instead?
```
modules:
  x:
    walk:
    - 1.3.6.1.2.1.4.24.7.1.1
    - 1.3.6.1.2.1.4.24.7.1.5
    get:
    - 1.3.6.1.2.1.4.24.6

```

**Comment by bastischubert** [comment]
1.3.6.1.2.1.4.24 is not a table - filters are meant to work on tables.

```
modules:
  x:
    walk:
      - "inetCidrRouteNumber"
```
can be used to achieve what you're looking for
