### ISSUE TITLE
Table non-read-only indexes Get ?

### ISSUE THREAD

**Issue by luweijun1992** [prometheus/snmp_exporter#1159]
[hwWlanRadioInfoTable](https://support.huawei.com/hedex/hdx.do?docid=EDOC1100278055&id=EN-US_CONCEPT_0176928119&lang=en)

The indexes of this table are hwWlanRadioInfoApMac and hwWlanRadioID.
![image](https://github.com/prometheus/snmp_exporter/assets/58923704/6d81f145-9944-4839-bcfd-9afdddc4c617)
---
snmpwalk Unable to get indexes OID
![image](https://github.com/prometheus/snmp_exporter/assets/58923704/ba76f859-d66e-4b05-b94b-5797265286f8)
---
Generating configuration
```
---
auths:
  public_v2:
    version: 2
    community: public

modules:
  huawei_wlan_ap:
    walk:
      # HUAWEI-WLAN-AP-RADIO-MIB::hwWlanRadioInfoTable
      # - 1.3.6.1.4.1.2011.6.139.16.1.2.1.1
      # - 1.3.6.1.4.1.2011.6.139.16.1.2.1.2
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.5
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.6
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.7
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.10
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.23
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.24
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.25
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.29
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.40
      - 1.3.6.1.4.1.2011.6.139.16.1.2.1.45
    max_repetitions: 50 # How many objects to request with GET/GETBULK, defaults to 25.
    retries: 3 # How many times to retry a failed request, defaults to 3.
    timeout: 10s # Timeout for each individual SNMP request, defaults to 5s.
    lookups:
      # HUAWEI-WLAN-AP-RADIO-MIB::hwWlanRadioInfoTable
      - source_indexes: [hwWlanRadioInfoApMac, hwWlanRadioID]
        lookup: hwWlanRadioInfoApName
    overrides:
      # HUAWEI-WLAN-AP-RADIO-MIB::hwWlanRadioInfoTable
      hwWlanRadioInfoApName:
        ignore: true
        type: DisplayString
```
---
config.file
```
# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
auths:
  public_v2:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 2
modules:
  huawei_wlan_ap:
    walk:
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.10
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.23
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.24
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.25
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.29
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.40
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.45
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.5
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.6
    - 1.3.6.1.4.1.2011.6.139.16.1.2.1.7
    metrics:
    - name: hwWlanRadioWorkingChannelBandwidth
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.10
      type: gauge
      help: This object indicates the actual channel bandwidth. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.10
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
      enum_values:
        1: ht20
        2: ht40Plus
        3: ht40Minus
        4: ht80
        5: ht160
        255: unknown
    - name: hwWlanRadioPER
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.23
      type: gauge
      help: This object indicates the packet error rate at the wireless side. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.23
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
    - name: hwWlanRadioNoise
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.24
      type: gauge
      help: This object indicates the interference noise of the radio - 1.3.6.1.4.1.2011.6.139.16.1.2.1.24
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
    - name: hwWlanRadioChUtilizationRate
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.25
      type: gauge
      help: This object indicates the channel usage on the radio. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.25
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
    - name: hwWlanRadioChInterferenceRate
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.29
      type: gauge
      help: This object indicates the interference rate. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.29
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
    - name: hwWlanRadioOnlineStaCnt
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.40
      type: gauge
      help: This object indicates the number of online users of the radio. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.40
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
    - name: hwWlanRadioActualEIRP
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.45
      type: gauge
      help: This object indicates the actual power of a radio, invalid value is 255.
        - 1.3.6.1.4.1.2011.6.139.16.1.2.1.45
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
    - name: hwWlanRadioFreqType
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.5
      type: gauge
      help: This object indicates the radio frequency band. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.5
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
      enum_values:
        1: frequency2G
        2: frequency5G
        3: frequency6G
    - name: hwWlanRadioRunState
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.6
      type: gauge
      help: This object indicates the running status of the radio. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.6
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
      enum_values:
        1: up
        2: down
        255: invalid
    - name: hwWlanRadioWorkingChannel
      oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.7
      type: gauge
      help: This object indicates the actual channel of a radio. - 1.3.6.1.4.1.2011.6.139.16.1.2.1.7
      indexes:
      - labelname: hwWlanRadioInfoApMac
        type: PhysAddress48
        fixed_size: 6
      - labelname: hwWlanRadioID
        type: gauge
      lookups:
      - labels:
        - hwWlanRadioInfoApMac
        - hwWlanRadioID
        labelname: hwWlanRadioInfoApName
        oid: 1.3.6.1.4.1.2011.6.139.16.1.2.1.3
        type: DisplayString
    max_repetitions: 50
    retries: 3
    timeout: 10s
```
---
Result
![image](https://github.com/prometheus/snmp_exporter/assets/58923704/eb567123-e8a2-4b6c-86bb-fb1610ac1b58)
---
How to get the two indexes in this table?
