### ISSUE TITLE
gosnmp sets SnmpPDU.Value to nil when type is Bitstring

### ISSUE THREAD

**Issue by nathanlcarlson** [prometheus/snmp_exporter#1216]
### Host operating system: output of `uname -a`
Docker on Mac

Linux cc14ccb5bd57 6.6.31-linuxkit #1 SMP PREEMPT_DYNAMIC Wed Jun  5 07:37:32 UTC 2024 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.24.0 (branch: HEAD, revision: c9fd025309572b81eaca65100de4ca38ea406da9)
  build user:       root@fb4e1a1f31ed
  build date:       20230829-12:20:02
  go version:       go1.21.0
  platform:         linux/amd64
  tags:             netgo

### What device/snmpwalk OID are you using?
Two switches, "Switch A" and "Switch B" that are from separate manufacturers with separate OS's.
dot3adAggPortActorAdminState
dot3adAggPortActorOperState
1.2.840.10006.300.43.1.2.1.1.21 and 1.2.840.10006.300.43.1.2.1.1.23

### If this is a new device, please link to the MIB(s).
https://github.com/librenms/librenms/blob/04101c2c6f7411b2f882b5ea05c6a5c1ef77cff5/mibs/IEEE8023-LAG-MIB

### What did you do that produced an error?
```
modules:
  dot3ad:
    walk:
      - dot3adAggPortActorOperState
      - dot3adAggPortPartnerOperState
    lookups:
      - source_indexes: [dot3adAggPortIndex]
        lookup: dot3adAggPortActorSystemID
      - source_indexes: [dot3adAggPortIndex]
        lookup: dot3adAggPortActorPort
      - source_indexes: [dot3adAggPortIndex]
        lookup: dot3adAggPortSelectedAggID
      - source_indexes: [dot3adAggPortIndex]
        lookup: dot3adAggPortPartnerOperSystemID
      - source_indexes: [dot3adAggPortIndex]
        lookup: dot3adAggPortPartnerOperPort
```
### What did you expect to see?
This worked as expected on Switch A, following the Bits support code in this exporter. It created a StateSet.

### What did you see instead?
 Switch B fails, reporting the following:
```
* error collecting metric Desc{fqName: "snmp_error", help: "BITS type was not a BISTRING on the wire.", constLabels: {}, variableLabels: []}: error for metric dot3adAggPortPartnerOperState with labels [{expected labels}]: <nil>
```
More investigation found that the switches report this OID as different types.
Switch A, that succeeds, reports a `String`:
```
$ snmpget -DALL -v 2c -c {community string} {host A}  1.2.840.10006.300.43.1.2.1.1.23.{index}
...
dumph_recv:         Value
dumpx_recv:          04 01 3D 
dumpv_recv:            String:	=
...
```
Switch B, that fails, reports a `Bitstring`:
```
$ snmpget -DALL -v 2c -c {community string} {host B} 1.2.840.10006.300.43.1.2.1.1.23.{index}
...
dumph_recv:         Value
dumpx_recv:          03 01 
dumpv_recv:            Bitstring: 03 
...
```
I created this issue https://github.com/gosnmp/gosnmp/issues/472 as I'm not sure where this should be addressed.
