### ISSUE TITLE
 Problem generating SNMP config for cIpM... metrics

### ISSUE THREAD

**Issue by rwgrony** [prometheus/snmp_exporter#1218]
### Host operating system: output of `uname -a`
Linux 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`
0.24.1

### What device/snmpwalk OID are you using?
```
$ snmptranslate -On -IR CISCO-IETF-IPMROUTE-MIB:cIpMRouteHCOctets
.1.3.6.1.4.1.9.10.117.1.1.2.1.17
$ snmptranslate -On -IR CISCO-IETF-IPMROUTE-MIB:cIpMRouteHCPkts
.1.3.6.1.4.1.9.10.117.1.1.2.1.26
$ snmptranslate -On -IR CISCO-IETF-IPMROUTE-MIB:cIpMRouteGroup
.1.3.6.1.4.1.9.10.117.1.1.2.1.2
$ snmptranslate -On -IR CISCO-IETF-IPMROUTE-MIB:cIpMRouteEntryCount
.1.3.6.1.4.1.9.10.117.1.1.7
```
### If this is a new device, please link to the MIB(s).
https://www.circitor.fr/Mibs/Html/C/CISCO-IETF-IPMROUTE-MIB.php
### What did you do that produced an error?
I am trying to generate an SNMP config to collect the following metrics:

- cIpMRouteEntryCount
- cIpMRouteGroup
- cIpMRouteHCPkts
- cIpMRouteHCOctets

However, when running the generator, these metrics are not added to the snmp.yml file. The logs indicate issues with handling the index type for these metrics.

my generator configuration file:
```
auths:
  auth_v2_asr:
    community: "1234"
    version: 2

modules:
  cisco_asr_module:
    walk:
      - sysDescr
      - sysUpTime
      - ifName
      - ifAlias
      - ifHighSpeed
      - ifAdminStatus
      - ifOperStatus
      - ifInDiscards
      - ifOutDiscards
      - ifInErrors
      - ifOutErrors
      - ifHCInOctets
      - ifHCOutOctets
      - ifHCInUcastPkts
      - ifHCOutUcastPkts
      - ifHCInBroadcastPkts
      - ifHCOutBroadcastPkts
      - ifHCInMulticastPkts
      - ifHCOutMulticastPkts
      - cIpMRouteEntryCount
      - cIpMRouteGroup
      - cIpMRouteHCPkts
      - cIpMRouteHCOctets
```
log:
```
MIBDIRS='mibs' ./generator --fail-on-parse-errors generate
ts=2024-07-18T09:39:49.572Z caller=net_snmp.go:162 level=info msg="Loading MIBs" from=mibs
ts=2024-07-18T09:39:50.682Z caller=main.go:53 level=info msg="Generating config for module" module=cisco_asr_module
ts=2024-07-18T09:39:50.709Z caller=tree.go:367 level=warn msg="Can't handle index type on node, missing preceding" node=cIpMRouteHCOctets type=InetAddress missing=InetAddressType
ts=2024-07-18T09:39:50.709Z caller=tree.go:367 level=warn msg="Can't handle index type on node, missing preceding" node=cIpMRouteGroup type=InetAddress missing=InetAddressType
ts=2024-07-18T09:39:50.709Z caller=tree.go:367 level=warn msg="Can't handle index type on node, missing preceding" node=cIpMRouteHCPkts type=InetAddress missing=InetAddressType
ts=2024-07-18T09:39:50.709Z caller=main.go:68 level=info msg="Generated metrics" module=cisco_asr_module metrics=20
```
### What did you expect to see?
The generated snmp.yml should include the specified metrics with the correct handling of InetAddressType and InetAddress indexes.
### What did you see instead?
The metrics are not added to the snmp.yml file, and the logs show warnings about missing preceding indexes.
