### ISSUE TITLE
InetAddressType Indexes/Indices being omitted

### ISSUE THREAD

**Issue by Vivida1** [prometheus/snmp_exporter#1223]
### snmp_exporter version: output of `snmp_exporter -version`
v0.26.0

### What device/snmpwalk OID are you using?
Trying to snmptable/walk jnxBgpM2PeerTable

```
    jnxBgpM2PeerTable OBJECT-TYPE
        SYNTAX     SEQUENCE OF JnxBgpM2PeerEntry
        MAX-ACCESS not-accessible
        STATUS     current
        DESCRIPTION
            "BGP peer table.

             This table contains, one entry per remote BGP peer,
             any information about the connections with the remote
             BGP peers."
        ::= { jnxBgpM2PeerData 1 }


    jnxBgpM2PeerEntry OBJECT-TYPE
        SYNTAX     JnxBgpM2PeerEntry
        MAX-ACCESS not-accessible
        STATUS     current
        DESCRIPTION
            "Entry containing information about the connection with
             a remote BGP peer."
        INDEX {
            jnxBgpM2PeerRoutingInstance,
            jnxBgpM2PeerLocalAddrType,
            jnxBgpM2PeerLocalAddr,
            jnxBgpM2PeerRemoteAddrType,
            jnxBgpM2PeerRemoteAddr
        }
        ::= { jnxBgpM2PeerTable 1 }


    JnxBgpM2PeerEntry ::= SEQUENCE {
        jnxBgpM2PeerIdentifier
            JnxBgpM2Identifier,
        jnxBgpM2PeerState
            INTEGER,
        jnxBgpM2PeerStatus
            INTEGER,
        jnxBgpM2PeerConfiguredVersion
            Unsigned32,
        jnxBgpM2PeerNegotiatedVersion
            Unsigned32,
        jnxBgpM2PeerLocalAddrType
            InetAddressType,
        jnxBgpM2PeerLocalAddr
            InetAddress,
        jnxBgpM2PeerLocalPort
            InetPortNumber,
        jnxBgpM2PeerLocalAs
            InetAutonomousSystemNumber,
        jnxBgpM2PeerRemoteAddrType
            InetAddressType,
        jnxBgpM2PeerRemoteAddr
            InetAddress,
        jnxBgpM2PeerRemotePort
            InetPortNumber,
        jnxBgpM2PeerRemoteAs
            InetAutonomousSystemNumber,
        jnxBgpM2PeerIndex
            Unsigned32,                                           -- *** JNX ***
        jnxBgpM2PeerRoutingInstance                               -- *** JNX ***
            Unsigned32
    }
```

### If this is a new device, please link to the MIB(s).
[https://www.juniper.net/documentation/software/junos/junos224/juniper-mibs-22.4R3.25.zip](https://www.juniper.net/documentation/software/junos/junos224/juniper-mibs-22.4R3.25.zip)

### What did you do that produced an error?

generator.yml
```
# Juniper Junos OS
  junosos:
    walk:
      - jnxBgpM2PeerTable
```

### What did you expect to see?
It seems that the jnxBgpM2PeerLocalAddrType and jnxBgpM2PeerRemoteAddrType are being omitted. I expected something like this:

```
    metrics:
    - name: jnxBgpM2PeerIdentifier
      oid: 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.1
      type: OctetString
      help: The BGP Identifier of this entry's remote BGP peer - 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.1
      indexes:
      - labelname: jnxBgpM2PeerRoutingInstance
        type: gauge
      - labelname: jnxBgpM2PeerLocalAddrType
        type: InetAddressType
      - labelname: jnxBgpM2PeerLocalAddr
        type: InetAddress
      - labelname: jnxBgpM2PeerRemoteAddrType
        type: InetAddressType
      - labelname: jnxBgpM2PeerRemoteAddr
        type: InetAddress
```

### What did you see instead?

```
  metrics:
    - name: jnxBgpM2PeerIdentifier
      oid: 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.1
      type: OctetString
      help: The BGP Identifier of this entry's remote BGP peer - 1.3.6.1.4.1.2636.5.1.1.2.1.1.1.1
      indexes:
      - labelname: jnxBgpM2PeerRoutingInstance
        type: gauge
      - labelname: jnxBgpM2PeerLocalAddr
        type: InetAddress
      - labelname: jnxBgpM2PeerRemoteAddr
        type: InetAddress
```

When manually adding the jnxBgpM2PeerLocalAddrType and jnxBgpM2PeerRemoteAddrType to the snmp.yml I get

```
ts=2024-07-22T09:30:53.887Z caller=tls_config.go:316 level=info msg="TLS is disabled." http2=false address=[::]:9116
panic: Unknown index type InetAddressType
```
