### ISSUE TITLE
How to scrape multi modules in one request?

### ISSUE THREAD

**Issue by geekard** [prometheus/snmp_exporter#129]
I specified a list of module names in prometheus's configure file as following:
```
  - job_name: 'snmp'
    scrape_interval: 3s
    file_sd_configs:
    - files:
      - ./sw*.json
    metrics_path: /snmp
    params:
      module: [default, juniper-mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.160.109.152:8116  # SNMP exporter.
```

Prometheus pulled from snmp_export using this URL: 
"http://10.160.109.152:8116/snmp?module=default&module=juniper-mib&target=172.29.254.3"

snmp_export seem to only scrape the first module 'default' and ignoring the follow "juniper-mib".

How to scrape multi modules in one request?
