### ISSUE TITLE
Allowing SNMP get as an alternative to walk

### ISSUE THREAD

**Issue by savoie** [prometheus/snmp_exporter#131]
**Use case:** Walking even a very short list of OID subtrees takes a very long time (~45 seconds for 10 subtrees) because of the number of leaf nodes in the tree. (Also it does not do pretty things to the device's CPU.) We only care about a very specific subset of OIDs for each target (the most important interfaces per switch), so taking 3/4 of a minute to fetch a lot of metrics before unceremoniously dropping most of them in relabeling is not ideal.

**Current solution:** One module per target, which lists _exactly_ the OIDs we want for that target.

If we want to get `ifHCInOctets` and `ifHCOutOctets` for ifIndex 555 and 666 on switch_one, then the config looks like:

```
switch_one:
  walk:
  - <ifHCInOctets OID>.555
  - <ifHCOutOctets OID>.555
  - <ifHCInOctets OID>.666
  - <ifHCOutOctets OID>.666
<label config is copied verbatim for each switch module>
```

This is not very scalable. (If there's a better way of achieving this with the exporter as-is, please point me to it. https://github.com/prometheus/snmp_exporter/issues/128 tells me this isn't currently possible.)

**Proposed functionality**: A `get` option in the configuration, that could work like so:

```
default:
  get:
  - <ifHCInOctets OID>.*
  - <ifHCOutOctets OID>.*
  - <someFullOIDWithoutWildcardIfDesired>
```

(I believe the config generator would have to generate a `get`-type module differently; rather than listing a minimal number of subtrees; it would list full OIDs but replace the final index with a wildcard.)

If a list of desired indexes were passed as a parameter along with the target, the exporter would replace the * with each index and then exclusively get the desired metrics per target without unnecessarily walking the full subtree to get a couple of metrics. (and without huge amounts of duplication in the config file)

I'd be happy to try to implement this (and likely will try to implement it on my end regardless), but would like to know if this would be a desired addition to the core exporter, and if you have any design suggestions that would help keep this in line with the design philosophy of Prometheus and the existing exporter.

**Comment by brian-brazil** [comment]
> If a list of desired indexes were passed as a parameter along with the target,

That's not something that I'm going to accept as modules should be static, and is unlikely to be practical to implement for reasons such as URL length limits.

> (I believe the config generator would have to generate a get-type module differently; rather than listing a minimal number of subtrees; it would list full OIDs but replace the final index with a wildcard.)

If the generator was to be a bit smarter I don't see why it'd have to be a different part of the config, it'd just require the generator to check if the walk was a subtree of an object rather than an object itself.

This would make lookups difficult though.

**Comment by savoie** [comment]
> That's not something that I'm going to accept as modules should be static, and is unlikely to be practical to implement for reasons such as URL length limits.

I was thinking of my indexes as part of the target here ("I'm 'targeting' interface B on switch A; it just doesn't have its own IP address"), which is why I wasn't thinking of this as changing the "staticness" of the module, but it's a very good point, as are URL length limits.

Maybe enough of a solution would be to have a config-side way of limiting which trees to walk:

```
default:
  walk:
  - <ifHCInOctets OID>.[555,666]
  - <ifHCOutOctets OID>.[555,666]
```

which would dramatically reduce the number of metrics I have to drop in the end (though I'd still need 1 scrape config per target, but such is life). If even this were causing problems, I'd still have to split into modules, but they would be significantly shorter and more manageable.

**Comment by brian-brazil** [comment]
> Maybe enough of a solution would be to have a config-side way of limiting which trees to walk:

That already works on the exporter side if you list every oid, as the exporter is dumb. On the generator side it'd be more problematic due to lookup handling.

> (though I'd still need 1 scrape config per target, but such is life)

That's a question of how fancy you are with relabelling.

**Comment by savoie** [comment]
> That already works on the exporter side if you list every oid, as the exporter is dumb.

Yeah I think ultimately my problem is "this can be done, and I have done it, but I wouldn't wish maintaining it on anyone", so if the generator could do this thing all would be good. I'll look into how the generator deals with lookup handling; I think that limits the scope of my issue very well.

> That's a question of how fancy you are with relabelling.

Fair enough! Incidentally I love Prometheus' relabeling feature.

**Comment by k0ste** [comment]
Yes, this is must be useful feature for performance reasons. I was try to cut `if_mib`, this is reduced walking time from 45s to 23s. Not fast, because switch return 260 ifaces...

before:

```yaml
INFO[0000] Starting snmp exporter (version=0.8.0, branch=HEAD, revision=17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)  source="main.go:125"
INFO[0000] Build context (go=go1.9.2, user=root@57f813d2791a, date=20171120-12:36:57)  source="main.go:126"
INFO[0000] Listening on :9116                            source="main.go:205"
DEBU[0006] Scraping target '10.100.129.7' with module 'if_mib'  source="main.go:73"
DEBU[0006] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0006] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.1.3" completed in 96.902959ms  source="collector.go:81"
DEBU[0006] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2"  source="collector.go:71"
DEBU[0028] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2" completed in 22.060744771s  source="collector.go:81"
DEBU[0028] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1"  source="collector.go:71"
DEBU[0051] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1" completed in 23.02536072s  source="collector.go:81"
DEBU[0051] Scrape of target '10.100.129.7' with module 'if_mib' took 45.300807 seconds  source="main.go:84"
DEBU[0057] Scraping target '10.100.129.7' with module 'if_mib'  source="main.go:73"
DEBU[0057] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0057] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.1.3" completed in 61.877209ms  source="collector.go:81"
DEBU[0057] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2"  source="collector.go:71"
DEBU[0079] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2" completed in 22.413499114s  source="collector.go:81"
DEBU[0079] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1"  source="collector.go:71"
DEBU[0132] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1" completed in 53.037746321s  source="collector.go:81"
DEBU[0132] Scrape of target '10.100.129.7' with module 'if_mib' took 75.620550 seconds  source="main.go:84"
```

New module with only what I need:

```yaml
eltex:
  walk:
  - 1.3.6.1.2.1.2.2.1.1
  - 1.3.6.1.2.1.2.2.1.10
  - 1.3.6.1.2.1.2.2.1.16
  - 1.3.6.1.2.1.31.1.1.1.1
  - 1.3.6.1.2.1.31.1.1.1.6
  - 1.3.6.1.2.1.31.1.1.1.10
  - 1.3.6.1.2.1.31.1.1.1.18
  metrics:
  - name: ifIndex
    oid: 1.3.6.1.2.1.2.2.1.1
    type: gauge
    help: A unique value, greater than zero, for each interface - 1.3.6.1.2.1.2.2.1.1
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifInOctets
    oid: 1.3.6.1.2.1.2.2.1.10
    type: counter
    help: The total number of octets received on the interface, including framing
      characters - 1.3.6.1.2.1.2.2.1.10
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifOutOctets
    oid: 1.3.6.1.2.1.2.2.1.16
    type: counter
    help: The total number of octets transmitted out of the interface, including framing
      characters - 1.3.6.1.2.1.2.2.1.16
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifName
    oid: 1.3.6.1.2.1.31.1.1.1.1
    type: DisplayString
    help: The textual name of the interface - 1.3.6.1.2.1.31.1.1.1.1
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCInOctets
    oid: 1.3.6.1.2.1.31.1.1.1.6
    type: counter
    help: The total number of octets received on the interface, including framing
      characters - 1.3.6.1.2.1.31.1.1.1.6
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifHCOutOctets
    oid: 1.3.6.1.2.1.31.1.1.1.10
    type: counter
    help: The total number of octets transmitted out of the interface, including framing
      characters - 1.3.6.1.2.1.31.1.1.1.10
    indexes:
    - labelname: ifIndex
      type: gauge
  - name: ifAlias
    oid: 1.3.6.1.2.1.31.1.1.1.18
    type: DisplayString
    help: This object is an 'alias' name for the interface as specified by a network
      manager, and provides a non-volatile 'handle' for the interface - 1.3.6.1.2.1.31.1.1.1.18
    indexes:
    - labelname: ifIndex
      type: gauge
```

Don't know why after first scrape walking is faster. I think some caches on switch side.

```go
INFO[0000] Starting snmp exporter (version=0.8.0, branch=HEAD, revision=17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)  source="main.go:125"
INFO[0000] Build context (go=go1.9.2, user=root@57f813d2791a, date=20171120-12:36:57)  source="main.go:126"
INFO[0000] Listening on :9116                            source="main.go:205"
DEBU[0015] Scraping target '10.100.129.7' with module 'eltex'  source="main.go:73"
DEBU[0015] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.1"  source="collector.go:71"
DEBU[0031] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.1" completed in 16.133126213s  source="collector.go:81"
DEBU[0031] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.10"  source="collector.go:71"
DEBU[0032] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.10" completed in 1.192335956s  source="collector.go:81"
DEBU[0032] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.16"  source="collector.go:71"
DEBU[0033] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.16" completed in 1.117048693s  source="collector.go:81"
DEBU[0033] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.1"  source="collector.go:71"
DEBU[0034] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.1" completed in 1.190907944s  source="collector.go:81"
DEBU[0034] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.6"  source="collector.go:71"
DEBU[0035] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.6" completed in 1.234484585s  source="collector.go:81"
DEBU[0035] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.10"  source="collector.go:71"
DEBU[0037] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.10" completed in 1.228597746s  source="collector.go:81"
DEBU[0037] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.18"  source="collector.go:71"
DEBU[0038] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.18" completed in 1.356154549s  source="collector.go:81"
DEBU[0038] Scrape of target '10.100.129.7' with module 'eltex' took 23.480140 seconds  source="main.go:84"
DEBU[0050] Scraping target '10.100.129.7' with module 'eltex'  source="main.go:73"
DEBU[0050] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.1"  source="collector.go:71"
DEBU[0051] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.1" completed in 1.100398018s  source="collector.go:81"
DEBU[0051] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.10"  source="collector.go:71"
DEBU[0052] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.10" completed in 1.061229933s  source="collector.go:81"
DEBU[0052] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.16"  source="collector.go:71"
DEBU[0053] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.2.2.1.16" completed in 1.16706324s  source="collector.go:81"
DEBU[0053] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.1"  source="collector.go:71"
DEBU[0054] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.1" completed in 1.272900938s  source="collector.go:81"
DEBU[0054] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.6"  source="collector.go:71"
DEBU[0056] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.6" completed in 1.244198818s  source="collector.go:81"
DEBU[0056] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.10"  source="collector.go:71"
DEBU[0057] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.10" completed in 1.273697039s  source="collector.go:81"
DEBU[0057] Walking target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.18"  source="collector.go:71"
DEBU[0058] Walk of target "10.100.129.7" subtree "1.3.6.1.2.1.31.1.1.1.18" completed in 1.229737439s  source="collector.go:81"
DEBU[0058] Scrape of target '10.100.129.7' with module 'eltex' took 8.374178 seconds  source="main.go:84"
```
