### ISSUE TITLE
audio codes sbc 7.4 new OID for active calls not working

### ISSUE THREAD

**Issue by alexbNz2021** [prometheus/snmp_exporter#1336]
Hello 

We updated our audio codes and they changed the OID for active calls, we logged a support ticket and they sent us this new OID 

snmpwalk to target works but I can't get the snmp exporter to work this is what my config is atm

```
mediantve:
  walk:
  - 1.3.6.1.2.1.1
  - 1.3.6.1.2.1.2
  - 1.3.6.1.2.1.25
  - 1.3.6.1.2.1.4
  - 1.3.6.1.4.1.5003.10.11
  - 1.3.6.1.4.1.5003.10.7
  - 1.3.6.1.4.1.5003.10.8.1
  - 1.3.6.1.4.1.5003.10.8.2.52.26
  - 1.3.6.1.4.1.5003.10.8.2.52.27
  - 1.3.6.1.4.1.5003.11.1
  - 1.3.6.1.4.1.5003.9.10.4
  get:
  - 1.3.6.1.4.1.5003.15.3.1.1.1.2
  metrics:
  - name: teams_sip_invites
    oid: 1.3.6.1.4.1.5003.15.3.1.1.1.2
    type: gauge
    help: Indicates the number of currently active INVITE dialogs. active calls - 1.3.6.1.4.1.5003.15.3.1.1.1.2
```
    
 that's my config any help would be great i'm at a loss

### Host operating system: output of `uname -a`
Linux nz-prometheus1 4.19.0-26-amd64 #1 SMP Debian 4.19.304-1 (2024-01-09) x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`
version=0.15.0

### What device/snmpwalk OID are you using?
1.3.6.1.4.1.5003.15.3.1.1.1.2 
### If this is a new device, please link to the MIB(s).
audio code sbc 7.4  
Type | gauge
Calculation Type | value
Realtime / History | Realtime
Supported Platforms | All
Web Name | Current/SBC/Call Stats/Global/Active Calls In
CLI Name | show kpi current sbc callstats global activecallsin
REST Name | /api/v1/kpi/current/sbc/callStats/global/activeCallsIn
SNMP Name | acKpiSbcCallStatsCurrentGlobalActiveCallsIn
SNMP OID | 1.3.6.1.4.1.5003.15.3.1.1.1.2

### What did you do that produced an error?
curl 'http://localhost:9506/snmp?target=ac-sbc&module=mediantve'
### What did you expect to see?
.1.3.6.1.4.1.5003.15.3.1.1.1.2
iso.3.6.1.4.1.5003.15.3.1.1.1.2.0 = Gauge32: 15
### What did you see instead?
DEBU[0074] OID .1.3.6.1.4.1.5003.15.3.1.1.1.2 not supported by target ac-sbc  source="collector.go:146"
