### ISSUE TITLE
Number of targets problem

### ISSUE THREAD

**Issue by lucevers** [prometheus/snmp_exporter#136]
Targets are cisco routers.

 Prometheus.yml

```
scrape_configs:
  - job_name: 'snmp'
    scrape_interval: 60s
    scrape_timeout: 60s
    file_sd_configs:
        - files :
          - /etc/prometheus/targets.yml
    metrics_path: /snmp
    params:
      module: [default] #which OID's we will be querying in

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 195.x.x.x.x:9117
```

  Max 115 targets can be put in de target file.
  The problem is not memory but CPU which become very high.
  
  If we put 500 targets then snmp_exporter blocks.
  
  Question,

     Prometheus design is based on polling (right?) which can be heavy is there are a lot of devices.
     

    We are using grafana as dashboard.
    Prometheus , snmp_exporter and Grafana are running in three separated docker containers.
    Server: Ubuntu , Memory 250Gb and cpu numbers = 55.
