### ISSUE TITLE
config generator cannot unmarshal !!seq into main.plain

### ISSUE THREAD

**Issue by HyperDevil** [prometheus/snmp_exporter#137]
Hi,

I have added a file MIKROTIK-MIB to my homefolder under .snmp/mibs/MIKROTIK-MIB

Added these simple lines on the bottom of the generator.yml
And i get this error: line 144: cannot unmarshal !!seq into main.plain

```
# Tested on Arista DCS-7010T-48 switch
#
  arista_sw:
    walk:
      - sysUpTime
      - interfaces
      - ifXTable
      - 1.3.6.1.2.1.25.3.3.1.2 # hrProcessorLoad
      - 1.3.6.1.2.1.25.2.3.1.6 # hrStorageUsed
      - 1.3.6.1.4.1.30065.3.1.1 # aristaSwFwdIp

  mikrotik:
      - sysUpTime

```
