### ISSUE TITLE
Lookup based on IpAddress Index delivers empty results

### ISSUE THREAD

**Issue by nicolai-hornung-bl** [prometheus/snmp_exporter#1373]
Generator:
```yaml
modules:
  CP_VPN_Tunnel:
    allow_nonincreasing_oids: true
    walk:
      # - 1.3.6.1.4.1.2620.500.9003.1.3.46.247.194.53.0
      - 1.3.6.1.4.1.2620.500.9002.1.3 # tunnelState
      - 1.3.6.1.4.1.2620.500.9003.1.3 # permanentTunnelState
    lookups:
      - source_indexes: [tunnelPeerIpAddr]
        lookup: tunnelPeerObjName
        drop_source_indexes: false
      - source_indexes: [permanentTunnelPeerIpAddr]
        lookup: permanentTunnelPeerObjName
        drop_source_indexes: false
    overrides:
      tunnelState:
        type: EnumAsStateSet
      permanentTunnelState:
        type: EnumAsStateSet
```
