### ISSUE TITLE
Exporter is treating "String64" syntax as "octetstring" instead of "displayString"

### ISSUE THREAD

**Issue by larsks** [prometheus/snmp_exporter#1387]
I'm using `snmp_exporter` to gather metrics from some Dell iDRAC devices. I noticed that string values were all showing up as hex strings:

```
systemBIOSManufacturerName{instance="10.2.11.112", job="idrac_snmp", systemBIOSIndex="1", systemBIOSManufacturerName="0x44656C6C20496E632E", systemBIOSchassisIndex="1"}	
```

These OIDs are delcared as `String64` in the MIB:

```
systemBIOSManufacturerName                      OBJECT-TYPE
    SYNTAX      String64
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "0300.0050.0001.0011 This attribute defines the name of the manufacturer
        of the system BIOS."
    ::= { systemBIOSTableEntry 11 }
```

`snmpwalk` displays them like this:

```
$ snmpwalk -M mibs -m ALL -v2c -c public 10.2.11.132 IDRAC-MIB-SMIv2::systemBIOSManufacturerName
IDRAC-MIB-SMIv2::systemBIOSManufacturerName.1.1 = STRING: "Dell Inc."
```

Is the problem that snmp_exporter doesn't know about the `String64` syntax? Evidence suggests that this is a Dell-ism. Is there a way to declare this an alias for `displayString`? It's going to be messy if I need to override all of these individually.

**Comment by SuperQ** [comment]
Yes, it seems like the exporter doesn't understand String64 textual convention.

**Comment by SuperQ** [comment]
It seems like the Dell MIB defines it this way:

```
String64                ::= TEXTUAL-CONVENTION
    STATUS current
    DESCRIPTION
        "General string type for 64 byte strings."
    SYNTAX              OCTET STRING (SIZE (0..64))
```

So, it does say it's a octet string, which isn't a DisplayString. So this appears to be a mistake on the Dell MIB side.

You can override it like this:

```yaml
  dell:
    walk:
      - 1.3.6.1.4.1.674.10892.5.2 # statusGroup
      - 1.3.6.1.4.1.674.10892.5.4 # systemDetailsGroup
      - 1.3.6.1.4.1.674.10892.5.5 # storageDetailsGroup
    overrides:
      systemBIOSManufacturerName:
        type: DisplayString
```
