### ISSUE TITLE
Allow scaling value after regex extract

### ISSUE THREAD

**Issue by llamafilm** [prometheus/snmp_exporter#1410]
After using regex_extract to turn a string into a number, sometimes that number needs to be scaled.  For example, I have a metric like this:

> cp850FaderLevel{cp850FaderLevel="0x3730"} 1

I use this config:
```yaml
    overrides:
      cp850FaderLevel:
        type: DisplayString
        regex_extracts:
          '':
          - regex: '(.*)'
            value: '$1'
        scale: 0.1
```

The `scale` is ignored, so the result is this:

> cp850FaderLevel 70
