### ISSUE TITLE
Lookup returning empty strings with this particular table

### ISSUE THREAD

**Issue by llamafilm** [prometheus/snmp_exporter#1416]
I'm generating a config for Sony ZRCT-200 LED wall controller.  It has many tables, usually with an index column and a description column, so I like to use a lookup to label each metric with the description.  For one particular table, it doesn't work and I end up with empty labels.  One unique thing about this table is it has 2 indexes; I'm not sure if that's relevant.

snmp-generator version 0.28.0

Generator config:
```yaml
modules:
  cled:
    walk:
    - SONY-PRO-MIB::proV1ErrStatTable # 1.3.6.1.4.1.122.8501.2.3.1
    lookups:
    - source_indexes:
      - proV1ErrStatErrIdx
      lookup: proV1ErrStatDescr
      drop_source_indexes: false
    - source_indexes:
      - proV1ErrStatErrIdx
      lookup: proV1ErrStatLevel
      drop_source_indexes: false
    - source_indexes:
      - proV1ErrStatErrIdx
      lookup: proV1ErrStatCode
      drop_source_indexes: false
    overrides:
      proV1ErrStatTime:
        ignore: true
      proV1ErrStatDescr:
        ignore: true
      proV1ErrStatProdId:
        ignore: true
      proV1ErrStatErrIdx:
        ignore: true
      proV1ErrStatLevel:
        ignore: true
```

With no lookups or overrides, the result is like this (help text removed):
```
proV1ErrStatCode{proV1ErrStatCode="121-14-11",proV1ErrStatErrIdx="140",proV1ErrStatProdId="5"} 1
proV1ErrStatCode{proV1ErrStatCode="321-14-00",proV1ErrStatErrIdx="3327",proV1ErrStatProdId="5"} 1
proV1ErrStatDescr{proV1ErrStatDescr="UC BOARD DIAG WARNING",proV1ErrStatErrIdx="3327",proV1ErrStatProdId="5"} 1
proV1ErrStatDescr{proV1ErrStatDescr="UC BOARD ERROR LIGHTING SEQUENCE",proV1ErrStatErrIdx="140",proV1ErrStatProdId="5"} 1
proV1ErrStatErrIdx{proV1ErrStatErrIdx="140",proV1ErrStatProdId="5"} 140
proV1ErrStatErrIdx{proV1ErrStatErrIdx="3327",proV1ErrStatProdId="5"} 3327
proV1ErrStatLevel{proV1ErrStatErrIdx="140",proV1ErrStatProdId="5"} 1
proV1ErrStatLevel{proV1ErrStatErrIdx="3327",proV1ErrStatProdId="5"} 4
proV1ErrStatProdId{proV1ErrStatErrIdx="140",proV1ErrStatProdId="5"} 5
proV1ErrStatProdId{proV1ErrStatErrIdx="3327",proV1ErrStatProdId="5"} 5
proV1ErrStatTime{proV1ErrStatErrIdx="140",proV1ErrStatProdId="5",proV1ErrStatTime="0x303030302F30302F30302030303A30303A30303A303020474D542B30303A3030"} 1
proV1ErrStatTime{proV1ErrStatErrIdx="3327",proV1ErrStatProdId="5",proV1ErrStatTime="0x303030302F30302F30302030303A30303A30303A303020474D542B30303A3030"} 1
```

With the lookups and overrides, the result is this:
```
proV1ErrStatCode{proV1ErrStatCode="",proV1ErrStatDescr="",proV1ErrStatErrIdx="140",proV1ErrStatLevel="",proV1ErrStatProdId="5"} 1
proV1ErrStatCode{proV1ErrStatCode="",proV1ErrStatDescr="",proV1ErrStatErrIdx="3327",proV1ErrStatLevel="",proV1ErrStatProdId="5"} 1
```

I'm expecting it to look like this:
```
proV1ErrStatCode{proV1ErrStatCode="121-14-11",proV1ErrStatDescr="UC BOARD ERROR LIGHTING SEQUENCE",proV1ErrStatErrIdx="140",proV1ErrStatLevel="1",proV1ErrStatProdId="5"} 1
proV1ErrStatCode{proV1ErrStatCode="321-14-00",proV1ErrStatDescr="UC BOARD DIAG WARNING",proV1ErrStatErrIdx="3327",proV1ErrStatLevel="4",proV1ErrStatProdId="5"} 1
```

[SONY-PRO-MIB.mib.txt](https://github.com/user-attachments/files/19816033/SONY-PRO-MIB.mib.txt)
