### ISSUE TITLE
generator EnumAsInfo failing in PDU2-MIB

### ISSUE THREAD

**Issue by Bubba210** [prometheus/snmp_exporter#1420]
### snmp_exporter version
0.28.0

### What device/snmpwalk OID are you using?

PDU2-MIB for Raritan PDUs
```
    walk:
      - measurementsOutletPoleSensorSignedValue
      - measurementsOutletSensorSignedValue
```
### What did you do that produced an error?

```
  raritan-PX3:
    walk:
      - measurementsOutletPoleSensorSignedValue
      - measurementsOutletSensorSignedValue

    lookups:
      - source_indexes: [pduId, outletId, sensorType]
        lookup: outletSensorUnits
        drop_source_indexes: false
      - source_indexes: [pduId, outletId, sensorType]
        lookup: outletSensorDecimalDigits
        drop_source_indexes: false

    overrides:
      sensorType:
        type: EnumAsInfo
      outletSensorUnits:
        type: EnumAsInfo
```

### What did you expect to see?
I expected to see the enumerated "outletSensorUnits" human readable output in the label
```
measurementsOutletSensorSignedValue{outletId="1",outletSensorDecimalDigits="0",outletSensorUnits="watts",pduId="1",sensorType="activePower"} 2184
```

### What did you see instead?
The enumeration of outletSensorUnits doesn't occur
```
measurementsOutletSensorSignedValue{outletId="1",outletSensorDecimalDigits="0",outletSensorUnits="3",pduId="1",sensorType="activePower"} 2184
```
