### ISSUE TITLE
Allow renumbering index labels

### ISSUE THREAD

**Issue by llamafilm** [prometheus/snmp_exporter#1428]
Dataprobe iBoot PDUs number the outlets starting from 1, which is shown in the `outletIndex` column of this table.  But the exporter numbers it starting from 0.

![Image](https://github.com/user-attachments/assets/e4bb3e09-6600-4a0c-b637-85c03d270f93)

I tried setting `offset: 1` in an override but that only affects the values, not the labels.

Generator config:
```yaml
auths:
  netflix_v2:
    version: 2
    community: netflixsnmp

modules:
  iboot_pdu:
    walk:
    - IBOOTPDU-MIB::device          # 1.3.6.1.4.1.1418.6.1.1
    - IBOOTPDU-MIB::outletTable     # 1.3.6.1.4.1.1418.6.5
    - IBOOTPDU-MIB::sensors         # 1.3.6.1.4.1.1418.6.6
    lookups:
    - source_indexes: [outletIndex]
      lookup: outletName
      drop_source_indexes: false
    overrides:
      voltageLC1:
        scale: 0.01
      currentLC1:
        scale: 0.01
      temperature1:
        scale: 0.01
      temperature2:
        scale: 0.01
      outletControl:
        ignore: true
      outletCycleTime:
        ignore: true
      outletInitialState:
        ignore: true
      voltageLC2:
        ignore: true
      currentLC2:
        ignore: true
      outletName:
        ignore: true

      deviceConnector:
        type: EnumAsStateSet
      deviceTemperatureUnit:
        type: EnumAsStateSet
      setFactoryDefaults:
        ignore: true
      rebootSystem:
        ignore: true
```

Sample output:
```
outletIndex{outletIndex="0",outletName="CFM"} 1
outletIndex{outletIndex="1",outletName="RX"} 2
outletIndex{outletIndex="2",outletName="TV1"} 3
outletIndex{outletIndex="3",outletName="TV2"} 4
```
