### ISSUE TITLE
add static labels to metrics

### ISSUE THREAD

**Issue by eburghar** [prometheus/snmp_exporter#157]
We implemented in the old python exporter a simple and nice feature allowing us to add static labels by adding a `labels` key to the snmp get definitions.

For instance in the example below, we have one metric `totalPage` with

- a `type` label allowing us to extract different kind of subtotal, and
- an `id` label allowing us to show `totalPage` with all subtotals as a table (grafana).

We still sadly have no skill in go, but just wanted to poke around if it looks like a goog idea to you, before diving into golang as it should only be a few lines PR.

Regards.

```yaml
      hpprinters: &_hpprinters
        <<: *_printers
        walk:
          - 1.3.6.1.2.1.25.3.2.1.3
          - 1.3.6.1.2.1.43.11.1.1.6
          - 1.3.6.1.2.1.43.11.1.1.8
          - 1.3.6.1.2.1.43.11.1.1.9
          - 1.3.6.1.2.1.43.12.1.1.4
          - 1.3.6.1.2.1.43.10.2.1
          - 1.3.6.1.4.1.11.2.3.9.4.2.1.4.1.2
          - 1.3.6.1.4.1.11.2.3.9.4.2.1.3.3.4.5
          - 1.3.6.1.4.1.11.2.3.9.4.2.1.3.3.3.5

        metrics:
          - *_prtMarkerSuppliesLevel
          - *_prtMarkerSuppliesMaxCapacity
          - *_prtMarkerLifeCount
          - *_prtMarkerPowerOnCount

          - name: totalPages
            oid: 1.3.6.1.4.1.11.2.3.9.4.2.1.4.1.2.5
            type: counter
            lookups:
              - *_hrDeviceDescr
            labels:
              type: totalEnginePageCount
              id: 1

          - name: totalPages
            oid: 1.3.6.1.4.1.11.2.3.9.4.2.1.4.1.2.7
            type: counter
            lookups:
              - *_hrDeviceDescr
            labels:
              type: totalColorPageCount
              id: 2

          - name: totalPages
            oid: 1.3.6.1.4.1.11.2.3.9.4.2.1.4.1.2.22
            type: counter
            lookups:
              - *_hrDeviceDescr
            labels:
              type: duplexPageCount
              id: 3
              
          - name: totalPages
            oid: 1.3.6.1.4.1.11.2.3.9.4.2.1.3.3.4.5
            type: counter
            lookups:
              - *_hrDeviceDescr
            labels:
              type: postscriptTotalPageCount
              id: 4
              
          - name: totalPages
            oid: 1.3.6.1.4.1.11.2.3.9.4.2.1.3.3.3.5
            type: counter
            lookups:
              - *_hrDeviceDescr
            labels:
              type: pclTotalPageCount
              id: 5
```
