### ISSUE TITLE
Minimize the scrape oids

### ISSUE THREAD

**Issue by Colstuwjx** [prometheus/snmp_exporter#159]
As I used generator from the [demo case](https://github.com/prometheus/snmp_exporter/pull/158/files#diff-42ab6a3262b91fd371d41b234451dab7R52), the snmp exporter helped me generate `snmp.yml` like:

```
huawei:
  walk:
  - 1.3.6.1.4.1.2011.6.3.4
  metrics:
  - name: hwCpuDevIndex
    oid: 1.3.6.1.4.1.2011.6.3.4.1.1
    type: gauge
    indexes:
    - labelname: hwFrameIndex
      type: gauge
    - labelname: hwSlotIndex
      type: gauge
    - labelname: hwCpuDevIndex
      type: gauge
  - name: hwCpuDevDuty
    oid: 1.3.6.1.4.1.2011.6.3.4.1.2
    type: gauge
    indexes:
    - labelname: hwFrameIndex
      type: gauge
    - labelname: hwSlotIndex
      type: gauge
    - labelname: hwCpuDevIndex
      type: gauge
  - name: hwAvgDuty1min
    oid: 1.3.6.1.4.1.2011.6.3.4.1.3
    type: gauge
    indexes:
    - labelname: hwFrameIndex
      type: gauge
    - labelname: hwSlotIndex
      type: gauge
    - labelname: hwCpuDevIndex
      type: gauge
  - name: hwAvgDuty5min
    oid: 1.3.6.1.4.1.2011.6.3.4.1.4
    type: gauge
    indexes:
    - labelname: hwFrameIndex
      type: gauge
    - labelname: hwSlotIndex
      type: gauge
    - labelname: hwCpuDevIndex
      type: gauge
```

The walk oid was `1.3.6.1.4.1.2011.6.3.4`, one thing is that the [hwCpuDevIndex](https://github.com/librenms/librenms/blob/master/mibs/huawei/HUAWEI-CPU#L70) is not accessible, and the other one is that all metrics we required is  *ONLY* 3, snmp exporter would walk all the tree node under `1.3.6.1.4.1.2011.6.3.4` !

Not only generator, We should also make snmp exporter itself minimize the oids due to these walks would make the scrape interval longer than the minimal case.

Thanks.
