### ISSUE TITLE
Accessing metrics outside of walk does not throw an error

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#16]
I had this in my config

```
walk:
  - 1.3.6.1.4.1.9.9.13.1.3.1_.3_

metrics:
  - name: ciscoEnvMonTemperatureStatusValue
    oid: 1.3.6.1.4.1.9.9.13.1.3.1.3
    indexes:
      - labelname: measuring_point
        type: Integer32
    lookups:
      - labels: [measuring_point]
        labelname: measuring_point
        oid: 1.3.6.1.4.1.9.9.13.1.3.1.2
```

which lead to

```
ciscoEnvMonTemperatureStatusValue{measuring_point="60052"} 24.0
```

changing the walk to

```
      - 1.3.6.1.4.1.9.9.13.1.3.1
```

results in

```
ciscoEnvMonTemperatureStatusValue{measuring_point="module 5 RP inlet temperature"} 24.0
```

Accessing metrics which are out of bounds should arguably lead to an error, both on cli and in the scrap target site.
