### ISSUE TITLE
Labels of type DisplayString displayed incorrectly when IP address is label source

### ISSUE THREAD

**Issue by funkelnd** [prometheus/snmp_exporter#173]
OID bgpPeerAcceptedPrefixes: 1.3.6.1.4.1.9.9.187.1.2.4.1.1 for CISCO has the indexes as IP addresses. These indexes can also be obtained from OID BgpRemoteIP: 1.3.6.1.2.1.15.3.1.7

snmp_exporter version: 0.4
config for oid:

```
    - name: bgpPeerAcceptedPrefixes
      oid: 1.3.6.1.4.1.9.9.187.1.2.4.1.1
      type: gauge
      indexes:
      - labelname: BgpRemoteIP
        type: DisplayString
```

Issue: I want these IP addresses be available as DisplayString labels, but instead get non human readable ASCII characters as label value.
Is this expected behavior? Are there known workarounds to this problem? Thanks.

**Comment by brian-brazil** [comment]
Please use the generator rather than hand creating incorrect configuration.

**Comment by funkelnd** [comment]
OctalString value is also non human readable IP address.

**Comment by funkelnd** [comment]
```
    - name: bgpPeerAcceptedPrefixes
      oid: 1.3.6.1.4.1.9.9.187.1.2.4.1.1
      type: gauge
      indexes:
      - labelname: RemoteIP
        type: DisplayString
```
With config like this - custom index label, the resulting label value is mangled string with couple of ASCII characters due to which Github wont let me quote exact value. Question remains: IP address like strings should be displayed properly with DisplayString type? Even though my snmp config currently is 1600 lines, I cannot use generator as it requires managing wast MIB resources. I rather write my own script for config generation, which just uses list of hardcoded OIDS, labels.

**Comment by brian-brazil** [comment]
The answer is to use the generator, it'll generate a correct config. Producing correct configs always requires knowledge of the MIB.

**Comment by funkelnd** [comment]
As I said, it is impossible to use generator with constantly changing infrastructure. MIB library management imposes unneeded overhead. I just cannot imagine what working config would the generator create, if there are just couple of label types available altogether.

**Comment by funkelnd** [comment]
I think I have not explained the issue properly:
With snmp.yml config:
```
    - name: BgpRemoteIP
      oid: 1.3.6.1.2.1.15.3.1.7
      type: gauge
      indexes:
      - labelname: XIP
        type: DisplayString
```
I get following metrics:
```
# HELP BgpRemoteIP 
# TYPE BgpRemoteIP gauge
BgpRemoteIP{XIP="�{�"} 0
BgpRemoteIP{XIP="�{�"} 0
```
with snmpwalk we see what is returned with this OID:
```
SNMPv2-SMI::mib-2.15.3.1.7.192.168.123.185 = IpAddress: 192.168.123.185
SNMPv2-SMI::mib-2.15.3.1.7.192.168.123.189 = IpAddress: 192.168.123.189
```
