### ISSUE TITLE
Allow overriding of MIB information

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/snmp_exporter#186]
Some MIBs aren't quite right, particularly around types. Figure out what's a sane config syntax to allow for per-module overrides of bits of MIBs.

Augments also need overriding, but we might hardcode those.

**Comment by andrewd-sterling** [comment]
Here's a use-case: the Dell MIB (in my case for the M1000e blade chassis) encodes various floating-point numbers as OctetStrings. I can't extract these currently with the regex_extracts functionality because OctetStrings get encoded as 0x333530362E303030 prior to the regex getting the value. If I override (manually edit snmp.yml) the type as DisplayString then the regex will work. Perhaps I'll be required to specify encoding since OctetStrings are opaque bytes... in this case I'd guess ascii or utf8.

Here's what snmpwalk outputs:
```
DELL-RAC-MIB::drsWattsReading.1 = STRING: "3509.000"
```
And the corresponding generated yaml:
```YAML
  - name: drsWattsReading
    oid: 1.3.6.1.4.1.674.10892.2.4.1.1.13
    type: OctetString
    help: 0004.0001.0001.0013 This attribute defines the instantaneous chassis power
      usage (in Watts). - 1.3.6.1.4.1.674.10892.2.4.1.1.13
    indexes:
    - labelname: drsChassisIndex
      type: gauge
```

**Comment by znerol** [comment]
Another example is `prtMarkerSuppliesDescription` from RFC 3805 (Printer-MIB in the Cisco collection). Those are localized strings and as a result end up as `OctetString`. Would be fantastic if there was a way to just override the relevant bits.

```
  - name: prtMarkerSuppliesDescription
    oid: 1.3.6.1.2.1.43.11.1.1.6
    type: OctetString
    help: The description of this supply container/receptacle in the localization
      specified by prtGeneralCurrentLocalization. - 1.3.6.1.2.1.43.11.1.1.6
    indexes:
    - labelname: hrDeviceIndex
      type: gauge
    - labelname: prtMarkerSuppliesIndex
      type: gauge
```

**Comment by brian-brazil** [comment]
I suspected those existed, these will be covered.

**Comment by brian-brazil** [comment]
Actually we won't support prtMarkerSuppliesDescription or anything else with localized strings where we have to look up another object to find the encoding.

**Comment by znerol** [comment]
I think it would already help if it was possible to specify the encoding for metric entries in `snmp.yml`. If the encoding is known, then an `OctetString` could be safely decoded/reencoded and exposed as string (instead of the current hex-encoding).

Generator support can be added later/independently if required.

**Comment by brian-brazil** [comment]
Such encodings would have to be a separate issue, this covers simpler type handling. In general we don't handle things that require parsing English, such as this.

**Comment by RichiH** [comment]
Do you see these overrides in between generator and config, between config and scrapes, or after scrapes?

**Comment by brian-brazil** [comment]
This is a generator thing.

**Comment by brian-brazil** [comment]
We already support extracting floats from strings.

**Comment by RichiH** [comment]
My version does not (see https://github.com/prometheus/snmp_exporter/issues/180 ) but in case anyone stumbles over this: It's been implemented in https://github.com/prometheus/snmp_exporter/pull/212 - sorry for the noise & thanks.

**Comment by SuperQ** [comment]
We now have 3 types of overrides, Ignore, Regexp Extracts, and Type.  Are there any more we need

**Comment by SuperQ** [comment]
I'm not sure what you mean by "Regexp Ignore & Type".

We just merged the Ignore and Type overrides recently, we can cut a new release sometime soon.

**Comment by RichiH** [comment]
"If that regex matches, do that other override"

**Comment by brian-brazil** [comment]
Generator changes do not require a release.

**Comment by andrewd-sterling** [comment]
I'm trying the "type" override now. Looks good for my use-case. Here's the OID metric from my previous example as normally encoded:

```
# HELP drsWattsReading 0004.0001.0001.0013 This attribute defines the instantaneous chassis power usage (in Watts). - 1.3.6.1.4.1.674.10892.2.4.1.1.13
# TYPE drsWattsReading gauge
drsWattsReading{drsChassisIndex="1",drsWattsReading="0x333033382E303030"} 1
```
When I add an override for type: DisplayString I get

```
drsWattsReading{drsChassisIndex="1",drsWattsReading="3039.000"} 1
```
Then if I regex_extracts the value like so:

```
    overrides:
      drsWattsReading:
        type: DisplayString
        regex_extracts:
          Value:
            - regex: '(.*)'
              value: '$1'
```
I get this metric:
```
drsWattsReadingValue{drsChassisIndex="1"} 3056
```
Which is pretty much what I want.

I tried going directly to "type: Float" but I always get a value of 0. Maybe that isn't intended for my float-as-OctetString case?
```
drsWattsReading{drsChassisIndex="1"} 0
```

**Comment by brian-brazil** [comment]
That's more a usage question, which is best handled on the mailing lists.

**Comment by acmodeu** [comment]
Trying to override **mtxrFirmwareVersion** from Mikrotik.mib, using docker SNMP Exporter Config Generator. After some digging I found the [same problem with resolution](https://stackoverflow.com/questions/48994639/grafrana-use-label-as-value). But my generator fails with the following error 
> FATA[0000] Error parsing yml config: yaml: line 30: did not find expected key  source="main.go:44"

Here is my generator.yml file:
```
  mikrotik_private:  # The module name. You can have as many modules as you want.
    walk:       # List of OIDs to walk. Can also be SNMP object names or specific instances.
      - mtxrFirmwareVersion
      - hrProcessorLoad # CPU Load
      - hrSystemUptime # System Uptime
      - ifInOctets # Incoming Traffic on the interface
      - ifOutOctets # Outgoing Traffic on the interface 

      - mtxrSerialNumber

      overrides:
           mtxrFirmwareVersion:
                 regex_extracts:
                 '': 
                 - regex: '(.*)'
                 value: '$1'



    version: 3  # SNMP version to use. Defaults to 2.
                # 1 will use GETNEXT, 2 and 3 use GETBULK.
    max_repetitions: 25  # How many objects to request with GET/GETBULK, defaults to 25.
                         # May need to be reduced for buggy devices.
    retries: 3   # How many times to retry a failed request, defaults to 3.
    timeout: 10s # Timeout for each walk, defaults to 10s.

    auth:
      # Community string is used with SNMP v1 and v2. Defaults to "public".
      community: snmp

      # v3 has different and more complex settings.
      # Which are required depends on the security_level.
      # The equivalent options on NetSNMP commands like snmpbulkwalk
      # and snmpget are also listed. See snmpcmd(1).
      username: snmp # Required, no default. -u option to NetSNMP.
      security_level: authNoPriv  # Defaults to noAuthNoPriv. -l option to NetSNMP.
                                    # Can be noAuthNoPriv, authNoPriv or authPriv.
      password: snmp  # Has no default. Also known as authKey, -A option to NetSNMP.
                      # Required if security_level is authNoPriv or authPriv.
      auth_protocol: MD5  # MD5 or SHA, defaults to SHA. -a option to NetSNMP.
                          # Used if security_level is authNoPriv or authPriv.
#      priv_protocol: DES  # DES or AES, defaults to DES. -x option to NetSNMP.
                          # Used if security_level is authPriv.
#      priv_password: # Has no default. Also known as privKey, -X option to NetSNMP.
                               # Required if security_level is authPriv.
#      context_name: context # Has no default. -n option to NetSNMP.
                            # Required if context is configured on the device.
```
