### ISSUE TITLE
Can't see metrics / data in Grafana

### ISSUE THREAD

**Issue by LordGorgul** [prometheus/snmp_exporter#195]
Hi,

I'm scraping data from my Brocade SAN switches. I generated a snmp.yml file using the generator and some MIBs.
Using the command  `curl localhost:9116/snmp?target=XXXX` I get the error `error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error walking target XXXX: Request timeout (after 3 retries)`
This only happens when I use the snmp.yml I generated with the Brocade MIBs, when I use default this works just fine. Also the error only occurs when I try to get the metrics with said command but not when I let the snmp_exporter run on his own.

Now I don't know if any data is being collected at all but when I make a Grafana graph with the query {job="san-switches"} the only data I get is scrape_duration_seconds, scrape_samples_post_metric_relabeling, scrape_samples_post_metric_relabeling and up.

Also when I used the default module I could see that data like ifSpeed is being collected but it never showed up in Grafana.

snmp.yml:
```YAML
brocade:
 version: 1
  auth:
    community: XXXX
  walk:
  - 1.3.6.1.4.1.1588.2.1.1.1.6
  metrics:
  - name: swFCPortCapacity
    oid: 1.3.6.1.4.1.1588.2.1.1.1.6.1
    type: gauge
```

generator.yml:
```YAML
modules:
# If ifDesc is unique.
  default:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        new_index: ifDescr
# If ifName is unique.
  default_ifname:
    walk: [sysUpTime, interfaces, ifXTable]
    lookups:
      - old_index: ifIndex
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        new_index: 1.3.6.1.2.1.31.1.1.1.1 # ifName
# If only ifIndex is unique.
  default_ifindex:
    walk: [sysUpTime, interfaces, ifXTable]

  brocade:
    walk: [swFCport]
```

prometheus.yml:
```YAML
  - job_name: 'san-switches'
    static_configs:
      - targets:
       - 'XXXX'
       - 'XXXX'
    metrics_path: /snmp
    params:
      module: [brocade]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter.
```
