### ISSUE TITLE
The configuration generated with latest generator doesn't work

### ISSUE THREAD

**Issue by ninoabbate** [prometheus/snmp_exporter#206]
Hi guys,
I've updated the generator container (https://github.com/ninoabbate/docker-secg) to the current master branch, I saw that you have introduced the field `help` and this is a great addition, but with current release (0.4.0) this doesn't work because it isn't an expected field: 

```
[....SNIP...]
+ docker run --name=snmp-exporter f4fd5814e522
time="2017-07-25T15:12:44Z" level=info msg="Starting snmp exporter (version=0.4.0, branch=master, revision=0a00acbf61971015b6475441d741ce59ad2ba26d)" source="main.go:99" 
time="2017-07-25T15:12:44Z" level=info msg="Build context (go=go1.8.3, user=root@ea8b44ce07e1, date=20170606-13:39:44)" source="main.go:100" 
time="2017-07-25T15:12:44Z" level=fatal msg="Error parsing config file: unknown fields in module: help" source="main.go:105" 
```

Could you please release a new version (which includes this great addition) or provide documentation of how it can be built the binary (like you did for the generator)? 
Thanks!

**Comment by brian-brazil** [comment]
We're in the middle of making a number of improvements to the exporter, so things will be out of sync for a bit. I'd suggest building from the v0.4.0 branch.

**Comment by ninoabbate** [comment]
It seems there isn't a v0.4.0 branch available.

**Comment by brian-brazil** [comment]
I meant tag, not branch.

**Comment by ninoabbate** [comment]
Thanks, I found it!

**Comment by ninoabbate** [comment]
Just a followup on this, I've rebuilt the generator container starting from tag v0.4.0 but the tag`help` is still added, though without the comments:
```
paloalto_fw:
  walk:
  - 1.3.6.1.2.1.1.3
  - 1.3.6.1.2.1.2
  - 1.3.6.1.2.1.25.1
  - 1.3.6.1.2.1.25.2
  - 1.3.6.1.2.1.25.3
  - 1.3.6.1.4.1.25461.2.1.2.1
  - 1.3.6.1.4.1.25461.2.1.2.3
  - 1.3.6.1.4.1.25461.2.1.2.5
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
    help: ""
  - name: ifNumber
    oid: 1.3.6.1.2.1.2.1
    type: gauge
    help: ""
  - name: ifIndex
    oid: 1.3.6.1.2.1.2.2.1.1
    type: gauge
    help: ""
    indexes:
    - labelname: ifIndex
      type: gauge
  [....SNIP....]
```

This is how I run the generator:
```
$ docker run --rm -v "$PWD/mibs:/root/.snmp/mibs" \
> -v "$PWD/generator.yml:/snmp_exporter/generator/generator.yml" \
> -v "$PWD/snmp.yml:/snmp_exporter/generator/snmp.yml" aabbate/secg:v0.4.0
time="2017-07-26T14:39:06Z" level=info msg="Loading MIBs from $HOME/.snmp/mibs:/usr/share/snmp/mibs" source="net_snmp.go:83"
time="2017-07-26T14:39:06Z" level=warning msg="NetSNMP reported 5 parse errors" source="main.go:78"
time="2017-07-26T14:39:06Z" level=info msg="Generating config for module paloalto_fw" source="main.go:29"
time="2017-07-26T14:39:06Z" level=info msg="Generated 152 metrics for module paloalto_fw" source="main.go:36"
time="2017-07-26T14:39:06Z" level=info msg="Config written to snmp.yml" source="main.go:58"
```

you can take a look at the code here: https://github.com/ninoabbate/docker-secg
