### ISSUE TITLE
Generator masks community with "<secret>"

### ISSUE THREAD

**Issue by andrewd-sterling** [prometheus/snmp_exporter#219]
Current master of the generator produces `community: <secret>` rather than actual community.

### Host operating system: output of `uname -a`
CentOS Linux release 7.3.1611 (Core)
3.10.0-514.26.2.el7.x86_64
net-snmp-devel-5.7.2-24.el7_3.2.x86_64

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.5.0 (branch: master, revision: 4a6cefde688765abba45f8110c219e8e512da3f1)
  build user:       root@localhost
  build date:       20170815-23:37:12
  go version:       go1.8.3

### generator.yml:
```
modules:
  default:
    walk:
      - sysORTable
      - ifTable
      - ifXTable
      - systemStats
      - hrStorage
    version: 2
    auth:
      community: redacted
    lookups:
      - old_index: ifIndex
        new_index: ifDescr
      - old_index: hrStorageIndex
        new_index: hrStorageDescr
```
### What did you do that produced an error?
./generator generate
with the provided yaml.

### What did you expect to see?
Same community as in generator.yml

### What did you see instead?
```
  auth:
    community: <secret>
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
```
