### ISSUE TITLE
Support generating multi-index lookups

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#227]
Some OIDs have multiple index values that need to be used to perform lookups.  This is supported by the exporter's config, but not the generator's config.

Example:

```yaml
servertech_sentry3:
  walk:
  - 1.3.6.1.4.1.1718.3.2.2.1 # infeedEntry
  metrics:
  - name: infeedStatus
    oid: 1.3.6.1.4.1.1718.3.2.2.1.5
    type: gauge
    indexes:
    - labelname: towerIndex
      type: gauge
    - labelname: infeedIndex
      type: gauge
    lookups:
    - labels: [towerIndex, infeedIndex]
      labelname: infeedName
      oid: 1.3.6.1.4.1.1718.3.2.2.1.3
      type: DisplayString
```

**Comment by SuperQ** [comment]
Another example from Aruba WLSX-WLAN-MIB:
```yaml
aruba_wlan:
  walk:
  - 1.3.6.1.4.1.14823.2.2.1.5.2.1.7.1 # wlsxWlanAPBssidEntry
  metrics:
  - name: wlanAPBssidChannel
    oid: 1.3.6.1.4.1.14823.2.2.1.5.2.1.7.1.8
    type: gauge
    indexes:
    - labelname: wlanAPMacAddress
      type: PhysAddress48
    - labelname: wlanAPRadioNumber
      type: gauge
    - labelname: wlanAPBSSID
      type: PhysAddress48
    lookups:
    - labels: [wlanAPMacAddress, wlanAPRadioNumber, wlanAPBSSID]
      labelname: wlanAPBSSID
      oid: 1.3.6.1.4.1.14823.2.2.1.5.2.1.7.1.2
      type: DisplayString
```

**Comment by viq** [comment]
And here's an example with juniper:
```yaml
juniper_cpu:
  walk:
  - 1.3.6.1.4.1.2636.3.1.13.1
  metrics:
  - name: jnxOperatingCPU
    oid: 1.3.6.1.4.1.2636.3.1.13.1.8
    type: gauge
    help: The CPU utilization in percentage of this subject - 1.3.6.1.4.1.2636.3.1.13.1.8
    indexes:
    - labelname: jnxOperatingContentsIndex
      type: gauge
    - labelname: jnxOperatingL1Index
      type: gauge
    - labelname: jnxOperatingL2Index
      type: gauge
    - labelname: jnxOperatingL3Index
      type: gauge
    lookups:
    - labels: [jnxOperatingContentsIndex, jnxOperatingL1Index, jnxOperatingL2Index, jnxOperatingL3Index]
      labelname: jnxOperatingDescr
      oid: 1.3.6.1.4.1.2636.3.1.13.1.5
      type: DisplayString
```
resulting in output like `jnxOperatingCPU{jnxOperatingContentsIndex="9",jnxOperatingDescr="Routing Engine 0",jnxOperatingL1Index="1",jnxOperatingL2Index="0",jnxOperatingL3Index="0"} 22`

**Comment by SuperQ** [comment]
I have been thinking about this for the generator syntax:

```yaml
lookups:
- oid: jnxOperatingDescr # The lookup OID. Could also be the numeric OID.
  indexes: # The indexes used for matching.
  - jnxOperatingContentsIndex
  - jnxOperatingL1Index
  - jnxOperatingL2Index
  - jnxOperatingL3Index
  label: jnxOperatingDescr # Destination label name.
  drop_label: foo # Optional, remove this label from the destination metric.
```

**Comment by brian-brazil** [comment]
This bug is just about multi-label, and that's the obvious syntax. Old labels would have to be dropped by default, as they are now.

**Comment by SuperQ** [comment]
@brian-brazil Yup, @stuartnelson3 was interested in this issue since he has some multi-index stuff that needs lookups.

**Comment by jcollie** [comment]
If the automatic dropping of labels remains the default, I would appreciate a way to globally change that default in the configuration file rather than having to do something for every lookup.

**Comment by brian-brazil** [comment]
It would be incorrect to enable to blindly for every lookup as that would lead to extraneous labels. It is only something to be enabled on a case by case basis.

The first step is reworking how the current label dropping works. Using the name of the new label as the old label in snmp.yml is a bit ugly, a more explicit deletion would be clearer and will be required for multi-index.

**Comment by dndericco** [comment]
Adding an example from Ruckus at the suggestion of @SuperQ:

```
ruckus_smartzone:
  walk:
  - 1.3.6.1.4.1.25053.1.8.1.1.1.1.3.1
  metrics:
  - name: ruckusCtrlZoneNumApConnected
    oid: 1.3.6.1.4.1.25053.1.8.1.1.1.1.3.1.9
    type: gauge
    help: Number of AP in the zone that are currently connected - 1.3.6.1.4.1.25053.1.8.1.1.1.1.3.1.9
    indexes:
    - labelname: ruckusCtrlZoneDomainId
      type: OctetString
      fixed_size: 16
    - labelname: ruckusCtrlZoneId
      type: OctetString
      fixed_size: 16
    lookups:
    - labels: [ruckusCtrlZoneDomainId, ruckusCtrlZoneId]
      labelname: ruckusCtrlZoneName
      oid: 1.3.6.1.4.1.25053.1.8.1.1.1.1.3.1.3
      type: DisplayString
```

Example of resulting output: `ruckusCtrlZoneNumApConnected{ruckusCtrlZoneDomainId="0xE618759F671D489998A25564C5C60205",ruckusCtrlZoneId="0xE5F51E85250741ECBF76DEDCC23C7CA9",ruckusCtrlZoneName="Primary Zone"} 33`
