### ISSUE TITLE
Adding multiple labels fails

### ISSUE THREAD

**Issue by taktv6** [prometheus/snmp_exporter#23]
Hi there,

I've tried to run the following configuration:
```
default:
  walk:
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
  metrics:
    - name: ifMtu
      oid: 1.3.6.1.2.1.2.2.1.4
      indexes:
        - labelname: ifDescr
          type: Integer32
        - labelname: ifAlias
          type: Integer32
      lookups:
        - labels: [ifDescr]
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [ifAlias]
          labelname: ifAlias
          oid: 1.3.6.1.2.1.31.1.1.1.18
```

I want to have two labels on the variable.
However, ifAlias stays empty.

Is that a bug or is my config wrong?

Thanks
Oliver

**Comment by taktv6** [comment]
After studying the code I found out what exactly the idea is.
The index is used to identify the particular interface (by interface id).
This is being referenced in the lookups.

Following example solves my problem:
```
default:
  walk:
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
  metrics:
    - name: ifNumber
      oid: 1.3.6.1.2.1.2.1
    - name: ifMtu
      oid: 1.3.6.1.2.1.2.2.1.4
      indexes:
        - labelname: ifDescr
          type: Integer32
      lookups:
        - labels: [ifDescr]
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
        - labels: [ifDescr]
          labelname: ifAlias
          oid: 1.3.6.1.2.1.31.1.1.1.18
```
