### ISSUE TITLE
generator - error cannot find oid

### ISSUE THREAD

**Issue by zarkoc** [prometheus/snmp_exporter#235]
Hi all,

I got an issue when adding an OID to generator.
The error is generated when running ./generator generate.

Error is:
**FATA[0002] Cannot find oid 'iso.3.6.1.4.1.14823.2.3.3.1.2.1.1.1.64.227.214.204.24.32' to walk  source="tree.go:143"**

But when I do a manual walk with snmpwalk everything is ok.

snmpwalk -v 2c -c xxxxx 192.168.1.1 .1.3.6.1.4.1.14823.2.3.3.1.2.1.1.2
iso.3.6.1.4.1.14823.2.3.3.1.2.1.1.2.64.227.214.204.24.32 = STRING: "AP-1-1"

The generator.yml looks like:

  aruba:
    auth:
      community: 'xxxxx'
    walk: [sysUpTime, sysName, sysLocation, interfaces, ifXTable, iso.3.6.1.4.1.14823.2.3.3.1.2.1.1.1.64.227.214.204.24.32]

When I was doing the testing at the beginning I wanted to do walk from iso.3.6.1.4.1.14823.2.3.3.1.2. but the error is the same, and everything again worked with snmpwalk.

Thanks,
Zarko

**Comment by SuperQ** [comment]
I was able to generate an Aruba config with this generator.yml.

```yaml
modules:
  aruba:
          walk: [1.3.6.1.4.1.14823.2.3.3.1.2]
```

The metric snmp.yml that you're looking for seems reasonable as well.

```yaml
... 
 metrics:
  - name: aiAPMACAddress
    oid: 1.3.6.1.4.1.14823.2.3.3.1.2.1.1.1
    type: PhysAddress48
    help: Access Point MAC Address - 1.3.6.1.4.1.14823.2.3.3.1.2.1.1.1
    indexes:
    - labelname: aiAPMACAddress
      type: PhysAddress48
```

Can you attach the contents of the generated snmp.yml, without auth strings of course?
