### ISSUE TITLE
SNMP V3 context name requirement in Prometheus

### ISSUE THREAD

**Issue by Ahmed-Tariq** [prometheus/snmp_exporter#239]
Hi everyone, 
I'm using prometheus to get the SNMP walk on Juniper device on which I have configured "context". Using a command line 
`snmpget -v3 -n DATAPLANE-VPN-CONTEXT -l authPriv -a sha -A xxxxx -x des -X xxxxx -u User x.x.x.x .1.3.6.1.2.1.1.2.0`
i can fetch the values of oid and also do a walk using above mentioned command. 
I'm not able to fetch anything using Prometheus. My question is do i need to define similar parameter (context) in yml file i set up for prometheus jobs.? 
 my current files look something like this :
# my snmp.yml file
```
Juniper:
  version: 3
  auth:
    username: xxxxx
    password: xxxxx
    auth_protocol: SHA
    priv_protocol: DES
    security_level: authPriv
    priv_password: xxxxx
  walk:
  - 1.3.6.1.2.1.1
  - 1.3.6.1.2.1.2.2 
  metrics:
- name: sysUpTime
  oid: 1.3.6.1.2.1.25.1.1.0
  type: counter
- name: sysDescr
  oid: 1.3.6.1.2.1.1.1.0
  type: DisplayString
  lookups:
  - labels:
    labelname: sysName
    oid: 1.3.6.1.2.1.1.5.0
    type: DisplayString
  - labels:
    labelname: sysLocation
    oid: 1.3.6.1.2.1.1.6.0
    type: DisplayString
  - labels:
    labelname: sysContact
    oid: 1.3.6.1.2.1.1.4.0
    type: DisplayString
```
# prometheus.yml looks something like this:
```
# Juniper
- job_name: 'Juniper'
  scrape_interval: 120s
  scrape_timeout: 120s
  file_sd_configs:
      - files :
        - /etc/prometheus/targetJuniper.yml
  metrics_path: /snmp
  params:
    module: [Juniper] #which OID's we will be querying in
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmpexporter:9116
```
