### ISSUE TITLE
Metrics are not generated by snmp-exporter 

### ISSUE THREAD

**Issue by maplewf** [prometheus/snmp_exporter#241]
Hello,

I tried to use snmp-exporter to import ipsec tunnel status from my device to prometheus database, I created MIB, and use it to generate snmp.yml as required by generator. Everything works well through snmpwalk/snmpbulkget until I checked the prometheus database, there is no corresponding metrics generated !!! 

### what I observed on prometheus
```
up{instance="10.12.0.12",job="snmp_ipsec@xxx"} = 0

```
And there is no my metrics generated.

what's wrong with my configuration? I paste my configuration as below: 

### Host operating system: output of `uname -a`
> 4.4.0-87-generic
### snmp_exporter version: output of `snmp_exporter -version`

> snmp_exporter, version 0.6.0 (branch: HEAD, revision: 4388d6815791d6d616098f899110c9dca354028c)
  build user:       root@fd9cde4d0842
  build date:       20170822-11:04:46
  go version:       go1.8.3

### snmpwalk/snmpbulkget output
> snmpwalk -v 2c -c public 10.12.0.12 1.3.6.1.4.1.8888
iso.3.6.1.4.1.8888.1.1 = INTEGER: 4
iso.3.6.1.4.1.8888.1.2.1.1.1.49 = INTEGER: 1
iso.3.6.1.4.1.8888.1.2.1.1.1.50 = INTEGER: 2
iso.3.6.1.4.1.8888.1.2.1.1.1.51 = INTEGER: 3
iso.3.6.1.4.1.8888.1.2.1.1.1.52 = INTEGER: 4
iso.3.6.1.4.1.8888.1.2.1.2.1.49 = STRING: "10.12.0.12"
iso.3.6.1.4.1.8888.1.2.1.2.1.50 = STRING: "10.12.0.12"
iso.3.6.1.4.1.8888.1.2.1.2.1.51 = STRING: "192.168.1.254"
iso.3.6.1.4.1.8888.1.2.1.2.1.52 = STRING: "192.168.1.254"
iso.3.6.1.4.1.8888.1.2.1.3.1.49 = STRING: "10.12.0.10"
iso.3.6.1.4.1.8888.1.2.1.3.1.50 = STRING: "10.12.0.10"
iso.3.6.1.4.1.8888.1.2.1.3.1.51 = STRING: "192.168.1.253"
iso.3.6.1.4.1.8888.1.2.1.3.1.52 = STRING: "192.168.1.253"
iso.3.6.1.4.1.8888.1.2.1.4.1.49 = STRING: "test"
iso.3.6.1.4.1.8888.1.2.1.4.1.50 = STRING: "test"
iso.3.6.1.4.1.8888.1.2.1.4.1.51 = STRING: "test2"
iso.3.6.1.4.1.8888.1.2.1.4.1.52 = STRING: "test2"
iso.3.6.1.4.1.8888.1.2.1.5.1.49 = INTEGER: 0
iso.3.6.1.4.1.8888.1.2.1.5.1.50 = INTEGER: 1
iso.3.6.1.4.1.8888.1.2.1.5.1.51 = INTEGER: 0
iso.3.6.1.4.1.8888.1.2.1.5.1.52 = INTEGER: 1
iso.3.6.1.4.1.8888.1.2.1.6.1.49 = INTEGER: 0
iso.3.6.1.4.1.8888.1.2.1.6.1.50 = INTEGER: 0
iso.3.6.1.4.1.8888.1.2.1.6.1.51 = INTEGER: 0
iso.3.6.1.4.1.8888.1.2.1.6.1.52 = INTEGER: 0

> snmpbulkget -v 2c -c public 10.12.0.12 1.3.6.1.4.1.8888
iso.3.6.1.4.1.8888.1.1 = INTEGER: 4
iso.3.6.1.4.1.8888.1.2.1.1.1.49 = INTEGER: 1
iso.3.6.1.4.1.8888.1.2.1.1.1.50 = INTEGER: 2
iso.3.6.1.4.1.8888.1.2.1.1.1.51 = INTEGER: 3
iso.3.6.1.4.1.8888.1.2.1.1.1.52 = INTEGER: 4
iso.3.6.1.4.1.8888.1.2.1.2.1.49 = STRING: "10.12.0.12"
iso.3.6.1.4.1.8888.1.2.1.2.1.50 = STRING: "10.12.0.12"
iso.3.6.1.4.1.8888.1.2.1.2.1.51 = STRING: "192.168.1.254"
iso.3.6.1.4.1.8888.1.2.1.2.1.52 = STRING: "192.168.1.254"
iso.3.6.1.4.1.8888.1.2.1.3.1.49 = STRING: "10.12.0.10"

### snmp.yml configuraton and MIB file

```
ipsec:
  walk:
  - 1.3.6.1.4.1.8888
  metrics:
  - name: asIpsecTunnelEntries
    oid: 1.3.6.1.4.1.8888.1.1
    type: gauge
    help: The number of rows in the asIpsecTunnelTable - 1.3.6.1.4.1.8888.1.1
  - name: asIpsecTunnelIndex
    oid: 1.3.6.1.4.1.8888.1.2.1.1
    type: gauge
    help: This is the index of ipsec tunnel entry in the table - 1.3.6.1.4.1.8888.1.2.1.1
    indexes:
    - labelname: asIpsecTunnelIndex
      type: gauge
  - name: asIpsecTunnelLocalAddr
    oid: 1.3.6.1.4.1.8888.1.2.1.2
    type: DisplayString
    help: This is the local address of ipsec tunnel entry in the table - 1.3.6.1.4.1.8888.1.2.1.2
    indexes:
    - labelname: asIpsecTunnelIndex
      type: gauge
  - name: asIpsecTunnelRemoteAddr
    oid: 1.3.6.1.4.1.8888.1.2.1.3
    type: DisplayString
    help: This is the remote address of ipsec tunnel entry in the table - 1.3.6.1.4.1.8888.1.2.1.3
    indexes:
    - labelname: asIpsecTunnelIndex
      type: gauge
  - name: asIpsecTunnelDescr
    oid: 1.3.6.1.4.1.8888.1.2.1.4
    type: DisplayString
    help: This is the description of ipsec tunnel entry in the table - 1.3.6.1.4.1.8888.1.2.1.4
    indexes:
    - labelname: asIpsecTunnelIndex
      type: gauge
  - name: asIpsecTunnelNo
    oid: 1.3.6.1.4.1.8888.1.2.1.5
    type: gauge
    help: This is the number of ipsec tunnel entry in the table - 1.3.6.1.4.1.8888.1.2.1.5
    indexes:
    - labelname: asIpsecTunnelIndex
      type: gauge
  - name: asIpsecTunnelStatus
    oid: 1.3.6.1.4.1.8888.1.2.1.6
    type: gauge
    help: This is the status of ipsec tunnel entry in the table - 1.3.6.1.4.1.8888.1.2.1.6
    indexes:
    - labelname: asIpsecTunnelIndex
      type: gauge
```
[VYOS-IPSEC-MIB.txt](https://github.com/prometheus/snmp_exporter/files/1433755/VYOS-IPSEC-MIB.txt)
### prometheus configuration

```
scrape_configs:
  - job_name: 'snmp_ipsec@xxx'
    static_configs:
      - targets:
        - 10.12.0.12
    metrics_path: /snmp
    params:
      module: [ipsec]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9117
```

### debug log
```
/usr/bin/snmp_exporter --log.level="debug" --web.listen-address=":9117" --config.file=snmp.yml
INFO[0000] Starting snmp exporter (version=0.6.0, branch=HEAD, revision=4388d6815791d6d616098f899110c9dca354028c)  source="main.go:125"
INFO[0000] Build context (go=go1.8.3, user=root@fd9cde4d0842, date=20170822-11:04:46)  source="main.go:126"
INFO[0000] Listening on :9117                            source="main.go:205"
DEBU[0008] Scraping target '10.12.0.12' with module 'ipsec'  source="main.go:73"
DEBU[0008] Walking target "10.12.0.12" subtree "1.3.6.1.4.1.8888"  source="collector.go:71"
DEBU[0008] Walk of target "10.12.0.12" subtree "1.3.6.1.4.1.8888" completed in 7.365473ms  source="collector.go:81"
DEBU[0008] Scrape of target '10.12.0.12' with module 'ipsec' took 0.010373 seconds  source="main.go:84"
DEBU[0023] Scraping target '10.12.0.12' with module 'ipsec'  source="main.go:73"
DEBU[0023] Walking target "10.12.0.12" subtree "1.3.6.1.4.1.8888"  source="collector.go:71"
DEBU[0023] Walk of target "10.12.0.12" subtree "1.3.6.1.4.1.8888" completed in 11.158895ms  source="collector.go:81"
DEBU[0023] Scrape of target '10.12.0.12' with module 'ipsec' took 0.015109 seconds  source="main.go:84"
```
I actually tried other MIBs like if-mib, it works well, but why self-defined mib can't be generated as metrics in prometheus through snmp-exporter?

thanks in advance

best regards.
