### ISSUE TITLE
How to properly describe DiplayString which is actually a number?

### ISSUE THREAD

**Issue by do11** [prometheus/snmp_exporter#250]
I have in vendor MIB description like this
```
curReadStatistic OBJECT-TYPE
    SYNTAX      DisplayString
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION "Current Read Statistic MB/S"
    ::= { hostSideParams 9 }
```
generator produced such config:
```
  - name: curReadStatistic
    oid: 1.3.6.1.4.1.1714.1.1.1.4.9
    type: DisplayString
    help: Current Read Statistic MB/S - 1.3.6.1.4.1.1714.1.1.1.4.9
```
`snmp_exporter` provides such output:
```
# HELP curReadStatistic Current Read Statistic MB/S - 1.3.6.1.4.1.1714.1.1.1.4.9
# TYPE curReadStatistic gauge
curReadStatistic{curReadStatistic="0"} 1
```
Which seems wrong, as value is always `1` even when `curReadStatistic` changes, `snmp_exporter` outputs, for example, `curReadStatistic{curReadStatistic="52"} 1` which is different metric but same `1` value.

How to configure `snmp_exporter` so it understands that this oid is actually number into string?

**Comment by SuperQ** [comment]
Yea, it looks like the vendor messed up their data.

You can use the `regex_extracts` feature in the generator to override the handling.

See the example in https://github.com/prometheus/snmp_exporter/blob/master/generator/FORMAT.md

**Comment by do11** [comment]
Thanks much! After I changed config to this it's worked:
```
  - name: curReadStatistic
    oid: 1.3.6.1.4.1.1714.1.1.1.4.9
    type: DisplayString
    help: Current Read Statistic MB/S - 1.3.6.1.4.1.1714.1.1.1.4.9
    regex_extracts:
      Temp:
        - regex: '(.*)'
          value: '$1'
```
This is a bit complicated and adds Temp suffix. Could this be avoided, maybe in next release?
