### ISSUE TITLE
Bug Report: Get timeout after disabled SNMP v1 on Cisco-Switch

### ISSUE THREAD

**Issue by Mortinke** [prometheus/snmp_exporter#266]
### Environment:
Host operating system:
```
Linux myhost 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

snmp_exporter version:
```
# ./snmp_exporter --version
snmp_exporter, version 0.8.0 (branch: HEAD, revision: 17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)
build user: root@57f813d2791a
build date: 20171120-12:36:57
go version: go1.9.2
```

Used devices / snmpwald OID:
used devices:
```
WS-C3850-48P (Cisco Catalyst 3850)
Version 03.06.07E
```

using provided OIDs from default snmp.yml "apcups"
```
apcups:
  version: 2
  max_repetitions: 25
  retries: 1
  timeout: 30s
  auth:
    community: ****
  walk:
  - 1.3.6.1.2.1.1.3
  - 1.3.6.1.2.1.2
  - 1.3.6.1.4.1.318.1.1.1.12
  - 1.3.6.1.4.1.318.1.1.1.2
  - 1.3.6.1.4.1.318.1.1.1.3
  - 1.3.6.1.4.1.318.1.1.1.4
  - 1.3.6.1.4.1.318.1.1.1.7.2
  - 1.3.6.1.4.1.318.1.1.1.8.1
  - 1.3.6.1.4.1.318.1.1.10.2.3.2
  metrics:
	...
```

#### What did you do that produced an error?

Firstly, I run the snmp_exporter with snmp v1 + v2 activated on target switch and got all information:
```
curl "http://myhost:9116/snmp?target=myswitch&module=apcups"
```
Here you can find the debug output for this run:
```
# ./snmp_exporter --log.level="debug" --config.file="snmp.yml"
INFO[0000] Starting snmp exporter (version=0.8.0, branch=HEAD, revision=17cefcaf7010106861ce0faa2a9ec9e39b7c2b4b)  source="main.go:125"
INFO[0000] Build context (go=go1.9.2, user=root@57f813d2791a, date=20171120-12:36:57)  source="main.go:126"
INFO[0000] Listening on :9116                            source="main.go:205"
DEBU[0003] Scraping target 'myswitch' with module 'apcups'  source="main.go:73"
DEBU[0003] Walking target "myswitch" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
DEBU[0003] Walk of target "myswitch" subtree "1.3.6.1.2.1.1.3" completed in 8.297073ms  source="collector.go:81"
DEBU[0003] Walking target "myswitch" subtree "1.3.6.1.2.1.2"  source="collector.go:71"
DEBU[0012] Walk of target "myswitch" subtree "1.3.6.1.2.1.2" completed in 8.985154064s  source="collector.go:81"
DEBU[0012] Walking target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.12"  source="collector.go:71"
DEBU[0014] Walk of target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.12" completed in 1.761167659s  source="collector.go:81"
DEBU[0014] Walking target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.2"  source="collector.go:71"
DEBU[0014] Walk of target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.2" completed in 258.126994ms  source="collector.go:81"
DEBU[0014] Walking target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.3"  source="collector.go:71"
DEBU[0015] Walk of target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.3" completed in 208.890762ms  source="collector.go:81"
DEBU[0015] Walking target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.4"  source="collector.go:71"
DEBU[0015] Walk of target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.4" completed in 200.725047ms  source="collector.go:81"
DEBU[0015] Walking target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.7.2"  source="collector.go:71"
DEBU[0015] Walk of target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.7.2" completed in 210.340754ms  source="collector.go:81"
DEBU[0015] Walking target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.8.1"  source="collector.go:71"
DEBU[0015] Walk of target "myswitch" subtree "1.3.6.1.4.1.318.1.1.1.8.1" completed in 208.660179ms  source="collector.go:81"
DEBU[0015] Walking target "myswitch" subtree "1.3.6.1.4.1.318.1.1.10.2.3.2"  source="collector.go:71"
DEBU[0017] Walk of target "myswitch" subtree "1.3.6.1.4.1.318.1.1.10.2.3.2" completed in 1.837394887s  source="collector.go:81"
DEBU[0017] Scrape of target 'myswitch' with module 'apcups' took 13.744268 seconds  source="main.go:84"
```
I also checked this with snmpgetnext:
```
snmpgetnext -v1 -c **** myswitch 1.3.6.1.2.1.1.3
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1544804639) 178 days, 19:07:26.39
```

Afterwards I disabled SNMP v1 and run this again with only snmp v2 activated on target switch:
```
curl "http://myhost:9116/snmp?target=myswitch&module=apcups"
An error has occurred during metrics gathering:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error walking target myswitch: Request timeout (after 1 retries)
```
Debug output:
```
DEBU[0158] Scraping target 'myswitch' with module 'apcups'  source="main.go:73"
DEBU[0158] Walking target "myswitch" subtree "1.3.6.1.2.1.1.3"  source="collector.go:71"
INFO[0188] Error scraping target myswitch: Error walking target myswitch: Request timeout (after 1 retries)  source="collector.go:126"
DEBU[0188] Scrape of target 'myswitch' with module 'apcups' took 30.000693 seconds  source="main.go:84"
```
Checked again with snmpgetnext. As expected, it doesn't wok with v1.
```
snmpgetnext -v1 -c **** myswitch 1.3.6.1.2.1.1.3
Timeout: No Response from myswitch.
```
However, with v2 it still work:
```
# snmpbulkget -v2c -c **** myswitch 1.3.6.1.2.1.1.3
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (1544926338) 178 days, 19:27:43.38
SNMPv2-MIB::sysContact.0 = STRING: ****
SNMPv2-MIB::sysName.0 = STRING: myswitch
SNMPv2-MIB::sysLocation.0 = STRING: ****
SNMPv2-MIB::sysServices.0 = INTEGER: 6
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORID.1 = OID: SNMPv2-SMI::enterprises.9.7.129
SNMPv2-MIB::sysORID.2 = OID: SNMPv2-SMI::enterprises.9.7.115
SNMPv2-MIB::sysORID.3 = OID: SNMPv2-SMI::enterprises.9.7.265
SNMPv2-MIB::sysORID.4 = OID: SNMPv2-SMI::enterprises.9.7.112
```

#### What did you expect to see?
The snmp_exporter use SNMP v2 and can fetch the metrics.

#### What did you see instead?
We get a timeout and can't fetch any metrics anymore. It seems to us that the snmp_exporter continues to use SNMP v1 instead of v2.

**Comment by brian-brazil** [comment]
This smells like an issue with the switch. What does tcpdump show?

**Comment by Mortinke** [comment]
The problem occures also with our HP switches:
```
HPE FF 5700-48G-4XG-2QSFP+ Switch
HPE Comware Software, Version 7.1.045, Release 2432P05, 
```

**Comment by brian-brazil** [comment]
What is the SNMP exporter sending, what is it getting back, and how does this differ from what snmpbulkwalk is doing.

Using the apcups module with a different type of device from a different manufacturer may not end well.

**Comment by Mortinke** [comment]
I can see that `snmpbulkget -v2c` use version v2c and we got a response.
With the `snmp_exporter` I can see that version-1 is used and we don't get a SNMP response. 

Could you tell me a little more about the modules and which we should use for these switches. 
We are only wonder that we don't get any information back.

**Comment by brian-brazil** [comment]
Are you sure you haven't specified `  version: 1` in your module? That's the only way GETNEXT should be used.

**Comment by Mortinke** [comment]
We use the default snmp.yml "apcups" module:
```
apcups:
  version: 2
  max_repetitions: 25
  retries: 1
  timeout: 30s
  auth:
    community: ****
  walk:
  - 1.3.6.1.2.1.1.3
  - 1.3.6.1.2.1.2
  - 1.3.6.1.4.1.318.1.1.1.12
  - 1.3.6.1.4.1.318.1.1.1.2
  - 1.3.6.1.4.1.318.1.1.1.3
  - 1.3.6.1.4.1.318.1.1.1.4
  - 1.3.6.1.4.1.318.1.1.1.7.2
  - 1.3.6.1.4.1.318.1.1.1.8.1
  - 1.3.6.1.4.1.318.1.1.10.2.3.2
  metrics:
	...
```

and start the exporter with this file:
```
# ./snmp_exporter --log.level="debug" --config.file="snmp.yml"
```

**Comment by brian-brazil** [comment]
Can you share the tcpdump output showing that it's using v1?

**Comment by Mortinke** [comment]
![snmp_exporter_v1_disabled pcap](https://user-images.githubusercontent.com/11607896/36313096-d3e4f57e-1330-11e8-9d32-f54c8d4eb1c6.png)

**Comment by Mortinke** [comment]
As additional information: we are currently also using check_mk for monitoring and there are no problems with disabled SNMP v1.  This is another indication that the problem isn't our switches (HP and Cisco switches).

**Comment by brian-brazil** [comment]
Can you confirm that you are using exactly the config from https://github.com/prometheus/snmp_exporter/issues/266#issuecomment-366244860 and the URL "http://myhost:9116/snmp?target=myswitch&module=apcups" in particular the module?

**Comment by Mortinke** [comment]
Yes, I can confirm these two points.
```
# cat prometheus-snmp-exporter/snmp_exporter-0.8.0.linux-amd64/snmp.yml | head -50
apcups:
  version: 2
  max_repetitions: 25
  retries: 1
  timeout: 30s
  auth:
    community: *******
  walk:
  - 1.3.6.1.2.1.1.3
  - 1.3.6.1.2.1.2
  - 1.3.6.1.4.1.318.1.1.1.12
  - 1.3.6.1.4.1.318.1.1.1.2
  - 1.3.6.1.4.1.318.1.1.1.3
  - 1.3.6.1.4.1.318.1.1.1.4
  - 1.3.6.1.4.1.318.1.1.1.7.2
  - 1.3.6.1.4.1.318.1.1.1.8.1
  - 1.3.6.1.4.1.318.1.1.10.2.3.2
  metrics:
  - name: sysUpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
```
