### ISSUE TITLE
Bug? in generator 

### ISSUE THREAD

**Issue by nicolas-gibelin** [prometheus/snmp_exporter#273]
### Infos
 - debian 9, manual install of prometheus
 - snmp_exporter 0.9.0, 0.8.0
 - In this issue, i use the `PowerNet-MIB`
 - generator from git : * master abb143a Release 0.9.0
 - go build : to compile the generator

```
generator.yml

  apcupssymmetrapx500:
    version: 1
    walk:
      - 1.3.6.1.4.1.318.1.1.1.9.3.3.1.16   # PhaseOutputPercentPower
```
Then

```
./generator generate
```
gives

```
snmp.yml

  - name: upsPhaseOutputPercentPower
    oid: 1.3.6.1.4.1.318.1.1.1.9.3.3.1.16
    type: gauge
    help: The percentage of the UPS power capacity in Watts at redundancy @ (n + x)
      presently being used on this output phase, or -1 if it's unsupported by this
      UPS. - 1.3.6.1.4.1.318.1.1.1.9.3.3.1.16
    indexes:
    - labelname: upsPhaseOutputPhaseTableIndex
      type: gauge
    - labelname: upsPhaseOutputPhaseIndex
      type: gauge
```
But the config does not work:

```
2 error(s) occurred:
* collected metric upsPhaseOutputPercentPower label:<name:"upsPhaseOutputPhaseIndex" value:"1" > label:<name:"upsPhaseOutputPhaseTableIndex" value:"1" > gauge:<value:40 >  was collected before with the same name and label values
* collected metric upsPhaseOutputPercentPower label:<name:"upsPhaseOutputPhaseIndex" value:"1" > label:<name:"upsPhaseOutputPhaseTableIndex" value:"1" > gauge:<value:42 >  was collected before with the same name and label values
```

After some tests, config (snmp.yml) must be (see the oid):

```
snmp.yml

  - name: upsPhaseOutputPercentPower
    oid: 1.3.6.1.4.1.318.1.1.1.9.3.3.1.16.1
    type: gauge
    help: The percentage of the UPS power capacity in Watts at redundancy @ (n + x)
      presently being used on this output phase, or -1 if it's unsupported by this
      UPS. - 1.3.6.1.4.1.318.1.1.1.9.3.3.1.16
    indexes:
    - labelname: upsPhaseOutputPhaseTableIndex
      type: gauge
    - labelname: upsPhaseOutputPhaseIndex
      type: gauge
```

And returns

```
upsPhaseOutputPercentPower{upsPhaseOutputPhaseIndex="1",upsPhaseOutputPhaseTableIndex="1"} 42
upsPhaseOutputPercentPower{upsPhaseOutputPhaseIndex="2",upsPhaseOutputPhaseTableIndex="1"} 42
upsPhaseOutputPercentPower{upsPhaseOutputPhaseIndex="3",upsPhaseOutputPhaseTableIndex="1"} 39
```

But 
  
```
generator.yml

  apcupssymmetrapx500:
    version: 1
    walk:
      - 1.3.6.1.4.1.318.1.1.1.9.3.3.1.16.1   # PhaseOutputPercentPower
```

Then

```
./generator generate
```

Gives

```
FATA[0000] Cannot find oid '1.3.6.1.4.1.318.1.1.1.9.3.3.1.16.1' to walk  source="tree.go:162"
```
