### ISSUE TITLE
Error with standard SNMP exporter on Ubiquiti Devices (Unifi/Airmax)

### ISSUE THREAD

**Issue by Cellebyte** [prometheus/snmp_exporter#313]
### Host operating system: 
Linux 4.9.0-6-amd64 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

### snmp_exporter version: 
snmp_exporter, version 0.11.0 (branch: HEAD, revision: e4591716c29459cb2a12b1bed129af519ad91d23)
  build user:       root@80735d30559d
  build date:       20180530-10:24:52
  go version:       go1.10.2

### What device/snmpwalk OID are you using?
Ubiquiti Airmax/Unifi

### If this is a new device, please link to the MIB(s).
Not new.
### What did you do that produced an error?
http://localhost:9116/snmp?module=ubiquiti_airmax&target=|hostname|
http://localhost:9116/snmp?module=ubiquiti_unifi&target=|hostname|
### What did you expect to see?
---
General Metrics
---
### What did you see instead?
---
An error has occurred during metrics gathering:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: Error getting target <hostname>: Request timeout (after 3 retries)
---

## Temporary Fix
Adding other SNMP versions to the snmp.yml.
```yaml
ubiquiti_airmax:
  version: 1 # <<<<
  walk:
  - 1.3.6.1.2.1.2
  - 1.3.6.1.2.1.31.1.1
  - 1.3.6.1.4.1.41112.1.4
# ....
```
```yaml
ubiquiti_unifi:
  version: 1 # <<<<
  walk:
  - 1.3.6.1.2.1.2
  - 1.3.6.1.2.1.31.1.1
  - 1.3.6.1.4.1.41112.1.4
# ....
```

Now it is working fine.
