### ISSUE TITLE
server returned HTTP status 400 Bad Request

### ISSUE THREAD

**Issue by Nurlan199206** [prometheus/snmp_exporter#314]
Hi everyone.

im trying to get traffic bandwidth from Cisco router interface, but error 400.

someone know how to fix that? 

my `snmp.yml`
```
cisco_custom:
  version: 2
  auth:
    community: 12345
  walk:
  - 1.3.6.1.2.1.2.2.1.10.33
  - 1.3.6.1.2.1.2.2.1.10.33
  metrics:
  - name: snmp_IfinOctets.32
    oid: 1.3.6.1.2.1.2.2.1.10.33
    type: gauge
```
prometheus.yml
```
  - job_name: snmp
    static_configs:
      - targets:
        - 172.27.22.254  # SNMP device.
    metrics_path: /snmp
    params:
#      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.27.1.54:9116
```

![snmp](https://user-images.githubusercontent.com/22808731/42553843-57229776-8504-11e8-9b48-fd839d72313b.PNG)
