### ISSUE TITLE
Config parser loads invalid metric names.

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#315]
The config parser needs to validate metric names against Prometheus [valid metric names](https://prometheus.io/docs/instrumenting/writing_exporters/#naming).

I don't remember if there's a function or not, but we could implement this with a basic regexp: `[a-zA-Z_]([a-zA-Z0-9_])*`

For example, this should fail:
```yaml
if_mib:
  walk:
  - 1.3.6.1.2.1.2
  get:
  - 1.3.6.1.2.1.1.3.0
  metrics:
  - name: sys.UpTime
    oid: 1.3.6.1.2.1.1.3
    type: gauge
```
