### ISSUE TITLE
Impossible to add multiple labels

### ISSUE THREAD

**Issue by axinojolais** [prometheus/snmp_exporter#36]
With the current code, it's impossible to add multiple labels, at least if they're both Integer32 (my use case is to get both interface name ("ifDescr") and interface description ("ifAlias"))

I worked around that by commenting "suboid = suboid[1:]"  in collector.py line 64. I must admit I'm not 100% sure why this is here for, so no PR for this.

Thanks !

**Comment by brian-brazil** [comment]
Multiple labels is known to work, see bsnAPIfDBNoisePower in the example config file for example.

What exactly are you trying to do?

**Comment by axinojolais** [comment]
Yeah I just noticed that the tests now fail, so I have no idea what I'm doing. I'm trying to add an "ifAlias" label. I'm trying to do it this way which is probably wrong :
```
   - name: ifMtu
      oid: 1.3.6.1.2.1.2.2.1.4
      indexes:
        - labelname: ifAlias
          type: Integer32
        - labelname: ifDescr
          type: Integer32
      lookups:
        - labels: [ifAlias]
          labelname: ifAlias
          oid: 1.3.6.1.2.1.31.1.1.1.18
        - labels: [ifDescr]
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
```

Thanks for your help

**Comment by brian-brazil** [comment]
The ifTable only has one index, so you want one entry in `indexes` and two in `lookups` referring to it.

**Comment by axinojolais** [comment]
Heh. For future travelers, that works :
```
    - name: ifMtu
      oid: 1.3.6.1.2.1.2.2.1.4
      indexes:
        - labelname: ifDescr
          type: Integer32
      lookups:
        - labels: [ifDescr]
          labelname: ifAlias
          oid: 1.3.6.1.2.1.31.1.1.1.18
        - labels: [ifDescr]
          labelname: ifDescr
          oid: 1.3.6.1.2.1.2.2.1.2
```

Thanks for your help Brian !
