### ISSUE TITLE
snmpwalk work but snmp_exporter do not work?

### ISSUE THREAD

**Issue by wanrui** [prometheus/snmp_exporter#367]
s1. use snmpwalk like ` snmpwalk -v3 -l authPriv -u xxx -a MD5 -A "xxxxxx" -x DES -X "xxxxxxxxx" 1.2.3.4` have some correct data return 

s2. use snmp_exporter like below ,it's not work 
 
```
if_mib:
  version: 3
  auth:
    username: xxx 
    password: xxxxxx
    auth_protocol: MD5
    priv_protocol: DES
    security_level: authPriv
    priv_password: xxxxxxxxx
  get:
    - 1.3.6.1.2.1.1.3
  metrics:
    - name: sysUpTime
      oid: 1.3.6.1.2.1.1.3
      type: gauge
```
we have something error  debug log on snmp_exporter

```
Incoming packet is not authentic, discarding
```
use tcpdump to scrap the info like that 

![image](https://user-images.githubusercontent.com/12728608/50008047-e3dc5580-ffed-11e8-8b5c-65c9efab0c05.png)

when to snmp_exporter to test authentic ,find that 
```
snmp.msgAuthenticationParameters 00:00:00:00:00:00:00:00:00:00:00:00
```
is not correct

@brian-brazil

_Originally posted by @wanrui in https://github.com/prometheus/snmp_exporter/issues/257#issuecomment-447338389_
