### ISSUE TITLE
EnumAsInfo vs EnumAsStateSet

### ISSUE THREAD

**Issue by daenney** [prometheus/snmp_exporter#384]
I'm a bit confused as to what the difference between the two is. I know what the README says but I'm not sure what that means. Is there some heuristic for when to pick one over the other? I'm currently revising #379 and a bunch of fields are enum-like.

**Comment by SuperQ** [comment]
Here's basically how I decide. We could add somethign like this to improve the readme.

## StateSet

This is useful if you want to alert on a specific set of states you want to alert on. Things like link state changes, where you need a 1 or 0. Also useful if you expect this value to change over time.

```yaml
- alert: LinkFlapping
  expr: changes(ifOperStatus{ifOperStatus="up"}[15m]) > 2
```

## Enum

Where you don't really care about the state, and don't expect the label to change over time. Things like version numbers, and inventory-ish data.

```
ifType{ifIndex="0",ifType="ethernetCsmacd"
```

**Comment by daenney** [comment]
This is helpful, thanks.

In the case of Printer-MIB then for example the `EnumAsStateSet` would be good for the `prtCoverStatus`, which has like 3 options of "open", "closed", "unknown" vs `prtColorantValue` as a `EnumAsInfo` which has "black", "white", "red", "cyan" and "yellow" and a toner doesn't change color.

**Comment by loganmc10** [comment]
Hey I have a question about this but I don't think it warrants a new issue:

Is EnumAsInfo supposed to work when attaching the value as a label?

Let's say I am collecting IfHCOutOctets and I want to add a lookup for ifType. Is there a way to have ifType resolve to the textual description rather than an integer?

I tried overriding ifType as EnumAsInfo, but it doesn't add the enumerated values to snmp.yml

**Comment by daenney** [comment]
I think what you're looking for is `lookups`: https://github.com/prometheus/snmp_exporter/tree/main/generator#file-format and in the generator: https://github.com/prometheus/snmp_exporter/blob/623b659678ad565217e93ac77b74bbc84c40660c/generator/generator.yml#L294-L298

It results in something like this in `snmp.yml`:
```yaml
- name: ifHCOutOctets
    oid: 1.3.6.1.2.1.31.1.1.1.10
    type: counter
    help: The total number of octets transmitted out of the interface, including framing
      characters - 1.3.6.1.2.1.31.1.1.1.10
    indexes:
    - labelname: ifIndex
      type: gauge
    lookups:
    - labels:
      - ifIndex
      labelname: ifDescr
      oid: 1.3.6.1.2.1.2.2.1.2
      type: DisplayString
    - labels: []
      labelname: ifIndex
```
