### ISSUE TITLE
dont print all oid

### ISSUE THREAD

**Issue by logicall** [prometheus/snmp_exporter#39]
Hello!
snmp-export displays not all oid.

```
# HELP snmp_oids_walked Number of oids walked in this scrape
# TYPE snmp_oids_walked gauge
snmp_oids_walked 16.0
# HELP SmgEOnePhyState SNMP OID 1.3.6.1.4.1.35265.1.29.7.1.2.0
# TYPE SmgEOnePhyState untyped
# HELP SmgEOnePhyState1 SNMP OID 1.3.6.1.4.1.35265.1.29.7.1.2.1
# TYPE SmgEOnePhyState1 untyped
SmgEOnePhyState1{ifDescr=""} 6.0
# HELP SmgEOnePhyState2 SNMP OID 1.3.6.1.4.1.35265.1.29.7.1.2.2
# TYPE SmgEOnePhyState2 untyped
SmgEOnePhyState2{ifDescr=""} 6.0
# HELP snmp_scrape_duration_seconds Time this SNMP scrape took, in seconds
# TYPE snmp_scrape_duration_seconds gauge
snmp_scrape_duration_seconds 0.01685190200805664
```

snmp.conf
```
default:
	community: public
	walk:
		- 1.3.6.1.4.1.35265.1.29.7.1.2
	metrics:

		- name: SmgEOnePhyState
			oid: 1.3.6.1.4.1.35265.1.29.7.1.2.0
			indexes:
				- labelname: ifDescr
					type: Integer32

		- name: SmgEOnePhyState1
			oid: 1.3.6.1.4.1.35265.1.29.7.1.2.1
			indexes:
				- labelname: ifDescr
					type: Integer32

		- name: SmgEOnePhyState2
			oid: 1.3.6.1.4.1.35265.1.29.7.1.2.2
			indexes:
				- labelname: ifDescr
					type: Integer32
```
Here print snmpget
```%snmpget -On -v 2c -c public 192.168.20.228 1.3.6.1.4.1.35265.1.29.7.1.2.0
.1.3.6.1.4.1.35265.1.29.7.1.2.0 = INTEGER: 6```

Why does not appear the value of oid 1.3.6.1.4.1.35265.1.29.7.1.2.0?

P.S.
Sorry for my bad english

**Comment by RichiH** [comment]
You need to use `oid: 1.3.6.1.4.1.35265.1.29.7.1.2` instead of `oid: 1.3.6.1.4.1.35265.1.29.7.1.2.0`

**Comment by RichiH** [comment]
Also, you need to change your community string as you just posted it to the public Internet...

**Comment by logicall** [comment]
@RichiH Thank you!

Now I received data.
Do not filled Field "ifDescr" for some reason oid 1.3.6.1.4.1.35265.1.29.7.1.2.0

```
# HELP SmgEOnePhyState SNMP OID 1.3.6.1.4.1.35265.1.29.7.1.2
# TYPE SmgEOnePhyState untyped
SmgEOnePhyState{ifDescr="8"} 6.0
SmgEOnePhyState{ifDescr="9"} 2.0
SmgEOnePhyState{ifDescr="10"} 2.0
SmgEOnePhyState{ifDescr="11"} 6.0
SmgEOnePhyState{ifDescr="4"} 6.0
SmgEOnePhyState{ifDescr="5"} 6.0
SmgEOnePhyState{ifDescr="6"} 6.0
SmgEOnePhyState{ifDescr="7"} 6.0
SmgEOnePhyState{ifDescr="1"} 6.0
SmgEOnePhyState{ifDescr="2"} 6.0
SmgEOnePhyState{ifDescr="3"} 6.0
SmgEOnePhyState{ifDescr=""} 6.0
SmgEOnePhyState{ifDescr="12"} 6.0
SmgEOnePhyState{ifDescr="13"} 6.0
SmgEOnePhyState{ifDescr="14"} 6.0
SmgEOnePhyState{ifDescr="15"} 6.0
# HELP snmp_scrape_duration_seconds Time this SNMP scrape took, in seconds
# TYPE snmp_scrape_duration_seconds gauge
snmp_scrape_duration_seconds 0.018084049224853516
# HELP snmp_oids_walked Number of oids walked in this scrape
# TYPE snmp_oids_walked gauge
snmp_oids_walked 16.0
```

**Comment by RichiH** [comment]
You didn't do a lookup. Try

````
walk:
    - 1.3.6.1.2.1.2
    - 1.3.6.1.4.1.35265.1.29.7.1.2

metrics:
    - name: SmgEOnePhyState
        oid: 1.3.6.1.4.1.35265.1.29.7.1.2.0
        indexes:
            - labelname: ifDescr
                type: Integer32
        lookups:
           - labels: [ifDescr]
            labelname: ifDescr
            oid: 1.3.6.1.2.1.2.2.1.2
````
