### ISSUE TITLE
snmp_exporter timeouts collecting switch metric

### ISSUE THREAD

**Issue by vishnubraj** [prometheus/snmp_exporter#403]
i am new to Prometheus, i have a Juniper switch which is located less than 5 ms distance from snmp_exporter. but it is have 192 physical ports. when i run the below walk it times out as i have mentioned 2 minutes as scrape_timeout: 120s, in the below mentioned walk alias and interface dont need to be walked for every scrape_interval.. Is there any option to customise to  only get the 1.3.6.1.2.1.31.1.1.1.10 and keep the alias and interface details in the cache??

```
  - name: ifHCOutOctets
    oid: 1.3.6.1.2.1.31.1.1.1.10
    type: gauge
    help: The total number of octets transmitted out of the interface, including framing characters - 1.3.6.1.2.1.31.1.1.1.10
    indexes:
    - labelname: interface
      type: gauge

    lookups:
       - labels: [interface]
         oid: 1.3.6.1.2.1.2.2.1.2
         labelname: interface
         type: DisplayString
       - labels: [interface]
         oid: 1.3.6.1.2.1.31.1.1.1.18
         labelname: alias
         type: DisplayString
```
