### ISSUE TITLE
Multiple metrics with the same OID? (multi-CPU load case)

### ISSUE THREAD

**Issue by paurullan** [prometheus/snmp_exporter#43]
I have a multi-core switch I would like to monitor. I can walk the CPU tree but I do not know how to register the load for the 36 cores.

```
$ snmpwalk -v 2c  -c public 10.10.0.8  .1.3.6.1.2.1.25.3.3.1.2
iso.3.6.1.2.1.25.3.3.1.2.1 = INTEGER: 2
[...]
iso.3.6.1.2.1.25.3.3.1.2.36 = INTEGER: 1
```

I may write the individual metrics but it will be a pain to use later in prometheus because I will not have a simple way to do an `avg` on the many metrics.

```
    - name: hrProcessorLoad_1
      oid: 1.3.6.1.2.1.25.3.3.1.2.1 # the last «1» is the core number
      type: Integer32
```

I would love to do something like this: to be able to mach the last OID number to a label.

```
    - name: hrProcessorLoad
      oid: 1.3.6.1.2.1.25.3.3.1.2.[cpu]
      type: Integer32
      indexes:
          - labelname: cpu
            type: Integer32
      lookups:
         - labels: [cpu]
           labelname: cpu
           values: 1-36 
```

How would you approach this issue?

**Comment by RichiH** [comment]
You match that to the table with the CPU core descriptions. Look at `ifDescr` for how this works.

**Comment by brian-brazil** [comment]
```
   - name: hrProcessorLoad
      oid: 1.3.6.1.2.1.25.3.3.1.2
      type: Integer32
      indexes:
          - labelname: cpu
            type: Integer32
```

should do it offhand.

**Comment by RichiH** [comment]
@brian-brazil For clarification: If you omit `lookups`, the index simply assigns the last number in a OID to the label as its value?

**Comment by brian-brazil** [comment]
It's two stages. Indexes extracts indexes as labels. Lookups lets you add/replace labels based on lookups of the tree.

**Comment by RichiH** [comment]
Ah, neat. Never understood it that way, but makes sense in hindsight. Thanks :)

**Comment by RichiH** [comment]
@paurullan Still, if you have a table with human-readable descriptions (unlikely in this specific case, mind), going via lookups might be preferable.

**Comment by paurullan** [comment]
@brian-brazil fantastic, thank you. The example worked great for the CPUs.

Now I have another similar case but with a twist: the router exposes the traffic for the external ports in the same OID walk than the dynamic clients (it is behind a PON port). Currently it has more than 3500+ items, I only need a list of 20 and the exporter only outputs around a hundred.

@RichiH , you said «going via lookups» but I could not fully understand how. This is my draft; how would you do it?

```
  metrics:
    - name: portOutput
      oid: 1.3.6.1.2.1.31.1.1.1.10
      type: Integer32
      indexes:
        - labelname: port
          type: Integer32
   #  lookups:
   #    - labels: [port]
   #      labelname: port
   #      values:                                                                              
   #        - "11004"
   #        - "10204"
```

**Comment by RichiH** [comment]
@paurullan The Prometheus way is to simply ingest those few thousand values and then ignore them in your queries. It might be counter-intuitive at first, but unless you're already resource-constrained, it will incur the least cost; human attention tends to be more expensive than hardware, in the long run.

Lookups are orthogonal to that, they simply assign a string from the snmpbulkget instead of the last section of the OID.

**Comment by paurullan** [comment]
@RichiH the problem is that doing a full snmp walk on that OID range takes more than 50 seconds.

But I found a way to cross the lookup with strings:

```
~$  snmpbulkget 10.40.0.10 -v 2c -c public 1.3.6.1.2.1.31.1
iso.3.6.1.2.1.31.1.1.1.1.101 = STRING: "Ethport 1/1/g1"
iso.3.6.1.2.1.31.1.1.1.1.102 = STRING: "Ethport 1/1/g2"
iso.3.6.1.2.1.31.1.1.1.1.103 = STRING: "Ethport 1/1/g3"
iso.3.6.1.2.1.31.1.1.1.1.104 = STRING: "Ethport 1/1/g4"
iso.3.6.1.2.1.31.1.1.1.1.201 = STRING: "Ethport 1/2/g1"
iso.3.6.1.2.1.31.1.1.1.1.202 = STRING: "Ethport 1/2/g2"
iso.3.6.1.2.1.31.1.1.1.1.203 = STRING: "Ethport 1/2/g3"
iso.3.6.1.2.1.31.1.1.1.1.204 = STRING: "Ethport 1/2/g4"
iso.3.6.1.2.1.31.1.1.1.1.301 = STRING: "Ethport 2/1/g1"
iso.3.6.1.2.1.31.1.1.1.1.302 = STRING: "Ethport 2/1/g2"
```

```
---
# Connection output for the PONs
default:
  walk:
    - 1.3.6.1.2.1.31.1.1.1.6
    - 1.3.6.1.2.1.31.1.1.1.10
  metrics:
    - name: ifHCInOctets
      oid: 1.3.6.1.2.1.31.1.1.1.6
      indexes:
        - labelname: ifMIBObjects
          type: Integer32
      lookups:
        - labels: [ifMIBObjects]
          labelname: ifMIBObjects
          oid: 1.3.6.1.2.1.31.1
```


This solution gives me lots of unnecessary items but it will do.
Was this the lookup way you mentioned?
