### ISSUE TITLE
Handle BITS textual conversion

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#443]
The [ServerTech Sentry 4](https://cdn10.servertech.com/assets/documents/documents/815/original/Sentry4.mib) uses a textual conversion of a `BITS` type. This looks like it's used as an enum of sort.

For example:
```
    EventNotificationMethods ::= TEXTUAL-CONVENTION
        STATUS      current
        DESCRIPTION
            "Bits to enable event notification methods."
        SYNTAX      BITS {
                        snmpTrap(0),     -- enables notifications by SNMP traps
                        email(1)         -- enables notifications by Email
                    }

    st4UnitNotifications OBJECT-TYPE
        SYNTAX      EventNotificationMethods
        MAX-ACCESS  read-write
        STATUS      current
        DESCRIPTION
            "The notification methods enabled for unit events."
        ::= { st4UnitEventConfigEntry 1 }
```

Another `BITS` example is status enum:

```
    st4UnitCapabilities OBJECT-TYPE
        SYNTAX      BITS {
                        dc(0),         -- unit is DC
                        phase3(1),     -- unit is 3 phase
                        wye(2),        -- unit has Wye circuits
                        delta(3)       -- unit has Delta circuits
                    }
        MAX-ACCESS  read-only
        STATUS      current
        DESCRIPTION
            "The capabilities of the unit."
        ::= { st4UnitConfigEntry 8 }
```

It looks like part of the problem is with `BITS`, we turn them into OctetStrings by default, and they turn into invalid UTF8.

```yaml
modules:
  servertech_sentry4:
    walk:
      - st4UnitCapabilities
```

```yaml
servertech_sentry4:
  walk:
  - 1.3.6.1.4.1.1718.4.1.2.2.1.8
  metrics:
  - name: st4UnitCapabilities
    oid: 1.3.6.1.4.1.1718.4.1.2.2.1.8
    type: OctetString
    help: The capabilities of the unit. - 1.3.6.1.4.1.1718.4.1.2.2.1.8
    indexes:
    - labelname: st4UnitIndex
      type: gauge
    enum_values:
      0: dc
      1: phase3
      2: wye
      3: delta
```

**Comment by SuperQ** [comment]
It looks like BITS is being handled correctly, but not as a textual conversion.

**Comment by SuperQ** [comment]
A workaround for these is to manually provide the enum override.

```yaml
modules:
  servertech_sentry4:
    walk:
      - st4UnitCapabilities
    overrides:
      st4UnitCapabilities:
        type: EnumAsInfo
```

```yaml
servertech_sentry4:
  walk:
  - 1.3.6.1.4.1.1718.4.1.2.2.1.8
  metrics:
  - name: st4UnitCapabilities
    oid: 1.3.6.1.4.1.1718.4.1.2.2.1.8
    type: EnumAsInfo
    help: The capabilities of the unit. - 1.3.6.1.4.1.1718.4.1.2.2.1.8
    indexes:
    - labelname: st4UnitIndex
      type: gauge
    enum_values:
      0: dc
      1: phase3
      2: wye
      3: delta
```
