### ISSUE TITLE
snmp_exporter get strange address "49.48.46.49"

### ISSUE THREAD

**Issue by maplewf** [prometheus/snmp_exporter#446]
### Host operating system: output of `uname -a`
Linux ubuntu 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter, version 0.15.0 (branch: HEAD, revision: 92a3da4467f8bc6759cf197e7442b8c43e890b13)
  build user:       root@8c3a7c03d455
  build date:       20190212-13:40:02
  go version:       go1.11.5
### What device/snmpwalk OID are you using?
I'm using Huawei Cloud Engine Series Switch, and want to get it's metric `nqaResultsAddress` from SNMP, its OID is `1.3.6.1.4.1.2011.5.25.111.4.1.1.20`
### If this is a new device, please link to the MIB(s).
It's hard to get its online MIB, I attached the MIB file here:
[NQA-MIB.2.75.txt](https://github.com/prometheus/snmp_exporter/files/3568177/NQA-MIB.2.75.txt)

### What did you do that produced an error?
I'm using very easy generator.yml to generate snmp.yml, a bunch of MIB files including attached Mib above as input:
```
modules:
  huawei_mib:
     walk:
        - nqaResultsAddress
```
here comes the snmp.yml:
```
huawei_mib:
  walk:
  - 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
  metrics:
  - name: nqaResultsAddress
    oid: 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
    type: InetAddress
    help: The destination address (TraceRoute is the destination address of each hop,
      and ping is the destination address of tests). - 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
    indexes:
    - labelname: nqaAdminCtrlOwnerIndex
      type: DisplayString
    - labelname: nqaAdminCtrlTestName
      type: DisplayString
    - labelname: nqaResultsIndex
      type: gauge
    - labelname: nqaResultsHopIndex
      type: gauge
```
### What did you expect to see?
I expect to see the following metric in snmp_exporter,  `nqaResultsAddress` should be the address I configured in the switch:
```
nqaResultsAddress{nqaAdminCtrlOwnerIndex="xxxxxx",nqaAdminCtrlTestName="xxxxxx",nqaResultsAddress="<nqa address I configured in switch>",nqaResultsHopIndex="1",nqaResultsIndex="652817"} 1
```
### What did you see instead?
The label `nqaResultsAddress` has a value `49.48.46.49` which I never know as following:
```
nqaResultsAddress{nqaAdminCtrlOwnerIndex="xxxxxx",nqaAdminCtrlTestName="xxxxxx",nqaResultsAddress="49.48.46.49",nqaResultsHopIndex="1",nqaResultsIndex="652817"} 1
```
But if I use snmpwalk to get the value, it work as normal:
```
snmpwalk -v 2c -c public <switch IP> 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.4.116.101.115.116.652817.1 = STRING: "10.11.0.100"
```

I wonder if there is something wrong in snmp-exporter parsing or in my configuration?

**Comment by brian-brazil** [comment]
That's an InetAddress, so can't be interpreted without the nqaResultsAddressType before it. What's the generator actually producing for this, and what's the raw data from the walk?

**Comment by maplewf** [comment]
Hi,

I compiled generator according to procedure in https://github.com/prometheus/snmp_exporter/tree/master/generator, nothing is special. 

the raw data from walk is like below:
```
snmpwalk -v 2c -c public <switch ip> 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.4.116.101.115.116.656545.1 = STRING: "10.11.0.100"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.4.116.101.115.116.656546.1 = STRING: "10.11.0.100"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.4.116.101.115.116.656547.1 = STRING: "10.11.0.100"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.4.116.101.115.116.656548.1 = STRING: "10.11.0.100"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.4.116.101.115.116.656549.1 = STRING: "10.11.0.100"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.98.106.48.49.95.49.656482.1 = STRING: "10.10.0.78"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.98.106.48.49.95.49.656483.1 = STRING: "10.10.0.78"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.98.106.48.49.95.49.656484.1 = STRING: "10.10.0.78"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.98.106.48.49.95.49.656485.1 = STRING: "10.10.0.78"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.98.106.48.49.95.49.656486.1 = STRING: "10.10.0.78"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.115.104.48.50.95.49.656466.1 = STRING: "10.10.0.46"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.115.104.48.50.95.49.656467.1 = STRING: "10.10.0.46"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.115.104.48.50.95.49.656468.1 = STRING: "10.10.0.46"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.115.104.48.50.95.49.656469.1 = STRING: "10.10.0.46"
iso.3.6.1.4.1.2011.5.25.111.4.1.1.20.12.112.114.105.118.97.116.101.95.108.105.110.101.11.116.111.95.99.110.115.104.48.50.95.49.656470.1 = STRING: "10.10.0.46"
```

what do you mean " InetAddress can't be interpreted without the nqaResultsAddressType before it"? I modified the generator.yml and have new snmp.yml, but the result is not changed, how should I configure it correctly?
```
generator.yml:
modules:
  huawei_mib:
     walk:
        - nqaResultsAddress

snmp.yml:
huawei_mib:
  walk:
  - 1.3.6.1.4.1.2011.5.25.111.4.1.1.19
  - 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
  metrics:
  - name: nqaResultsAddressType
    oid: 1.3.6.1.4.1.2011.5.25.111.4.1.1.19
    type: gauge
    help: The destination address type, and the value range can be unknown(0), ipv4(1)
      and dns(16). - 1.3.6.1.4.1.2011.5.25.111.4.1.1.19
    indexes:
    - labelname: nqaAdminCtrlOwnerIndex
      type: DisplayString
    - labelname: nqaAdminCtrlTestName
      type: DisplayString
    - labelname: nqaResultsIndex
      type: gauge
    - labelname: nqaResultsHopIndex
      type: gauge
    enum_values:
      0: unknown
      1: ipv4
      2: ipv6
      3: ipv4z
      4: ipv6z
      16: dns
  - name: nqaResultsAddress
    oid: 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
    type: InetAddress
    help: The destination address (TraceRoute is the destination address of each hop,
      and ping is the destination address of tests). - 1.3.6.1.4.1.2011.5.25.111.4.1.1.20
    indexes:
    - labelname: nqaAdminCtrlOwnerIndex
      type: DisplayString
    - labelname: nqaAdminCtrlTestName
      type: DisplayString
    - labelname: nqaResultsIndex
      type: gauge
    - labelname: nqaResultsHopIndex
      type: gauge
```
