### ISSUE TITLE
Feature: Textual Convention lookups for indexes

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#461]
The [Raritan PDU2-MIB](http://cdn.raritan.com/download/lg/version-3.4.11/PDU2_MIB_3.4.11_44691.txt) contains a TEXTUAL-CONVENTION enum used to identify sensor types. But the `sensorType` is not mapped into the table as a string, only as an index integer.

Example generator.yml:
```yaml
modules:
  raritan:
   walk:
   - measurementsOutletSensorValue
```

Output snmp.yml:
```yaml
# WARNING: This file was auto-generated using snmp_exporter generator, manual changes will be lost.
raritan:
  walk:
  - 1.3.6.1.4.1.13742.6.5.4.3.1.4
  metrics:
  - name: measurementsOutletSensorValue
    oid: 1.3.6.1.4.1.13742.6.5.4.3.1.4
    type: gauge
    help: The sensor reading as an unsigned integer - 1.3.6.1.4.1.13742.6.5.4.3.1.4
    indexes:
    - labelname: pduId
      type: gauge
    - labelname: outletId
      type: gauge
    - labelname: sensorType
      type: gauge
```

It would be useful to be able to get the data for the sensorType SensorTypeEnumeration into the snmp.yml to replace gauge index with the string.
