### ISSUE TITLE
snmp_exporter config to show relevant values HEX string from specific MIB juniper

### ISSUE THREAD

**Issue by HappyFX** [prometheus/snmp_exporter#466]
I have problem with display the result in readable form: http://oidref.com/1.3.6.1.2.1.15.6.1.5
```
bgp4PathAttrASPathSegment OBJECT-TYPE
SYNTAX OCTET STRING (SIZE (2..255))
MAX-ACCESS read-only
STATUS current
DESCRIPTION
"The sequence of AS path segments. Each AS
path segment is represented by a triple
The type is a 1-octet field which has two
possible values:
1 AS_SET: unordered set of ASs a
route in the UPDATE
message has traversed
2 AS_SEQUENCE: ordered set of ASs
a route in the UPDATE
message has traversed.
The length is a 1-octet field containing the
number of ASs in the value field.
The value field contains one or more AS
numbers, each AS is represented in the octet
string as a pair of octets according to the
following algorithm:
first-byte-of-pair = ASNumber / 256;
second-byte-of-pair = ASNumber & 255;"
```
For example I used Juniper as SNMP target.
snmp walk result:
`iso.3.6.1.2.1.15.6.1.5.10.0.1.0.24.10.0.1.15 = Hex-STRING: 02 01 FD EA FF FF FF FF`
My config `snmp.yml`: 
```yml
ipv4_juniper:
  walk:
    - 1.3.6.1.2.1.15.6.1.5.10.0.1.0
  metrics:
  - name: snmp_bgp_AS_path
    oid: 1.3.6.1.2.1.15.6.1.5
    type: OctetString
    help: The sequence of AS path segments - /32
    indexes:
    - labelname: snmp_addr_prefix
      type: InetAddressIPv4
    - labelname: snmp_addr_prefix_len
      type: gauge
    - labelname: snmp_attr_peer
      type: InetAddressIPv4
```

snmp_exporter result:
`snmp_bgp_AS_path{snmp_addr_prefix="10.0.1.0",snmp_addr_prefix_len="24",snmp_attr_peer="10.0.1.15",snmp_bgp_AS_path="0x0201FDEAFFFFFFFF"} 1`

desire result:
`snmp_bgp_AS_path{snmp_addr_prefix="10.0.1.0",snmp_addr_prefix_len="24",snmp_attr_peer="10.0.1.15",snmp_as_set="2",snmp_as_sequence="3",snmp_bgp_AS_path="[65002,65535,65535]"} 1`

base logic:
value from snmp: Hex-STRING: 02 01 FD EA FF FF FF FF
then I need to group: [[02],[03],[FDEA],[FFFF],[FFFF]]
and convert hex to dec: 2 3 65002 65535 65535
