### ISSUE TITLE
EnumAsInfo panic

### ISSUE THREAD

**Issue by SuperQ** [prometheus/snmp_exporter#477]
### snmp_exporter version: output of `snmp_exporter -version`

version=0.16.1

### What device/snmpwalk OID are you using?

snmp.yml:
```
  - name: ciscoEnvMonSupplyStatusIndex
    oid: 1.3.6.1.4.1.9.9.13.1.5.1.1
    type: gauge
    help: Unique index for the power supply being instrumented - 1.3.6.1.4.1.9.9.13.1.5.1.1
    indexes:
    - labelname: ciscoEnvMonSupplyStatusIndex
      type: gauge
```

### What did you do that produced an error?

Set an `EnumAsInfo`

### What did you see instead?

```
snmp_exporter[1138]: panic: Unknown index type EnumAsInfo
snmp_exporter[1138]: goroutine 1918149 [running]:
snmp_exporter[1138]: main.indexOidsAsString(0xc0008ee4e8, 0x1, 0x3, 0xc0011c54f0, 0xa, 0x0, 0xab9200, 0xc000192a40, 0x0, 0x0, ...)
snmp_exporter[1138]: #011/app/collector.go:662 +0x1870
snmp_exporter[1138]: main.indexesToLabels(0xc0008ee4e8, 0x1, 0x3, 0xc00131dc00, 0xc0006bbaa0, 0x4)
snmp_exporter[1138]: #011/app/collector.go:673 +0x169
snmp_exporter[1138]: main.pduToSamples(0xc0008ee4e8, 0x1, 0x3, 0xc0006bbad0, 0xc00131dc00, 0xc0006bbaa0, 0xaaf060, 0xc000721e60, 0xc000d36a50, 0x1, ...)
snmp_exporter[1138]: #011/app/collector.go:326 +0x77
snmp_exporter[1138]: main.collector.Collect(0xc000d6a025, 0x11, 0xc0001752c0, 0xaaf060, 0xc000721e60, 0xc001252e40)
snmp_exporter[1138]: #011/app/collector.go:244 +0x914
snmp_exporter[1138]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
snmp_exporter[1138]: #011/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:443 +0x19d
snmp_exporter[1138]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
snmp_exporter[1138]: #011/app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:454 +0x57d
```

It turns out I made an incorrect override for `ciscoEnvMonSupplyStatusIndex` as an `EnumAsInfo`. So this is possibly a generator safety check that is needed to avoid allowing enum types for OIDs that don't have `enum_values`.

**Comment by brian-brazil** [comment]
What version of the exporter and generator were in use? I'd guess you had a
too old exporter.

**Comment by SuperQ** [comment]
Updated the description with more info. This was totally a user error, but it might be something we want to protected against in the generator.

**Comment by fredericve** [comment]
@SuperQ @brian-brazil 

As discussed on IRC this happens as well for me in the case the index is an Enum. I am using the [oracle acme packet MIB](https://docs.oracle.com/cd/F12246_01/doc/MIBSSCZ830.zip) ap-sip.mib.

When I add an override to the apSipMethodStatsIndex oid the same panic occurs:
```yaml
modules:
  acmepacket:
    walk:
      - 1.3.6.1.2.1.1          # System object
      - 1.3.6.1.2.1.2          # Interfaces object
      - 1.3.6.1.2.1.5          # ICMP object
      - 1.3.6.1.2.1.6          # TCP object
      - 1.3.6.1.2.1.7          # UDP object
      - 1.3.6.1.2.1.31.1.1     # ifXTable object
      - 1.3.6.1.4.1.9148.3.16  # ap-apps Applications MIB
      - 1.3.6.1.4.1.9148.3.7   # ap-codec Codec and Transcoding MIB
      - 1.3.6.1.4.1.9148.3.2   # ap-smgmt System Management MIB
      - 1.3.6.1.4.1.9148.3.13  # ap-diameter Diameter MIB
      - 1.3.6.1.4.1.9148.3.14  # ap-dnsalg DNS ALG MIB
      - 1.3.6.1.4.1.9148.3.3   # ap-env-monitor Environment Monitor MIB
      - 1.3.6.1.4.1.9148.3.10  # ap-h323 H.323 MIB
      - 1.3.6.1.4.1.9148.3.5   # ap-license License MIB
      - 1.3.6.1.4.1.9148.3.9   # ap-security Security MIB
      - 1.3.6.1.4.1.9148.3.15  # ap-sip SIP MIB
      - 1.3.6.1.4.1.9148.3.4   # ap-swinventory Software Inventory MIB
      - 1.3.6.1.4.1.9148.3.17  # ap-usbcsys Multicore Monitoring MIB
    lookups:
      - source_indexes:
          - ifIndex
        lookup: ifDescr
      - source_indexes:
          - apSipSAStatsSessionAgentIndex
        lookup: apSipSAStatsSessionAgentHostname
      - source_indexes:
          - apSipAgentIndex
        lookup: apSipAgentName
      - source_indexes:
          - apCombinedStatsSessionAgentIndex
        lookup: apCombinedStatsSessionAgentHostname
      - source_indexes:
          - apSigRealmStatsRealmIndex
        lookup: apSigRealmStatsRealmName
      - source_indexes:
          - apSysVolumeIndex
        lookup: apSysVolumeName
    overrides:
        apSipMethodStatsIndex:
            type: EnumAsInfo
```

**Comment by SuperQ** [comment]
To reproduce, I used these mibs: ap-license.mib ap-sip.mib ap-smgmt.mib ap-smi.mib ap-tc.mib.

This simplified generator.yml is enough:
```
modules:
  ap-sip:
    walk:
    - apSipMethodStatsIndex
    overrides:
      apSipMethodStatsIndex:
        type: EnumAsInfo
```
