### ISSUE TITLE
"Lookups:" of generator seems not working

### ISSUE THREAD

**Issue by shdxiang** [prometheus/snmp_exporter#485]
### Host operating system: output of `uname -a`
Linux 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

f0ad4551a5c2023e383bc8dde2222f47dc760b83

### What device/snmpwalk OID are you using?
1.3.6.1.4.1.674.10892.5.4.700.12.1

### If this is a new device, please link to the MIB(s).
https://raw.githubusercontent.com/librenms/librenms/master/mibs/drac/IDRAC-MIB-SMIv2

### What did you do that produced an error?
generator.yml
```yaml
modules:
  dell_irac:
    version: 2
    auth:
      community: public
    walk:
      - 1.3.6.1.4.1.674.10892.5.4.700.12.1 # coolingDeviceTable
    lookups:
      - source_indexes: [coolingDeviceLocationName]
        lookup: coolingDeviceStatus
    overrides:
      coolingDeviceStatus:
        type: EnumAsStateSet
      coolingDeviceLocationName:
        type: DisplayString
```

### What did you expect to see?
snmp.yml
```yaml
...
- name: coolingDeviceStatus
    oid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.5
    type: EnumAsStateSet
    help: 0700.0012.0001.0005 This attribute defines the probe status of the cooling
      device. - 1.3.6.1.4.1.674.10892.5.4.700.12.1.5
    indexes:
    - labelname: coolingDevicechassisIndex
      type: gauge
    - labelname: coolingDeviceIndex
      type: gauge
    - labelname: coolingDeviceLocationName
      type: DisplayString
    enum_values:
      1: other
      2: unknown
      3: ok
      4: nonCriticalUpper
      5: criticalUpper
      6: nonRecoverableUpper
      7: nonCriticalLower
      8: criticalLower
      9: nonRecoverableLower
      10: failed
...
```

### What did you see instead?
snmp.yml
```yaml
...
- name: coolingDeviceStatus
    oid: 1.3.6.1.4.1.674.10892.5.4.700.12.1.5
    type: EnumAsStateSet
    help: 0700.0012.0001.0005 This attribute defines the probe status of the cooling
      device. - 1.3.6.1.4.1.674.10892.5.4.700.12.1.5
    indexes:
    - labelname: coolingDevicechassisIndex
      type: gauge
    - labelname: coolingDeviceIndex
      type: gauge
    enum_values:
      1: other
      2: unknown
      3: ok
      4: nonCriticalUpper
      5: criticalUpper
      6: nonRecoverableUpper
      7: nonCriticalLower
      8: criticalLower
      9: nonRecoverableLower
      10: failed
...
```

`coolingDeviceLocationName` did not show in the indexes.

**Comment by brian-brazil** [comment]
That output is correct, coolingDeviceLocationName is not an index of that table.

**Comment by shdxiang** [comment]
@brian-brazil Thanks, so only the `index` of  a table can be used as `source_indexes` right? Is there a way to make `coolingDeviceLocationName` a label of `coolingDeviceStatus`?

**Comment by brian-brazil** [comment]
Yes, list all the indexes in the source indexes and then it as the target.

**Comment by SuperQ** [comment]
This is the correct lookup:

```yaml
modules:
  dell_irac:
    version: 2
    auth:
      community: public
    walk:
    - 1.3.6.1.4.1.674.10892.5.4.700.12.1 # coolingDeviceTable
    lookups:
    - source_indexes:
      - coolingDevicechassisIndex
      - coolingDeviceIndex
      lookup: coolingDeviceLocationName
    overrides:
      coolingDeviceStatus:
        type: EnumAsStateSet
      coolingDeviceLocationName:
        type: DisplayString
```
