### ISSUE TITLE
Mac address as table index results in conflicting label values

### ISSUE THREAD

**Issue by fischerman** [prometheus/snmp_exporter#563]
### Host operating system: output of `uname -a`

```
Linux falcon 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux
```

### snmp_exporter version: output of `snmp_exporter -version`

```
version="(version=0.18.0, branch=master, revision=1b3b0539ec70d692ec1d405345e685a6368c55d1)"
```
FYI `snmp_exporter` has no version flag.

### What device/snmpwalk OID are you using?

Ruckus ZoneDirector
`ruckusZDWLANAPTable` / `ruckusZDWLANAPStatus` (a column in that table)

### What did you do that produced an error?

The index of the table is a mac address. The index is defined without `IMPLIED` in the MIB:
```
    INDEX {
        ruckusZDWLANAPMacAddr }
```
```
ruckusZDWLANAPMacAddr OBJECT-TYPE
    SYNTAX  MacAddress
...
```
From SNMPv2-TC
```
MacAddress ::= TEXTUAL-CONVENTION
    DISPLAY-HINT "1x:"
    STATUS       current
    DESCRIPTION
            "Represents an 802 MAC address represented in the
            `canonical' order defined by IEEE 802.1a, i.e., as if it
            were transmitted least significant bit first, even though
            802.5 (in contrast to other 802.x protocols) requires MAC
            addresses to be transmitted most significant bit first."
    SYNTAX       OCTET STRING (SIZE (6))
```
The device returns the length of the OCTET STRING as part of the index in the OID. As far as I can tell this is according to RFC2578. The `generator.yml` looks as follows.
```
modules:
  wlan_ruckus:
    auth:
      community: <secret>
    walk:
      - ruckusZDWLANAPStatus
```
... which generates the following `snmp.yml`:
```
  metrics:
  - name: ruckusZDWLANAPStatus
    oid: 1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.3
    type: gauge
    help: The connection status with ZD. - 1.3.6.1.4.1.25053.1.2.2.1.1.2.1.1.3
    indexes:
    - labelname: ruckusZDWLANAPMacAddr
      type: PhysAddress48
      fixed_size: 6
    enum_values: ...
```
The resulting index is of fixed length and the length sub-identifier is the first one that is read. As a result the last byte (i.e. the last sub-identifier) of the mac is ignored which makes the index "not unique" and the scrape fails.

```
An error has occurred while serving metrics:

10 error(s) occurred:
* collected metric "ruckusZDWLANAPStatus" { label:<name:"ruckusZDWLANAPMacAddr" value:"06:30:87:D9:1B:52" > gauge:<value:1 > } was collected before with the same name and label values
```

I've tried some alternations to narrow down the problem:

- removing `fixed_size: 6` from `snmp.yml` does not change the label value.
- removing `fixed_size: 6` and changing the type to `type: OctetString` makes the scrape succeed. The length sub-identifier is skipped `ruckusZDWLANAPMacAddr="0x3087D91B5220"`. 

Also `snmpwalk` seems to have some problem displaying this correctly. The first `6` is the length while the last byte of the mac is `0d32`.
```
snmpwalk [...] -Ox ip.local  ruckusZDWLANAPStatus -OX
RUCKUS-ZD-WLAN-MIB::ruckusZDWLANAPStatus[STRING: 6:30:87:d9:1b:52].32 = INTEGER: connected(1)
...
```
