### ISSUE TITLE
generator not indexing table rows

### ISSUE THREAD

**Issue by h3po** [prometheus/snmp_exporter#566]
i've got a problem generating a config for UTIMACO-CSLAN-MIB, which is for monitoring untimaco hardware security modules.

with this example data:
```
$ snmpwalk -M +.snmp/mibs/utimaco -m +UTIMACO-CSLAN-MIB -v2c -c CryptoServer 10.73.107.165 1.3.6.1.4.1.3159.1.1.8
UTIMACO-CSLAN-MIB::cslFanIndex.1 = INTEGER: 1
UTIMACO-CSLAN-MIB::cslFanIndex.2 = INTEGER: 2
UTIMACO-CSLAN-MIB::cslFanIndex.3 = INTEGER: 3
UTIMACO-CSLAN-MIB::cslFanIndex.4 = INTEGER: 4
UTIMACO-CSLAN-MIB::cslFanIndex.5 = INTEGER: 5
UTIMACO-CSLAN-MIB::cslFanIndex.6 = INTEGER: 6
UTIMACO-CSLAN-MIB::cslFanSpeed.1 = INTEGER: 5200
UTIMACO-CSLAN-MIB::cslFanSpeed.2 = INTEGER: 6000
UTIMACO-CSLAN-MIB::cslFanSpeed.3 = INTEGER: 5200
UTIMACO-CSLAN-MIB::cslFanSpeed.4 = INTEGER: 6000
UTIMACO-CSLAN-MIB::cslFanSpeed.5 = INTEGER: 5200
UTIMACO-CSLAN-MIB::cslFanSpeed.6 = INTEGER: 6000
```

i would expect this generator config:
```
modules:
  utimaco-cslan:
    walk:
      - 1.3.6.1.4.1.3159.1.1.8 #SNMPv2-SMI::enterprises.utimaco.cslanMIB.cslFanTable
    version: 2
    auth:
      community: CryptoServer
```
to generate a config with a `cslFanSpeed` metric indexed by `cslFanIndex`, similar to this:
```
utimaco-cslan:
  walk:
  - 1.3.6.1.4.1.3159.1.1.8
  metrics:
  - name: cslFanSpeed
    oid: 1.3.6.1.4.1.3159.1.1.8.1.2
    type: gauge
    help: CryptoServer LAN fan speed in rpm - 1.3.6.1.4.1.3159.1.1.8.1.2
    indexes:
      - labelname: cslFanIndex
        type: gauge
  version: 2
  auth:
    community: CryptoServer
```
but instead, it generates:
```
[...]
  - name: cslFanIndex
    oid: 1.3.6.1.4.1.3159.1.1.8.1.1
    type: gauge
    help: CryptoServer LAN fan index for identification - 1.3.6.1.4.1.3159.1.1.8.1.1
  - name: cslFanSpeed
    oid: 1.3.6.1.4.1.3159.1.1.8.1.2
    type: gauge
    help: CryptoServer LAN fan speed in rpm - 1.3.6.1.4.1.3159.1.1.8.1.2
```
which results in a scrape error:
```
An error has occurred while serving metrics:

10 error(s) occurred:
* collected metric "cslFanIndex" { gauge:<value:3 > } was collected before with the same name and label values
* collected metric "cslFanIndex" { gauge:<value:4 > } was collected before with the same name and label values
* collected metric "cslFanIndex" { gauge:<value:5 > } was collected before with the same name and label values
* collected metric "cslFanIndex" { gauge:<value:6 > } was collected before with the same name and label values
* collected metric "cslFanSpeed" { gauge:<value:5900 > } was collected before with the same name and label values
* collected metric "cslFanIndex" { gauge:<value:1 > } was collected before with the same name and label values
* collected metric "cslFanSpeed" { gauge:<value:5200 > } was collected before with the same name and label values
* collected metric "cslFanSpeed" { gauge:<value:5200 > } was collected before with the same name and label values
* collected metric "cslFanSpeed" { gauge:<value:6000 > } was collected before with the same name and label values
* collected metric "cslFanSpeed" { gauge:<value:6000 > } was collected before with the same name and label values
```

if i write the snmp.yml myself, the exporter works as expected:
```
# HELP cslFanSpeed CryptoServer LAN fan speed in rpm - 1.3.6.1.4.1.3159.1.1.8.1.2
# TYPE cslFanSpeed gauge
cslFanSpeed{cslFanIndex="1"} 5200
cslFanSpeed{cslFanIndex="2"} 6000
cslFanSpeed{cslFanIndex="3"} 5200
cslFanSpeed{cslFanIndex="4"} 6000
cslFanSpeed{cslFanIndex="5"} 5200
cslFanSpeed{cslFanIndex="6"} 6000
```

this is the relevant portion of the mib:
```
cslFanTable OBJECT-TYPE
	SYNTAX		SEQUENCE OF CslFanEntry
	MAX-ACCESS	not-accessible
	STATUS		current
	DESCRIPTION	
        "The table holding information about all CryptoServer LAN fans. Only available for CryptoServer LAN >= V4.
         CSLAN V4b: 3 entries: 1) CPU fan, 2) first internal fan, 3) second internal fan
         CSLAN V4c: 2 entries: 1) first internal fan, 2) second internal fan
         CSLAN V5:  6 entries: 1/2) fans in right module, 3/4) fans in middle module, 5/6) fans in left module"
	::= { cslObjects 8 }

cslFanEntry  OBJECT IDENTIFIER ::= { cslFanTable 1 } 

CslFanEntry ::= SEQUENCE {
    cslFanIndex     Integer32,
    cslFanSpeed     Integer32
}

cslFanIndex OBJECT-TYPE
	SYNTAX		Integer32 (1..10)
	MAX-ACCESS	read-only
	STATUS		current
	DESCRIPTION	"CryptoServer LAN fan index for identification. Only available for CryptoServer LAN >= V4."
	::= { cslFanEntry 1 }
    
cslFanSpeed OBJECT-TYPE
	SYNTAX		Integer32
	MAX-ACCESS	read-only
	STATUS		current
	DESCRIPTION	"CryptoServer LAN fan speed in rpm. Only available for CryptoServer LAN >= V4."
	::= { cslFanEntry 2 } 
```

is this an error caused by the mib or by my generator config? i've fiddled with overrides and lookups for hours but i can't get it to generate a working config. i've chosen the fan table as an example here, the same problem occurs with the other tables in the mib.

edit: here's my manually created WIP snmp.yml: https://gist.github.com/h3po/ba5fea65facc5ec1f2a514122927db92
