### ISSUE TITLE
Exporter not supporting SNMPv3 

### ISSUE THREAD

**Issue by psreekrishnan** [prometheus/snmp_exporter#602]
> I wanted to start the exporter with snmp version 3 config using prometheus-snmp-exporter juju charm but looks like its not supporting SNMP V3 config.

### Host operating system: output of `uname -a`
Linux apnnc01pkrw-test-3 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`

Started the exporter via juju charm, 
juju deploy cs:prometheus-snmp-exporter-1
https://jaas.ai/prometheus-snmp-exporter/1
### What device/snmpwalk OID are you using?
1.3.6.1.2.1.1
### What did you do that produced an error?
Adding **snmp.yml** content below,
```
if_mib:
  walk:
  - 1.3.6.1.2.1.1
  metrics:
  - name: sysDescr
    oid: 1.3.6.1.2.1.1.1
    type: DisplayString
    help: A textual description of the entity - 1.3.6.1.2.1.1.1
  version: 3
  max_repetitions: 25
  retries: 3
  timeout: 5s
  auth:
    security_level: authPriv
    username: <user_name>
    password: <password>
    auth_protocol: MD5
    priv_protocol: AES
    priv_password: <password>

```

### What did you expect to see?
Exporter supposed to start, but instead it gives the above error, it works when I run the snmp_exporter from by downloading it from [here](https://github.com/prometheus/snmp_exporter/releases/download/v0.19.0/snmp_exporter-0.19.0.linux-amd64.tar.gz).

### What did you see instead?
**Error log**
```
Jan 18 09:37:33 apnnc01pkrw-test-3 prometheus-snmp-exporter.snmp-exporter[9742]: time="2021-01-18T09:37:33Z" level=info msg="Build context (go=go1.6.2, user=, date=)" source="main.go:100"
Jan 18 09:37:33 apnnc01pkrw-test-3 prometheus-snmp-exporter.snmp-exporter[9742]: time="2021-01-18T09:37:33Z" level=fatal msg="Error parsing config file: unknown fields in module: get" source="main.go:105"
```
Am I missing anything here?
