### ISSUE TITLE
generator new file management

### ISSUE THREAD

**Issue by xkilian** [prometheus/snmp_exporter#625]
Problem: Each class of devices should be managed in its own directory to simplify testing, mib compatibility and shareability of configs. Merging snmp.yml files becomes a hassle and must be handled by an external script and having a single monster snmp.yml is a pain to review. Also having all generator configuration files names generator.yml and output snmp.yml is not ideal.

Solution: Create an MANDATORY  --input option and an OPTIONAL  --path option for the output path.

The generator MUST have an input option to specify the name of the generator_xxxx.yml file.
The input file MUST have a generator_ prefix
The input file MUST be a valid yml file.
The xxx portion SHOULD represent that grouping identifier for a class of devices or a vendor

Example _valid_ input files:

- generator_cisco_switches.yml
- generator_cisco_fw.yml
- generator_paloalto.yml

Example _invalid_ input files:
- cisco_routers.yml
- netscreen_generator.yml

If no output path is specified:

- name the output file becomes: snmp_xxx.yml and is placed in the current directory (for validation)

An output path SHOULD be specified to deploy to the directory the collector will read
- valid example: /opt/prometheus/etc/snmp_exporter/snmp.d/
- valid example: /etc/snmp_exporter/snmp.d

The output directory for production files MUST be a common directory where all snmp.yml will be merged by the collector.

This FR is linked to a change in the collector #628 to read the snmp_xxxx.yml files for a given directory (startup flag of snmp_exporter).

As discussed with @SuperQ .

**Comment by xkilian** [comment]
Yeah, #628 I'll covers it for the collector. Sorry, I missed it, I will update the issue description to refer to #628.
As for the generator, the above FR is still applicable.

**Comment by RichiH** [comment]
Now that I think about it again, that makes sense. I will need to think about it some more. A mapping from `generator_fool.yml` -> `snmp_exporter_foo.yml` could make sense.

**Comment by lausser** [comment]
I have my own script which reads from smaller yml files, where every involved mib has one:
if_mib.yml  rmon_mib.yml  snmpv2_mib.yml,....
They all start with
```
modules:
  # Default IF-MIB interfaces table with ifIndex.
  if_mib:
    walk: [sysUpTime, interfaces, ifXTable]
```
or
```
modules:
  snmpv2_mib:
    walk:
      - sysDescr
```
and these files get merged into the generator.yml

On the other side i have a script which creates scrape configs for network devices. Depending on the model and usage every device gets a list like this:
self.snmp_exporter_modules = ["if_mib", "snmpv2_mib"]
or
self.snmp_exporter_modules = ["if_mib", "snmpv2_mib", "rmon_mib"]

My first approach was to create two or three scrape configs for the file_sd_configs, one for every mib. But this could mean that two or even more scrapes (snmpwalks) could run against a device at the same time. Sometimes this can lead to timeouts (if you have 512 interfaces for example).
So i thought to have the walks run in a serial manner. The scrape config of a device would then contain a module which consists of all the single mibs (or modules), like  module: if_mib__rmon_mib__snmpv2_mib

The script i mentioned in the beginning would not only copy the contents of the single-mib-ymls into one generator.yml, but also create combined modules by merging them.
```
modules:
  if_mib_
    walk:
      - ifTable
      - ifXTable
  snmpv2_mib:
    walk:
      - sysDescr
  rmon_mib:
    walk:
      - etherstatsTable
```
and there that there are also
```
  if_mib__snmpv2_mib:
    walk:
      - ifTable
      - ifXTable
      - sysDescr
  if_mib__rmon_mib__snmpv2_mib:
    walk:
      - ifTable
      - ifXTable
      - sysDescr
      - etherstatsTable
```

Of course this creates a big generator.yml in the first step, but the number of typical combinations will not be too big.
This would become much easier, if it was possible to allow a list of modules and the snmp_exporter would walk one after the other (skipping duplicate tables/oids)
Also splitting up generator.yml in smaller portions (in generator.d)  would make it easier to exchange config files for certain devices.
