### ISSUE TITLE
Support chained lookups in the generator

### ISSUE THREAD

**Issue by loganmc10** [prometheus/snmp_exporter#678]
https://github.com/prometheus/snmp_exporter/pull/489 added support for chained lookups, but the generator doesn't support this configuration. Consider this list of lookups:
```
    lookups:
      - source_indexes: [cbQosObjectsIndex, cbQosPolicyIndex]
        lookup: cbQosConfigIndex
      - source_indexes: [cbQosConfigIndex]
        lookup: cbQosCMName
```

The order here matters, first it uses [cbQosObjectsIndex, cbQosPolicyIndex] to lookup cbQosConfigIndex, then it uses cbQosConfigIndex to lookup cbQosCMName.

This is already supported (see https://github.com/prometheus/snmp_exporter/issues/405), but the generator doesn't seem to be able to generate a snmp.yml file that would work.
