### ISSUE TITLE
Help/Directions needed

### ISSUE THREAD

**Issue by elisiano** [prometheus/snmp_exporter#70]
I would need some directions on how to accomplish the following (I've read through the README but it's not clear how to generate the config sections).

We are using few fortinet devices: we have one fortinet fortigate (a firewall) and 3 forti AP (access points managed through the fortigate).

I would like to query few of the attributes of the fgWcWtpSessionEntry table (search for oid 1.3.6.1.4.1.12356.101.14.4.4.1 at http://www.oidview.com/mibs/12356/FORTINET-FORTIGATE-MIB.html ).
The table definition can be seen at https://github.com/librenms/librenms/blob/master/mibs/FORTINET-FORTIGATE-MIB.mib#L6125-L6148

The problem is that the index is not an increasing counter but some sort of enumeration.

Example, the following are the IDs of the APs connected (last part of the serial redacted):

```
$ snmpwalk -v 2c -c public $IP 1.3.6.1.4.1.12356.101.14.4.4.1.1
SNMPv2-SMI::enterprises.12356.101.14.4.4.1.1.1.16.70.80.51.50.48.67.51.88.49.54.48.48.48.48.54.55 = STRING: "FP320C3X16000XXX"
SNMPv2-SMI::enterprises.12356.101.14.4.4.1.1.1.16.70.80.51.50.48.67.51.88.49.54.48.48.48.49.50.57 = STRING: "FP320C3X16000YYY"
SNMPv2-SMI::enterprises.12356.101.14.4.4.1.1.1.16.70.80.51.50.48.67.51.88.49.54.48.48.48.51.51.53 = STRING: "FP320C3X16000ZZZ"
```

So, to start simple, I wanted to retrieve the number of wireless clients connected per AP

```
$ snmpwalk -v 2c -c public $IP 1.3.6.1.4.1.12356.101.14.4.4.1.17
SNMPv2-SMI::enterprises.12356.101.14.4.4.1.17.1.16.70.80.51.50.48.67.51.88.49.54.48.48.48.48.54.55 = Gauge32: 10
SNMPv2-SMI::enterprises.12356.101.14.4.4.1.17.1.16.70.80.51.50.48.67.51.88.49.54.48.48.48.49.50.57 = Gauge32: 4
SNMPv2-SMI::enterprises.12356.101.14.4.4.1.17.1.16.70.80.51.50.48.67.51.88.49.54.48.48.48.51.51.53 = Gauge32: 4
```

According to the above, I defined the following section in the snmp.yml

```
fn_fg_test:
  walk:
    - 1.3.6.1.2.1.1.3
    - 1.3.6.1.4.1.12356.101.14.4.4.1.1
    - 1.3.6.1.4.1.12356.101.14.4.4.1.17
  metrics:
    - name: sysUpTime
      oid: 1.3.6.1.2.1.1.3
    - name: fgWcWtpSessionWtpStationCount
      oid: 1.3.6.1.4.1.12356.101.14.4.4.1.17
      indexes:
        - labelname: fgWcWtpSessionWtpId
          type: String
      lookups:
        - labels: [fgWcWtpSessionWtpId]
          labelname: fgWcWtpSessionWtpId
          oid: 1.3.6.1.4.1.12356.101.14.4.4.1.1
```

This results in an error similar to what's described in issue #64:

```
An error has occurred during metrics gathering:

2 error(s) occurred:
* collected metric fgWcWtpSessionWtpStationCount untyped:<value:10 >  was collected before with the same name and label values
* collected metric fgWcWtpSessionWtpStationCount untyped:<value:4 >  was collected before with the same name and label values
```

It seems that the exporter is not able to walk through all the children of the main OID. Or I'm doing something wrong.

Any help/direction would be greatly appreciated.

**Comment by brian-brazil** [comment]
Looking at the MIB the index is an integer followed by a displaystring.

**Comment by elisiano** [comment]
I went through all the tree starting at 1.3.6.1.4.1.12356.101.14.4.4.1 and there is nothing that looks like an integer index.

How would I go implementing this?

**Comment by brian-brazil** [comment]
fgVdEntIndex is an Integer, and is the first entry in the index.

**Comment by elisiano** [comment]
After adding the mib to the system, browsing the OIDs has been a little simpler, but this confirms the fear I had: there is no indices for the managed wireless adapters, I can just query a counter which tells me how many are managed.

the fgVdEntIndex is the list of virtual domains (not helpful): 
```
$ snmpwalk -m +FORTINET-FORTIGATE-MIB -v2c -cpublic  $IP fgVdEntIndex
FORTINET-FORTIGATE-MIB::fgVdEntIndex.1 = INTEGER: 1
```

```
$ snmpwalk -m +FORTINET-FORTIGATE-MIB -v2c -cpublic  $IP fgWcInfo
FORTINET-FORTIGATE-MIB::fgWcInfoName.0 = STRING:
FORTINET-FORTIGATE-MIB::fgWcInfoLocation.0 = STRING:
FORTINET-FORTIGATE-MIB::fgWcInfoWtpCapacity.0 = Gauge32: 128
FORTINET-FORTIGATE-MIB::fgWcInfoWtpManaged.0 = Gauge32: 3 # <--- number of controlled APs
FORTINET-FORTIGATE-MIB::fgWcInfoWtpSessions.0 = Gauge32: 3
FORTINET-FORTIGATE-MIB::fgWcInfoStationCapacity.0 = Gauge32: 0
FORTINET-FORTIGATE-MIB::fgWcInfoStationCount.0 = Gauge32: 28
```

In every table the APs are enumerated by their serial number. Example:


```
$ snmpwalk -m +FORTINET-FORTIGATE-MIB -v2c -cpublic  $IP fgWcWtpSessionWtpId 
FORTINET-FORTIGATE-MIB::fgWcWtpSessionWtpId.1."FP320C3X16000XXX" = STRING: FP320C3X16000XXX
FORTINET-FORTIGATE-MIB::fgWcWtpSessionWtpId.1."FP320C3X16000YYY" = STRING: FP320C3X16000YYY
FORTINET-FORTIGATE-MIB::fgWcWtpSessionWtpId.1."FP320C3X16000ZZZ" = STRING: FP320C3X16000ZZZ
```

```
$ snmpwalk -m +FORTINET-FORTIGATE-MIB -v2c -cpublic  $IP fgWcWtpSessionWtpStationCount 
FORTINET-FORTIGATE-MIB::fgWcWtpSessionWtpStationCount.1."FP320C3X16000XXX" = Gauge32: 17
FORTINET-FORTIGATE-MIB::fgWcWtpSessionWtpStationCount.1."FP320C3X16000YYY" = Gauge32: 10
FORTINET-FORTIGATE-MIB::fgWcWtpSessionWtpStationCount.1."FP320C3X16000ZZZ" = Gauge32: 1
```

Is there any way I can tell snmp_exporter to auto create an index between 1 and fgWcInfoWtpManaged.0?
Or any other way to get those to scrape correctly?

**Comment by brian-brazil** [comment]
> Is there any way I can tell snmp_exporter to auto create an index between 1 and fgWcInfoWtpManaged.0?

The index is already there, it's the `.1.` in your output.

You need:

```
      indexes:
        - fgVdEntIndex
          type: Integer32
        - labelname: fgWcWtpSessionWtpId
          type: String
```

**Comment by elisiano** [comment]
Updated module config:
```
fn_fg_test:
  walk:
    - 1.3.6.1.2.1.1.3
    - 1.3.6.1.4.1.12356.101.3.2.1.1.1.1
    - 1.3.6.1.4.1.12356.101.14.4.4.1.1
    - 1.3.6.1.4.1.12356.101.14.4.4.1.17
  metrics:
    - name: sysUpTime
      oid: 1.3.6.1.2.1.1.3
    - name: fgWcWtpSessionWtpStationCount
      oid: 1.3.6.1.4.1.12356.101.14.4.4.1.17
      indexes:
        - labelname: fgVdEntIndex
          type: Integer32
        - labelname: fgWcWtpSessionWtpId
          type: String
      lookups:
        - labels: [fgVdEntIndex]
          labelname: fgVdEntIndex
          oid: 1.3.6.1.4.1.12356.101.3.2.1.1.1.1
        - labels: [fgWcWtpSessionWtpId]
          labelname: fgWcWtpSessionWtpId
          oid: 1.3.6.1.4.1.12356.101.14.4.4.1.1
```

Output: 
```
An error has occurred during metrics gathering:

2 error(s) occurred:
* collected metric fgWcWtpSessionWtpStationCount label:<name:"fgVdEntIndex" value:"1" > untyped:<value:5 >  was collected before with the same name and label values
* collected metric fgWcWtpSessionWtpStationCount label:<name:"fgVdEntIndex" value:"1" > untyped:<value:0 >  was collected before with the same name and label values
```
