### ISSUE TITLE
snmp_exporter can't export OIDs served by uWSGI

### ISSUE THREAD

**Issue by jankoprowski** [prometheus/snmp_exporter#701]
### Host operating system: output of `uname -a`

```bash
Linux intel 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### snmp_exporter version: output of `snmp_exporter -version`
```bash
$ ./snmp_exporter -version
snmp_exporter: error: unknown short flag '-v', try --help
```

### What device/snmpwalk OID are you using?
uWSGI exported SNMP OIDs

### If this is a new device, please link to the MIB(s).
There are no MIBS

### What did you do that produced an error?
You will need:
* Python 3.9
* uWSGI 2.0.20
* Flask 2.0.2

```bash
python 3.9 -m venv venv
. venv/bin/activate
pip install uwsgi
pip install flask
```

Create a Python file `hello.py`

```python
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"
```

Run uwsgi: `uwsgi --module hello --http-socket 8080 --stats :30059 --stats-http --snmp=:30022 --snmp-community public --metrics-dir metrics --enable-metrics`

Check following oids:

```bash
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.5.3
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.5.4
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.5.5
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.1.1
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.3.0.1
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.5.100
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.5.101
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.5.102
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.5.103
snmpget -v2c -c public 127.0.0.1:30022  1.3.6.1.4.1.35156.17.7.0.1
```

And check following `config.yml` file for snmp_exporter:

```yaml
uwsgi:
  get:
    - 1.3.6.1.4.1.35156.17.5.3
    - 1.3.6.1.4.1.35156.17.5.4
    - 1.3.6.1.4.1.35156.17.5.5
    - 1.3.6.1.4.1.35156.17.1.1
    - 1.3.6.1.4.1.35156.17.3.0.1
    - 1.3.6.1.4.1.35156.17.5.100
    - 1.3.6.1.4.1.35156.17.5.101
    - 1.3.6.1.4.1.35156.17.5.102
    - 1.3.6.1.4.1.35156.17.5.103
    - 1.3.6.1.4.1.35156.17.7.0.1
  version: 2
  auth:
    community: public
  metrics:
    - name: busy_workers
      oid: 1.3.6.1.4.1.35156.17.5.3
      type: gaugly
    - name: idle_workers
      oid: 1.3.6.1.4.1.35156.17.5.4
      type: gaugly
    - name: overloaded
      oid: 1.3.6.1.4.1.35156.17.5.5
      type: counter
    - name: total_requests
      oid: 1.3.6.1.4.1.35156.17.1.1
      type: counter
    - name: worker_0_requets
      oid: 1.3.6.1.4.1.35156.17.3.0.1
      type: counter
    - name: total_trasmited_data
      oid: 1.3.6.1.4.1.35156.17.5.100
      type: counter
    - name: rss_memory_total
      oid: 1.3.6.1.4.1.35156.17.5.101
      type: gauge
    - name: vsz_memory_total
      oid: 1.3.6.1.4.1.35156.17.5.102
      type: gauge
    - name: avg_response_time
      oid: 1.3.6.1.4.1.35156.17.5.103
      type: gauge
    - name: avg_response_time
      oid: 1.3.6.1.4.1.35156.17.7.0.1
      type: gauge
```

run: `./snmp_exporter --config.file=config.yml`

and run: `curl 'http://localhost:9116/snmp?target=127.0.0.1:30022&module=uwsgi'`

### What did you expect to see?

Regular promethes metrics output

### What did you see instead?

```bash
An error has occurred while serving metrics:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: error getting target 127.0.0.1: request timeout (after 3 retries)
```
