### ISSUE TITLE
Different xType create different enum_values in labels display

### ISSUE THREAD

**Issue by shulianwang** [prometheus/snmp_exporter#707]
### What did you do that produced an error?
![image](https://user-images.githubusercontent.com/61801885/143226726-e2ded1a2-231a-4c0f-962e-62b5fa2910ab.png)

[root@localhost snmp_p]# snmpwalk -v2c -c iDCXM2020  192.168.10.11 hrStorageType
HOST-RESOURCES-MIB::hrStorageType.1 = OID: HOST-RESOURCES-TYPES::hrStorageRam
HOST-RESOURCES-MIB::hrStorageType.3 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.6 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.7 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.8 = OID: HOST-RESOURCES-TYPES::hrStorageOther
HOST-RESOURCES-MIB::hrStorageType.10 = OID: HOST-RESOURCES-TYPES::hrStorageVirtualMemory
HOST-RESOURCES-MIB::hrStorageType.31 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.36 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.38 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.39 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk
HOST-RESOURCES-MIB::hrStorageType.57 = OID: HOST-RESOURCES-TYPES::hrStorageFixedDisk

hrStorageIndex{hrStorageDescr="/", hrStorageType="1.3.6.1.2.1.25.2.1.4", instance="192.168.10.11", job="snmpexporter_test2"}
### What did you expect to see?

hrStorageIndex{hrStorageDescr="/", hrStorageType=" hrStorageFixedDisk", instance="192.168.10.11", job="snmpexporter_test2"}
### What did you see instead?

Cause Analysis; _____
example:
create enum_values : ifOperStatus , .1.3.6.1.2.1.2.2.1.8 , ifType  .1.3.6.1.2.1.2.2.1.3  , hrSWRunType.1.3.6.1.2.1.25.4.2.1.6
not create enum_values : hrStorageType  .1.3.6.1.2.1.25.2.1 , hrDeviceTypes  .1.3.6.1.2.1.25.3.1

hrStorageType and  hrDeviceTypes is different from  ifType ，It will not be generated in the configuration of the enumerated type，So, Any good ideas?

**Comment by kidiboy** [comment]
Any update on this? @SuperQ

**Comment by ptimofee** [comment]
I'm wondering how to solve this as well

**Comment by SuperQ** [comment]
It looks like these use a `TEXTUAL-CONVENTION` of type `AutonomousType`. This is not currently handled. We would need to implement special handling for this conversion.

**Comment by hpaluch-pil** [comment]
I use this workaround until this issue is resolved - added to my `prometheus.yml` section:
```yaml
 scrape_configs:
  - job_name: snmp-example
    # other SNMP exporter config here and then:
    metric_relabel_configs:
      - source_labels: [hrStorageType]
        target_label: hrStorageType
        regex: '^1\.3\.6\.1\.2\.1\.25\.2\.1\.4$'
        replacement: "FixedDisk"
      - source_labels: [hrStorageType]
        target_label: hrStorageType
        regex: '^1\.3\.6\.1\.2\.1\.25\.2\.1\.7$'
        replacement: "CompactDisc"
      - source_labels: [hrStorageType]
        target_label: hrStorageType
        regex: '^1\.3\.6\.1\.2\.1\.25\.2\.1\.3$'
        replacement: "VirtualMemory"
      - source_labels: [hrStorageType]
        target_label: hrStorageType
        regex: '^1\.3\.6\.1\.2\.1\.25\.2\.1\.2$'
        replacement: "Ram"
```

It will replace, for example:
- exporter: `hrStorageUsed{hrStorageDescr="C:\\ Label:... Serial Number ...",hrStorageIndex="1",hrStorageType="1.3.6.1.2.1.25.2.1.4"} 3.773956e+07`
- Prometheus Query `hrStorageUsed` returns: `hrStorageUsed{hrStorageDescr="C:\ Label:... Serial Number...",hrStorageIndex="1",hrStorageType="FixedDisk",other="keys..."}`

It works at Prometheus level (not at SNMP scrapper level). Yes it is dumb solution, but good enough for me.
