### ISSUE TITLE
Fix description section Configuration

### ISSUE THREAD

**Issue by HappyFX** [prometheus/snmp_exporter#718]
In documentation https://github.com/prometheus/snmp_exporter#prometheus-configuration `module` variable is a list, but you can't use it like real list.

Working ok:

```yaml
- job_name: 'working ok'
  params:
      module: [if_mib]
```

Failed:

```yaml
- job_name: 'failed 400 error'
  params:
    module: [if_mib,cisco_wlc]
```

Actual error in prometheus `server returned HTTP status 400 Bad Request`

Make `module` variable as a string
