### ISSUE TITLE
Lookups are not displayed as labels in the metrics

### ISSUE THREAD

**Issue by afernandezrios90** [prometheus/snmp_exporter#729]
### snmp_exporter version: output of `snmp_exporter -version`
v0.20.0

### What device/snmpwalk OID are you using?
Cisco Switch N5696Q

### What did you do that produced an error?
I tried to add extra lookups to have the device name (sysName) as a label for further filtering by the name, but the exporter ignores the lookup. 

Relevant piece of `snmp.yml` configuration:
```yaml
metrics:
 #ciscoSystemInfo
 - name: cseSysCPUUtilization
   oid: 1.3.6.1.4.1.9.9.305.1.1.1
   type: gauge
   lookups:
   - labels:
     labelname: sysName
     oid: 1.3.6.1.2.1.1.5.0
     type: DisplayString
 - name: cseSysMemoryUtilization
   oid: 1.3.6.1.4.1.9.9.305.1.1.2
   type: gauge
   lookups:
   - labels:
     labelname: sysName
     oid: 1.3.6.1.2.1.1.5.0
     type: DisplayString
```

### What did you expect to see?
'sysName' is added as a label in the metrics. Example working fine (using another exporter, probably a fork of this one: [oakman/snmp-exporter](https://github.com/oakman/snmp-exporter)

```
# HELP cseSysCPUUtilization 
# TYPE cseSysCPUUtilization gauge
cseSysCPUUtilization{sysName="N5696Q-PAO-PA4-101"} 10
# HELP cseSysMemoryUtilization 
# TYPE cseSysMemoryUtilization gauge
cseSysMemoryUtilization{sysName="N5696Q-PAO-PA4-101"} 15
```

### What did you see instead?
Metrics without the sysName:

```
# HELP cseSysCPUUtilization 
# TYPE cseSysCPUUtilization gauge
cseSysCPUUtilization 13
# HELP cseSysMemoryUtilization 
# TYPE cseSysMemoryUtilization gauge
cseSysMemoryUtilization 15
```
