### ISSUE TITLE
Can multiple modules be supported？

### ISSUE THREAD

**Issue by linqianye** [prometheus/snmp_exporter#731]
hello,
Can SNMP exporter support multiple modules to adapt to private MIBs of different vendors?
Now it's like this in prometheus.yml,

```yaml
  - job_name: 'test-switch'
    scrape_interval: 60s
    static_configs:
     - targets:
       - 172.22.1.57
       - 172.22.1.58
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116
```
In the code above, can you realize the following functions?

```yaml
  - job_name: 'test-switch'
    scrape_interval: 60s
    static_configs:
     - targets:
       - 172.22.1.57
       - 172.22.1.58
    metrics_path: /snmp
    params:
      modules:
      - if_mib
      - cisco_bgp
      - juniper_ospf
```

**Comment by mv-rodriguez** [comment]
Hi, the way I do it is using relabeling on prometheus.yml:
```
- job_name: snmp
  honor_labels: true
  metrics_path: /snmp
  params:
    module: [generic]
  file_sd_configs:
  - files:
    - 'snmp/snmp_targets.json'
  relabel_configs:
    - source_labels: [__module]
      target_label: __param_module
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp_exporter:9116
```
In the _snmp_targets.json_ there is a disposable label "__module" that defines the specific snmp module the target should use.  I'm not sure if the "honor_labels" option is required though, but as the saying says _"if it is working..."_
