### ISSUE TITLE
Generator: Allow metric label name and value rewrites

### ISSUE THREAD

**Issue by jelmd** [prometheus/snmp_exporter#741]
It would be nice to support label name and label value rewrites in the generator. AFAIC the snmp-exporter just uses the numeric OIDs to query the target and uses `labelname` value to emit the labelname. So the generator just needs to accept and pass it.  The other nice to have is to be able to replace the values of a label.

E.g.:
```
# snmpbulkwalk -Lf /tmp/log -v 2c -c public -Pw -Pu -OX cisco_machine ciscoEnvMonTemperatureStatusTable
CISCO-ENVMON-MIB::ciscoEnvMonTemperatureStatusDescr[1006] = STRING: Switch#1, Sensor#1, Status is GREEN
CISCO-ENVMON-MIB::ciscoEnvMonTemperatureStatusValue[1006] = Gauge32: 27 degrees Celsius
CISCO-ENVMON-MIB::ciscoEnvMonTemperatureThreshold[1006] = INTEGER: 60 degrees Celsius
CISCO-ENVMON-MIB::ciscoEnvMonTemperatureLastShutdown[1006] = INTEGER: 0 degrees Celsius
CISCO-ENVMON-MIB::ciscoEnvMonTemperatureState[1006] = INTEGER: normal(1)
CISCO-ENVMON-MIB::ciscoEnvMonTemperatureStatusValueRev1[1006] = INTEGER: 27 degrees Celsius
```
The index number is not really something we wanna see, so we use the generator snippet:
```
    lookups:
      - source_indexes: [ciscoEnvMonTemperatureStatusIndex]
        lookup: ciscoEnvMonTemperatureStatusDescr
        drop_source_indexes: true
```
But this produces not what is desired either, because the description contains the current state of the sensor as well. E.g.:
```
ciscoEnvMonTemperatureLastShutdown{ciscoEnvMonTemperatureStatusDescr="Switch#1, Sensor#1, Status is GREEN "} 0
ciscoEnvMonTemperatureState{ciscoEnvMonTemperatureStatusDescr="Switch#1, Sensor#1, Status is GREEN "} 1
ciscoEnvMonTemperatureStatusValue{ciscoEnvMonTemperatureStatusDescr="Switch#1, Sensor#1, Status is GREEN "} 26
ciscoEnvMonTemperatureStatusValueRev1{ciscoEnvMonTemperatureStatusDescr="Switch#1, Sensor#1, Status is GREEN "} 26
ciscoEnvMonTemperatureThreshold{ciscoEnvMonTemperatureStatusDescr="Switch#1, Sensor#1, Status is GREEN "} 60
```
So having something like this would be nice:
```
    lookups:
      - source_indexes: [ciscoEnvMonTemperatureStatusIndex]
        lookup: ciscoEnvMonTemperatureStatusDescr
        - name: sensor
        - regex: '(Switch#[0-9]+, Sensor#[0-9]+),.*'
        - value: '$1'
        drop_source_indexes: true
```
So that we finally get:
```
ciscoEnvMonTemperatureLastShutdown{sensor="Switch#1, Sensor#1"} 0
ciscoEnvMonTemperatureState{sensor="Switch#1, Sensor#1"} 1
ciscoEnvMonTemperatureStatusValue{sensor="Switch#1, Sensor#1"} 26
ciscoEnvMonTemperatureStatusValueRev1{sensor="Switch#1, Sensor#1"} 26
ciscoEnvMonTemperatureThreshold{sensor="Switch#1, Sensor#1"} 60
```
