### ISSUE TITLE
namespaces with switches

### ISSUE THREAD

**Issue by inetman28** [prometheus/snmp_exporter#746]
Hi, I faced with difficulties which, as I think, aren't problems for snmp_exporter's community )

I try to get snmp metrics from different namespaces (in network switches they are named "VRF"). I have few VRFs, for example: INFRA, STAGING, PROD, etc...

VRFs/Namespaces in snmp_exporter generator are named like "context" and defined under "**context_name**" variable.

and now I'd like to get metrics from different namespaces

are there any ways to write one snmp_exporter module for all VRF? or only do we have option to make one module per each VRF? For example I'd like to have module with name "arista_sw99" which gather metrics from each vrf. Can I do that? 
Example snmp generator config below.

Thank everyone in advance. 

```
 arista_sw99:

    version: 3  # SNMP version to use. Defaults to 2.
                # 1 will use GETNEXT, 2 and 3 use GETBULK.
    max_repetitions: 25  # How many objects to request with GET/GETBULK, defaults to 25.
                        # May need to be reduced for buggy devices.
    retries: 3   # How many times to retry a failed request, defaults to 3.
    timeout: 120s  # Timeout for each individual SNMP request, defaults to 5s.
    
    auth:
      [users and pass were omitted]
      context_name: STAGING 

    walk:
      - 1.3.6.1.4.1.30065.4.1	# aristaBgp4V2
    overrides:
      ifType:
        type: EnumAsInfo
```
