### ISSUE TITLE
Workarounds needed for Palo Alto

### ISSUE THREAD

**Issue by gsperry2011** [prometheus/snmp_exporter#760]
This is not intended to be a bug report where I expect things to be fixed but I do think it is a place other folks might come looking (like I did) to fix the numerous issues with using this snmp_exporter and generator to collect metrics from Palo Alto firewalls. None of the issues described here are problems with this exporter or generator (I think). What I believe is that the MIBs from Palo aren't exactly standard which causes issues with the snmp_exporter as it relies on the manufacturers MIBs.

First issue: 

This is a relatively common one I found quickly online. The work around involves editing the MIBs downloaded from Palo to prevent conflicts with `ifIndex` and `ifDesc` and then re-generating snmp.yml. The generator.yml already has some logic in place to work around Palo's conflicting OIDs but doesn't account for this issue yet (and I don't expect it to). I found the issue described in detail and workaround here: https://github.com/prometheus/snmp_exporter/issues/623 

Second issue:

This one I couldn't find documented anywhere and took some digging. I grabbed a dashboard for Palo from Grafana's website: https://grafana.com/grafana/dashboards/13907 - This has a widgit which queries for `panChassisType` which was blank for me and not a metric Prometheus was collecting. After some digging I discovered that for some reason unknown to me at the moment, while `panChassisType` is found in the Palo MIBs, the generator doesn't create this as an OID to collect. This is the value required to read the "model" of the Palo e.g. `PA-3060`. If I manually edit a generated snmp.yml to add the the following lines, the exporter does successfully collect it. 

```
paloalto_fw:
  walk:
  - 1.3.6.1.2.1.2
  - 1.3.6.1.2.1.25.1
  - 1.3.6.1.2.1.25.2
  - 1.3.6.1.2.1.25.3
  - 1.3.6.1.4.1.25461.2.1.2.1
  - 1.3.6.1.4.1.25461.2.1.2.3
  - 1.3.6.1.4.1.25461.2.1.2.5
  - 1.3.6.1.4.1.25461.2.1.2.2.1.0                        # <--- Added line
  get:
  - 1.3.6.1.2.1.1.3.0
  metrics:
  - name: panChassisType                                # <--- Added line
    oid: 1.3.6.1.4.1.25461.2.1.2.2.1.0                 # <--- Added line
    type: DisplayString                                        # <--- Added line
    help: String of the model of palo firewall model. e.g. PA-3060 - 1.3.6.1.4.1.25461.2.1.2.2.1.0       # <--- Added line
```
