### ISSUE TITLE
Problem with index on AKCP Device

### ISSUE THREAD

**Issue by miroth70** [prometheus/snmp_exporter#789]
I tried to configure a new SNMP Device from AKCP, a Security Probe+.

Usually the index is an integer value, but not in this case, the index constists of an sub oid.

```
iso.3.6.1.4.1.3854.3.5.2.1.1.0.0.0.0.0 = STRING: "0.0.0.0.0"
iso.3.6.1.4.1.3854.3.5.2.1.1.0.0.0.0.1 = STRING: "0.0.0.0.1"
iso.3.6.1.4.1.3854.3.5.2.1.1.0.0.0.0.2 = STRING: "0.0.0.0.2"
iso.3.6.1.4.1.3854.3.5.2.1.1.0.0.0.1.1 = STRING: "0.0.0.1.1"
```

I use the following generator configuration

```
  akcp_securityprobe_plus:
    version: 2
    auth:
      community: *********
    walk:
    - sysName
    - sysLocation
    - temperatureDegree
    lookups:
    - source_indexes: [temperatureIndex]
      lookup: temperatureDescription
      drop_source_indexes: true
```

If I try to call the date I got some error messages

```
3 error(s) occurred:
* collected metric "temperatureDegree" { label:<name:"temperatureDescription" value:"" > gauge:<value:22 > } was collected before with the same name and label values
* collected metric "temperatureDegree" { label:<name:"temperatureDescription" value:"" > gauge:<value:23 > } was collected before with the same name and label values
* collected metric "temperatureDegree" { label:<name:"temperatureDescription" value:"" > gauge:<value:23 > } was collected before with the same name and label values
```
I see two Problems, the first is that the label temperatureDescription has no value.
The second is that I've only three Entries, but there are four

temperatureDegree = iso.3.6.1.4.1.3854.3.5.2.1.3
```
iso.3.6.1.4.1.3854.3.5.2.1.3.0.0.0.0.0 = INTEGER: 23
iso.3.6.1.4.1.3854.3.5.2.1.3.0.0.0.0.1 = INTEGER: 23
iso.3.6.1.4.1.3854.3.5.2.1.3.0.0.0.0.2 = INTEGER: 23
iso.3.6.1.4.1.3854.3.5.2.1.3.0.0.0.1.1 = INTEGER: 3
```
Is it possible that the Prometheus SNMP Exporter can not handle this kind of index ?
