### ISSUE TITLE
Excuse me, how do I set up multiple module queries? [error:'module' parameter must only be specified once]

### ISSUE THREAD

**Issue by harvey945** [prometheus/snmp_exporter#798]
## prometheus setting.
```
  - job_name: 'snmp'
    scrape_interval: 2m
    scrape_timeout: 2m
    file_sd_configs:
    - files:
        - conf.d/icmp/snmp_exporter.yaml
    metrics_path: /snmp
    params:
      module: [HUAWEI-ENTITY-EXTENT-MIB,BRIDGE-MIB,LLDP-MIB,VRRP-MIB,HUAWEI-IF-EXT-MIB,ENTITY-MIB,HUAWEI-STACK-MIB,if_mib]
      #module: [HUAWEI-ENTITY-EXTENT-MIB]
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 172.16.80.113:9184
```
`module: [HUAWEI-ENTITY-EXTENT-MIB,BRIDGE-MIB,LLDP-MIB,VRRP-MIB,HUAWEI-IF-EXT-MIB,ENTITY-MIB,HUAWEI-STACK-MIB,if_mib]`not allowed.

## url
```
http://172.16.80.113:9184/snmp?module=HUAWEI-ENTITY-EXTENT-MIB&module=BRIDGE-MIB&module=LLDP-MIB&module=VRRP-MIB&module=HUAWEI-IF-EXT-MIB&module=ENTITY-MIB&module=HUAWEI-STACK-MIB&module=if_mib&target=10.16.3.114
```
`module' parameter must only be specified once.`

how can i solve this problem?

![image](https://user-images.githubusercontent.com/93895686/190331956-a7fb2d47-8b0a-4b62-ae75-f95ea487ef00.png)
