### ISSUE TITLE
Multi-Level OID as Index

### ISSUE THREAD

**Issue by mvtechteam** [prometheus/snmp_exporter#853]
So I know that you can loop through many OIDs via indexes, but the traditional method of doing that only allows you to do the next proceeding OID level. I have this linux system that assigns very long OIDs to individual components, but those have the same proceeding OID for the name and state (as highlighted in the photo). I was wondering if there is a way to capture that many-level proceeding OID and use it to uniquely label each entry. I tried it the traditional way, but the next OID can repeat sometimes and doesn't make it unique.

```
Test_Module:
  walk:
  - 1.3.6.1.4.1.10704.1.0.1
  metrics:
  - name: state
    oid: 1.3.6.1.4.1.10704.1.0.1.2 #grab the state of the service
    type: gauge
    indexes:
    - labelname: oidIndex #here would be the long many-level unique OID for that entry
      type: gauge
    lookups:
    - labels:
      - oidIndex
      labelname: name
      oid: 1.3.6.1.4.1.10704.1.0.1.1 #add a label with the name (unique identifier)
      type: DisplayString
```

![image](https://user-images.githubusercontent.com/116840530/221671133-c5be825a-9bae-4827-a23d-d88130495c9b.png)

![image](https://user-images.githubusercontent.com/116840530/221671363-b35fc78e-62aa-43af-a7a4-670d05aef65b.png)

**Comment by mvtechteam** [comment]
Just figured it out right after posting! Gonna put the answer for others.

I simply changed the "type" in the indexes to "DisplayString" and that told the exporter to use the entire multi-level OID for the label lookups. Working great!

```
Test_Module:
  walk:
  - 1.3.6.1.4.1.10704.1.0.1
  metrics:
  - name: state
    oid: 1.3.6.1.4.1.10704.1.0.1.2 #grab the state of the service
    type: gauge
    indexes:
    - labelname: oidIndex #here would be the long many-level unique OID for that entry
      type: DisplayString # <--- changed from gauge to DisplayString
    lookups:
    - labels:
      - oidIndex
      labelname: name
      oid: 1.3.6.1.4.1.10704.1.0.1.1 #add a label with the name (unique identifier)
      type: DisplayString
```
