### ISSUE TITLE
Feature: support for SNMP sequences

### ISSUE THREAD

**Issue by llamafilm** [prometheus/snmp_exporter#942]
I'd like to monitor SNMP data for an LED video wall.  The wall is made of 72 "display units", each of which contains 12 "cells".  Each cell reports its temperature, indexed by the Unit ID.  Since the temperature is defined as a DisplayString, I use the following override to turn it into float:

```yaml
    overrides:
      ledCellStatusTemperatureCell1:
        regex_extracts:
          '':
            - regex: '(.*)'
              value: '$1'
```
That works well, but I have to copy this 12 times in the generator.  It would be nice for this app to parse sequences

### What device/snmpwalk OID are you using?
Sony [PROV1-LEDDISPLAY-MIB.txt](https://github.com/prometheus/snmp_exporter/files/12325188/PROV1-LEDDISPLAY-MIB.txt) `1.3.6.1.4.1.122.8501.3.128.13.1`
