### ISSUE TITLE
Configure many SNMP authentication method in the same snmp.yml

### ISSUE THREAD

**Issue by balioune** [prometheus/snmp_exporter#984]
Hi all,
I'm using snmp_exporter to to monitor my routers. some of my routers use SNMP v2 and others SNMP v3.
I would like to know how to set the SNMP v2 community and credential of SNMP  v3 in the same snmp.yml ?
The ideal is to have all authentication method in the same configuration file.

BR

**Comment by candlerb** [comment]
Splitting out of auth creds has been available since snmp_exporter 0.23.0 The file [auth-split-migration.md](https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md) explains how to use it.

At scrape time you have to provide `target`, `module` and `auth` query params.  These can come directly from your targets file, e.g.

```
- labels:
    __param_auth: auth1
    __param_module: if_mib
  targets:
    - 1.1.1.1
    - 2.2.2.2
- labels:
    __param_auth: auth2
    __param_module: if_mib
  targets:
    - 3.3.3.3
    - 4.4.4.4
```

or, in more sophisticated configs, from relabelling rules.

Also, as of 0.24.0 you can have multiple configuration files which are merged together, each of which can contain modules, auths, or both. You do this using repeated `--config.file` arguments, and/or by providing a glob pattern like `--config.file=/etc/prometheus/snmp.d/*.yml`
