### ISSUE TITLE
20,000 interfaces, possible with snmp_exporter ?

### ISSUE THREAD

**Issue by j-oss2023** [prometheus/snmp_exporter#991]
### Host operating system: output of `uname -a`
docker

### snmp_exporter version: output of `snmp_exporter -version`
ts=2023-09-04T09:42:07.920Z caller=main.go:196 level=info msg="Starting snmp_exporter" version="(version=0.24.0, branch=HEAD, revision=c9fd025309572b81eaca65100de4ca38ea406da9)" concurrency=1

### What device/snmpwalk OID are you using?
```yaml
  if_mib:
    max_repetitions: 2000  # How many objects to request with GET/GETBULK, defaults to 25.
    retries: 3   # How many times to retry a failed request, defaults to 3.
    timeout: 10m # Timeout for each walk, defaults to 10s.
    walk:
    - 1.3.6.1.2.1.2
    - 1.3.6.1.2.1.31.1.1
    get:
    - 1.3.6.1.2.1.1.3.0
    - 1.3.6.1.2.1.1.5.0
```

### What did you do that produced an error?
start snmp_exporter

### What did you expect to see?
Gather metrics for prometheus

### What did you see instead?
Timeout

Wondering what is the limitations of snmp_exporter, I have a Juniper JNP10003 [MX10003] Edge Router with roughly 20,000 interfaces (including sub interfaces)

No matter what I've tried, it times out.... I understand that it's quite a lot of data for a single HTTP request so i'm just wondering how to tackle this ? 

Thank you in advance
